### ISSUE TITLE
container_linux.go:247: starting container process caused "exec: \"/pause\": stat /pause: no such file or directory"

### ISSUE THREAD

**Issue by runcom** [kubernetes-incubator/cri-o#102]
just `make binaries` and then try to run something starting ocid with paths to conmon/pause binaries /cc @cyphar 

```
$ sudo ./ocid --pause /home/amurdaca/src/github.com/kubernetes-incubator/cri-o/pause/pause --runtime /usr/local/sbin/runc --debug --conmon $PWD/conmon/conmon & OCID_PID=$!
[1] 22136
$ INFO[0000] Starting reaper                              
E1006 18:10:39.956877   22145 ocicni.go:136] error updating cni config: No networks found in /etc/cni/net.d
DEBU[0000] sandboxes: map[]                             
DEBU[0000] containers: &{map[] {{0 0} 0 0 0 0}}         

$ ‹master› sudo ./ocic pod create --name pod1 --config test/testdata/sandbox_config.json
container_linux.go:247: starting container process caused "exec: \"/pause\": stat /pause: no such file or directory"
conmon: Failed to create container
FATA[0000] Creating the pod sandbox failed: rpc error: code = 2 desc = reading pid from init pipe: EOF 
INFO[0009] Signal received: child exited                
INFO[0009] Reaped process with pid 22195
```

**Comment by rhatdan** [comment]
I am seeing the same thing.

**Comment by mrunalp** [comment]
Strange. It works fine for me :/ What OS are you testing on?

**Comment by runcom** [comment]
Fedora 24

**Comment by mrunalp** [comment]
@runcom okay, I am testing on rawhide.

**Comment by rhatdan** [comment]
I am testing on rawhide and seeing the issue.  Perhaps there is something on your box making this work. Have you tried in a VM?

**Comment by mrunalp** [comment]
@rhatdan could be possible. I'll try it in a VM where I haven't run ocid before and report back here.

**Comment by mrunalp** [comment]
Hmm, I tried it in a new VM but still can't reproduce the issue.

**Comment by cyphar** [comment]
This works for me on openSUSE. Do you see the following line of debug output in the `ocid` terminal?

```
DEBU[0018] copying infra rootfs binary: /home/cyphar/src/cri-o/pause/pause -> /var/lib/ocid/graph/vfs/pause/rootfs/pause
```

**Comment by mrunalp** [comment]
One thing to ensure is whether the runc version is new enough (>=1.0.0.rc1)

**Comment by rhatdan** [comment]
rpm -q runc
runc-1.0.0-1.rc1.git04f275d.fc26.x86_64

**Comment by mrunalp** [comment]
@rhatdan That looks like it should work. Maybe tomorrow I can access your VM and take a look.

**Comment by runcom** [comment]
figured this out - @rhatdan you need to `rm -rf /var/lib/ocid/graph` and restart ocid (because that directory is already populated with a rootfs and it's failing to locate the binary somehow)

**Comment by runcom** [comment]
feel free to close this if removing the graph dir solves this issue for you

**Comment by rhatdan** [comment]
Yup that fixes the issue.  Although we probably should figure this out.

**Comment by rhatdan** [comment]
I now notice that the SELinux labels are not stored in the config.json.

**Comment by cyphar** [comment]
It should be noted that once #28 lands, we'll be able to entirely swap out the infra image setup code with OCI image setup code -- so the current hack I have of copying a static binary will no longer be necessary.

**Comment by runcom** [comment]
> I now notice that the SELinux labels are not stored in the config.json.

I'm working on this as part of #17 - we can save those as annotations I guess?
