### ISSUE TITLE
chmod of nonexistent file causes test suite to fail

### ISSUE THREAD

**Issue by edsantiago** [kubernetes-incubator/cri-o#1024]
Commit 8392f5f75 introduces a "Clean up network if pod sandbox fails" test in `network.bats`; this code does:

    chmod 0644 /go/src/github.com/kubernetes-incubator/cri-o/conmon/conmon

...which causes the unit tests to fail when running with cri-o as an rpm, not from source:

    not ok 8 Clean up network if pod sandbox fails
    # (in test file network.bats, line 174)
    #   `chmod 0644 /go/src/github.com/kubernetes-incubator/cri-o/conmon/conmon' failed

**Comment by edsantiago** [comment]
#1025

**Comment by rhatdan** [comment]
Any avc's?

**Comment by edsantiago** [comment]
In the original scenario I reported, or in #1025 ?

Original scenario: I didn't check, but I don't think so: nothing looks relevant in `/var/log/audit/audit.log`, and I wouldn't expect one anyway. Simple confirmation:

    shell1# tail -f /var/log/audit/audit.log

    shell2# chmod 644 /no/such/file
    (no new output in audit.log)

In #1025: no AVCs seen on my test run, in which `CONMON_BINARY=/usr/libexec/crio/conmon`. I can manually chmod it to 644 and back to 755 with, again, no new output in audit.log.

Does that answer your question?

**Comment by rhatdan** [comment]
Looks like this got merged.
