### ISSUE TITLE
Move crio.sock to /var/run/crio/crio.sock by default

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes-incubator/cri-o#1028]
Using crio.sock at the /var/run level means we cannot give a pod access to only the crio socket, such that a Kubernetes pod can hostPath mount only that directory.  It also is uncommon to mount in that directory - having a specific path would be more consistent with other users of /var/run

**Comment by rhatdan** [comment]
That is fine with me, and what I would prefer.

**Comment by rhatdan** [comment]
@mrunalp WDYT?

**Comment by mrunalp** [comment]
Sure, sounds good.

**Comment by mrunalp** [comment]
I'll make a PR to fix that.
