### ISSUE TITLE
Use single binary and dispatch on argv[0]

### ISSUE THREAD

**Issue by cgwalters** [kubernetes-incubator/cri-o#1034]
Today in the RPM:

```
-rwxr-xr-x    1 root    root                 56746744 Sep 20 15:06 /usr/bin/crio
-rwxr-xr-x    1 root    root                 24481408 Sep 20 15:06 /usr/bin/crioctl
-rwxr-xr-x    1 root    root                 55542096 Sep 20 15:06 /usr/bin/kpod
```

In contrast with kube;

```
# rpm -qlv kubernetes-master|grep /usr/bin
-rwxr-xr-x    3 root    root                109419520 Aug 10 10:47 /usr/bin/hyperkube
-rwxr-xr--    1 root    kube                124290232 Aug 10 10:47 /usr/bin/kube-apiserver
-rwxr-xr-x    3 root    root                109419520 Aug 10 10:47 /usr/bin/kube-controller-manager
-rwxr-xr-x    3 root    root                109419520 Aug 10 10:47 /usr/bin/kube-scheduler
```

So the single binary is larger, but it at least means the shared bits among them are shared.

(Another approach would be what systemd does with `/usr/lib/systemd/libsystemd-shared-233.so`)

**Comment by cgwalters** [comment]
This is what busybox does too of course, it's a classic Unix thing.

**Comment by rhatdan** [comment]
Well we want to split kpod from CRIO into a separate project, so you can install kpod without CRIO or vice versa.  (kpod has to be reamed first)

crioctl is supposed to go away and be replaces with crictl, which is a totally different project.

**Comment by ashcrow** [comment]
The background around this is the size of the resulting binaries and adding them to OS ISO's. @dustymabe noted the current footprint is around 132M on disk. ```strip``` seems to happily remove about 20MB. Are there possibly others things that could be done to reduce binary size? 

```
$ du -ch
131M    .
131M    total
# Strip each binary 
$ du -ch
112M    .
112M    total
```

**Comment by mrunalp** [comment]
:+1: We can try this out.

**Comment by sameo** [comment]
> We can try this out.

@mrunalp You mean stripping, right ?

**Comment by mrunalp** [comment]
@sameo I meant the busy-boxing with argv[0]. Any concerns? I guess even stripping is fine if it helps reduce the binary size further.

**Comment by rhatdan** [comment]
@mrunalp My problem with that is we lock kpod and crio together.  We are thinking about splitting them into two different packages, especially for RHEL.
Isn't crioctl supposed to go away and be replaced by crictl?

**Comment by runcom** [comment]
> Isn't crioctl supposed to go away and be replaced by crictl?

it is, that's the current plan, we already use crictl in tests bootstrap and some new tests

**Comment by rhatdan** [comment]
So if we move kpod into its own package and crioctl is replaced with crictl, we are doing work that will only shrink the size for a small time.  

Will stripping prevent debugging tools from being able to use the packages?

**Comment by ashcrow** [comment]
I believe by default it will remove debugging symbols. There is ``--only-keep-debug`` but I didn't check to see the size results.

**Comment by cyphar** [comment]
You don't want to use `strip` by the way, you want to pass `-s` as a build flag. `strip` has caused us problems in the past because it can corrupt the internal structure of Go binaries (since it doesn't use "traditional" `.a` structure and so on).

**Comment by rhatdan** [comment]
Should we make that the default in the Makefile?

**Comment by sameo** [comment]
@mrunalp stripping is fine, but combining crio and kpod in the same binary is quite inelegant imho. There's a reason why we want to separate them code wise :)

**Comment by sameo** [comment]
@rhatdan It would make sense, yes.

**Comment by runcom** [comment]
We're now stripping the binaries and kpod moved out this repo as well, going to close this but ping me if you still have concerns
