### ISSUE TITLE
fix issue with crio rpm

### ISSUE THREAD

**Issue by dustymabe** [kubernetes-incubator/cri-o#1035]
probably should open a BZ but this is easier. We need to fix this:

```
[vagrant@f27vanilla ~]$ sudo dnf install crio                                                                                                                                                
Fedora 27 - x86_64 - Test Updates                                                                                                                             23 MB/s |  20 MB     00:00    
Fedora 27 - x86_64 - Updates                                                                                                                                 2.1 kB/s | 373  B     00:00    
Fedora 27 - x86_64                                                                                                                                            12 MB/s |  58 MB     00:04    
Last metadata expiration check: 0:00:00 ago on Wed 18 Oct 2017 06:41:22 PM UTC.
Error: 
 Problem: conflicting requests
  - nothing provides runc >= 2:1.0.0-10 needed by cri-o-1.0.0-5.gita636972.fc27.x86_64
  - nothing provides runc >= 2:1.0.0-10 needed by cri-o-1.0.0.rc1-2.gitbb1da97.fc27.x86_64

```

**Comment by rhatdan** [comment]
Is it in updates-testing?

**Comment by rhatdan** [comment]
dnf info runc
Last metadata expiration check: 2:05:01 ago on Wed 18 Oct 2017 01:47:52 PM EDT.
Installed Packages
Name         : runc
Epoch        : 2
Version      : 1.0.0
Release      : 10.rc4.gitaea4f21.fc26
Arch         : x86_64
Size         : 7.1 M
Source       : runc-1.0.0-10.rc4.gitaea4f21.fc26.src.rpm
Repo         : @System
From repo    : updates
Summary      : CLI for running Open Containers
URL          : https://github.com/opencontainers/runc
License      : ASL 2.0
Description  : The runc command can be used to start containers which are packaged
             : in accordance with the Open Container Initiative's specifications,
             : and to manage containers running under runc.

**Comment by dustymabe** [comment]
this is an issue in f27, not f26.

**Comment by rhatdan** [comment]
I just pushed runc-1.0.0-11.rc4.gitaea4f21.fc2* into updates testing.  not sure why 10 never made it there.  Please check and update karma.

https://bodhi.fedoraproject.org/updates/FEDORA-2017-994680b67b
