### ISSUE TITLE
Image List should group same IDs and have a single list of repo tags

### ISSUE THREAD

**Issue by runcom** [kubernetes-incubator/cri-o#1048]
Reproducer is simple:

```sh
$ sudo ./crioctl image pull busybox:1-uclibc
$ sudo ./crioctl image pull busybox:1
$ sudo ./crioctl image list
# [...]
ID: 6ec8d0f6ad9ff4e226c0c334e1cfb3698138b9b2547ca82c17cd5c0610b80030
Tag: docker.io/library/busybox:1
Size: 1131313
ID: 6aa20173508fe850cfd9126bb2f0029e08a2da64194503131204b4ffc5d67846
Tag: docker.io/library/busybox:1-uclibc
Size: 1131313
```
It should rather be:
```sh
# [...]
ID: 6ec8d0f6ad9ff4e226c0c334e1cfb3698138b9b2547ca82c17cd5c0610b80030
Tag: docker.io/library/busybox:1, docker.io/library/busybox:1-uclibc
Size: 1131313
```
The issue is in the server of couse, crioctl is being used to exaplain the issue.

You can notice images should be grouped by image IDs (like docker does and kube does in the dockershim).
The huge issue is those images are the same but they have different IDs!!!!!!!

**Comment by runcom** [comment]
@nalind PTAL

**Comment by runcom** [comment]
@nalind the image ID you use in containers/image when Commit(ing) a new image isn't the "Config blog sha256" for that image. We need to use that to have same IDs for very same images in order to group them.

**Comment by baude** [comment]
@nalind was saying that the fix lies in https://github.com/kubernetes-incubator/cri-o/pull/654
