### ISSUE TITLE
Share constants between C and Go code

### ISSUE THREAD

**Issue by mrunalp** [kubernetes-incubator/cri-o#1060]
We have some duplicated constants between Go code and conmon that we should move to a header file.

**Comment by fntlnz** [comment]
@mrunalp I'm waiting for @rhatdan to reply [this comment](https://github.com/kubernetes-incubator/cri-o/pull/1052/files/e66da6046d0e8eef1d5eeb949579ba6dd843f88c#r151841747) to know if we need to share `/var/run/crio` too.
If you think that there's something else please let me know.

**Comment by jvanz** [comment]
I think this issue can be closed. The issue #1164 has already started to work on this. There is a PR waiting to be merge.

**Comment by rhatdan** [comment]
We now share.
