### ISSUE TITLE
No 'CONTRIBUTING.md' was found.

### ISSUE THREAD

**Issue by lubinsz** [kubernetes-incubator/cri-o#1071]
Hi all,
What is the agreement for contributions?

It seems that I didn't find the inbound agreement.
In general, the inbound license should be 'Developer Certificate of Origin, version 1.1'.
The outbound license should be 'Apache License 2.0'
And the legal information of inbound license should be in CONTRIBUTING.md.

My boss want to know the inbound license of this project and the link.

Thanks.

**Comment by rhatdan** [comment]
@lubinsz We have merged in CONTRIBUTING.md, does this satisfy your needs?
