### ISSUE TITLE
k8s doesn't show cri-o version information

### ISSUE THREAD

**Issue by vbatts** [kubernetes-incubator/cri-o#1123]
**Description**
when running kubernetes with cri-o does not report container runtime version

**Steps to reproduce the issue:**
1. `kubectl describe nodes`
2.
3.

**Describe the results you received:**
```
 Container Runtime Version:     runc://Unknown
```

**Describe the results you expected:**
Actual version info?

**Additional information you deem important (e.g. issue happens only occasionally):**
https://github.com/kubernetes/kubernetes/blob/04b876e/pkg/kubelet/kubelet_node_status.go#L660

**Output of `crio --version`:**

```
$ minikube ssh -- sudo crio --version
crio version 
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
ohman. could this be an issue with how cri-o is built for minikube? :-\

**Comment by runcom** [comment]
> ohman. could this be an issue with how cri-o is built for minikube? :-\

great question, are you building with the makefile? actually, that version call in kubelet shouild not error out :confused:

**Comment by runcom** [comment]
```
Container Runtime Version:  cri-o://1.8.0-dev
 Kubelet Version:            v1.8.1-1+41a4b274a83e32
 Kube-Proxy Version:         v1.8.1-1+41a4b274a83e32
```
This is fixed in master and >= 1.0.1 via https://github.com/kubernetes-incubator/cri-o/commit/7efdae80bcb55b488956063f3bba965960b45d3c

**Comment by vbatts** [comment]
v1.0.0 and makefile

**Comment by vbatts** [comment]
I'll open a PR to minikube then :smile:

**Comment by vbatts** [comment]
https://github.com/kubernetes/minikube/pull/2160
