### ISSUE TITLE
kpod load always throw out message "trying to pull xxx"

### ISSUE THREAD

**Issue by gouyang** [kubernetes-incubator/cri-o#1125]
It throw out the message even with `--quiet`. 

```
# ./bin/kpod load -q -i pause.tar
Trying to pull gcr.io/google_containers/pause-amd64:3.0...
```

**Comment by rhatdan** [comment]
kpod is moving over to https://github.com/projectatomic/libpod  Please open issues there.

**Comment by rhatdan** [comment]
https://github.com/projectatomic/libpod/pull/23 Should fix this issue.
