### ISSUE TITLE
OCID needs a yaml config file

### ISSUE THREAD

**Issue by rhatdan** [kubernetes-incubator/cri-o#113]
I don't want OCID to make the same mistake that docker did, although even docker finally has a config file.

All commands on the CLI should be specified in a config file.  The CLI options should override this.  One problem I foresee is the Option handling for OCID does not support default boolean settings.

I would figure the OCID would read in the config file first, and then setup the CLI Options with the values defaulted to the config file, but if the boolean options can not take a default, then we won't be able to tell the difference between whether the option was set in the config or overridden by the CLI Option.

**Comment by cyphar** [comment]
I completely agree. However, I think we should make it a TOML config file. My reasons:

1. YAML is an incredibly complicated specification, and contains lots of features (ahem turing completeness) that are not helpful to anyone who just wants to set up cri-o.
2. YAML is not good for describing the configuration of a tool, as it doesn't semantically make sections of options easy to convey. TOML is essentially what git uses, and that works fairly well IMO.

**Comment by runcom** [comment]
+1 on this, either yaml or toml works for me

**Comment by cyphar** [comment]
I'm working on toml at the moment, so consider this assigned to me.

**Comment by rhatdan** [comment]
My main concern is that it is easy for the Administrator to understand and edit.  So if TOML works for this situation, I am all for it.  I am still concerned about the boolean default values.

**Comment by cyphar** [comment]
We can set this up by having a "default config" structure and then we just modify it. i'm currently working on a PR so hang tight for that. :wink:

**Comment by runcom** [comment]
closed by #115 I guess
