### ISSUE TITLE
why not share pid namespace

### ISSUE THREAD

**Issue by weiwei04** [kubernetes-incubator/cri-o#1135]
From cri-o.io says
```
Pods are a kubernetes concept consisting of one or more containers sharing the same IPC, NET and PID namespaces and living in the same cgroup.
```

but in the code, seems don't share pid namespace for now, is there some special reason?
https://github.com/kubernetes-incubator/cri-o/blob/master/server/container_create.go#L916

**Comment by rhatdan** [comment]
We probably should change the description.  Kubernetes currently does not share the PID Namespaces,  Well I guess it is optional.

**Comment by rhatdan** [comment]
We probably should change the description.  Kubernetes currently does not share the PID Namespaces,  Well I guess it is optional.

**Comment by weiwei04** [comment]
Kubernetes now support pid namespace from 1.7 :) (ref: https://github.com/kubernetes/kubernetes/pull/51634), and we have enabled this feature in our 1.8 environment with docker 1.13 so far so good :), wondering why cri-o don't support pid namespace, we are also investigating to use cri-o(since it have some features we need, like pid-max, ignore image volume and more light weight than docker for kubernetes)

If there's no other reason than old kubernetes didn't support share pid namespaces, I'd like to open a pr  working on it.

**Comment by weiwei04** [comment]
Kubernetes now support pid namespace from 1.7 :) (ref: https://github.com/kubernetes/kubernetes/pull/51634), and we have enabled this feature in our 1.8 environment with docker 1.13 so far so good :), wondering why cri-o don't support pid namespace, we are also investigating to use cri-o(since it have some features we need, like pid-max, ignore image volume and more light weight than docker for kubernetes)

If there's no other reason than old kubernetes didn't support share pid namespaces, I'd like to open a pr working on it.

**Comment by rhatdan** [comment]
We will certainly add it, I believe they were duplicating the Docker-1.12 behaviour that kubernetes currently uses.  @runcom how hard would this be to fix?

**Comment by rhatdan** [comment]
Yes open a PR.
I have been pushing back on upstream kubernetes about making this a requirements. since I think having multiple containers in the same POD with different Security is an interesting use case.  Think about a container with an init container that loads a kernel module and then the primary container can be locked down and just use the module.

systemd in a container also does not work well with the PID namespace shared with the Pause container.  Although I think CRI-O can get rid of the need for the Pause container, which would be awesome.

**Comment by rhatdan** [comment]
@weiwei04 if you do make a patch to share the PID namespace can you add it as an option to the daemon to allow people to optionally run it shared.
