### ISSUE TITLE
CNI 0.6.0 Support

### ISSUE THREAD

**Issue by danehans** [kubernetes-incubator/cri-o#1137]
CNI will be bumped to 0.6.0 in k8s 1.9, see: https://github.com/kubernetes/kubernetes/issues/49480.
While reviewing the CNI bridge configuration [example](https://github.com/kubernetes-incubator/cri-o/blob/master/contrib/cni/10-crio-bridge.conf), it appears CRI-O may need to be updated to support CNI 0.6.0.

**Comment by rhatdan** [comment]
Thanks for the headsup

**Comment by runcom** [comment]
As soon as we cut CRI-O 1.8.x we'll move master to CNI 0.6.0, thanks!

**Comment by danehans** [comment]
That's great to hear. Thanks.

**Comment by runcom** [comment]
This has been fixed by https://github.com/cri-o/ocicni/pull/1

@danehans could you check it out?
