### ISSUE TITLE
Debug API

### ISSUE THREAD

**Issue by runcom** [kubernetes-incubator/cri-o#1144]
Kube 1.9 added support for a Debug API which is basically a knob coming from the CI that tells the runtime to output additional and optional informations about some requests. We're mainly interested in the Status CRI API where we could return `docker info`-like about CRI-O. You can find the definition here and work from there in CRI-O: https://github.com/kubernetes/kubernetes/blob/c6ddc749e85f4281628f366d65cf924c22d6cd99/pkg/kubelet/apis/cri/v1alpha1/runtime/api.proto#L335 and https://github.com/kubernetes/kubernetes/blob/c6ddc749e85f4281628f366d65cf924c22d6cd99/pkg/kubelet/apis/cri/v1alpha1/runtime/api.proto#L391

**Comment by runcom** [comment]
we can also fix https://github.com/kubernetes/kubernetes/issues/55414 when this is done (note to self)

**Comment by willstudy** [comment]
It's a good idea.

**Comment by runcom** [comment]
removing 1.9 as it's not mandatory to expose anything until we actually need something
