### ISSUE TITLE
Replace crioctl with crictl

### ISSUE THREAD

**Issue by weiwei04** [kubernetes-incubator/cri-o#1158]
This is a umbrella issue to track the crioctl -> crictl progress

Some todos:

- [ ] replace crioctl with crictl in e2e tests #1156  #1159

- [ ] remove crioctl code

**Comment by mdshuai** [comment]
same https://github.com/kubernetes-incubator/cri-o/issues/504

**Comment by weiwei04** [comment]
Thanks for remind :)

**Comment by TomSweeneyRedHat** [comment]
@weiwei04 I've moved the todo list to #504, please track there.  @mdshuai thx for the reminder.  @rhatdan I can't close this issue, can you please?
