### ISSUE TITLE
confusion over the ocid name?

### ISSUE THREAD

**Issue by sarahnovotny** [kubernetes-incubator/cri-o#12]
After reading the updated repo description, I believe i understand the intent of this work but, am concerned that naming it only ocid will be both confusing and a possible infringement on the OCI trademarks.  I see the following options:
- find some examples of cases where this sort of naming based on a standard is common even when the standard offers formal certification (which is in the works now with the OCI).
- go out to the OCI Trademark Board for clarification on their AUP for the name. -  i.e. can we name this repo/tooling ocid but not claim "OCI Certified" or "OCI Compliant" without going through their (still nacent) certification process?
- rename 

Thoughts, dear maintainers?  (@mrunalp @runcom @yujuhong @cyphar @mikebrow )

**Comment by vbatts** [comment]
I couldn't find a link to the opencontainers trademark. Though it doesn't
seem terribly confusing to me.

**Comment by mrunalp** [comment]
@sarahnovotny I will reach out to the OCI Trademark Board to see what they think. We aren't claiming that this project is OCI compliant but rather that it makes use of OCI compliant runtimes. I do see your concern and can modify to take out "compliant" from the README till runc is formally verified as compliant, though. Thanks!

**Comment by sarahnovotny** [comment]
thanks, @mrunalp and @vbatts.

**Comment by vbatts** [comment]
🐿️🐧

**Comment by mrunalp** [comment]
Okay, this will be discussed in the next OCI TB meeting later this week. I will update the feedback that I get from the OCI TB here. Thanks!

**Comment by estesp** [comment]
I know you guys don't control what The New Stack writes, but surprising, but maybe not based on the name, there is now a story claiming this is a project and intention of the OCI itself: http://thenewstack.io/oci-building-way-kubernetes-run-containers-without-docker/

**Comment by thockin** [comment]
Yeah, I agree the name is somewhat misleading.  So is "CRI".  Neither CRI nor OCID (seemingly) aim to be universal things.  CRI is kubelet's internal API for abstracting runtimes out.  OCID is an implementation of CRI.  I know the docs say this but it is maybe not clear enough?

**Comment by yujuhong** [comment]
@philips mentioned a few names for the rkt implementation of CRI. One popular option is rk8s (and dk8s for docker). If we follow the same convention, maybe ocid can be renamed as ok8s? 

Not sure if a better name would've actually prevented stories stories like http://thenewstack.io/oci-building-way-kubernetes-run-containers-without-docker/

**Comment by mrunalp** [comment]
The intention wasn't to mislead but to have a simple boring name hence `ocid` seemed apt. We can rename it to something different. 

cc: @rhatdan @smarterclayton

**Comment by thockin** [comment]
No malice was assumed :)

**Comment by rhatdan** [comment]
nfsd :^)

**Comment by caniszczyk** [comment]
@mrunalp I'll followup with you from an OCI perspective on this issue next week after deliberation but we don't have formal trademark guidelines in OCI outside of what is provided by the LF default (https://www.linuxfoundation.org/trademark-usage). 

We are also in the process of developing an OCI certification program which will add some clarity in terms of how we expect the wider community to use OCI related marks. I would definitely not refer to anything being OCI certified or compliant in the time being.

**Comment by mikebrow** [comment]
Good points.. all.  A rename is probably a good idea for the reasons Sarah pointed out.  Just a point of reference Docker used the name containerd for a similar project that they needed to build to "layer" in runc. 

In the ocid case the daemon is supporting commands to meet Kube's interface for managing **k**ube **p**ods, **c**ontainers and **i**mages. 

Possible names:
containerk
runp
runkube

**Comment by mrunalp** [comment]
@caniszczyk Thanks for the update. Meanwhile I have merged in #14 that removes the word `compliant` from the README.

**Comment by mrunalp** [comment]
Thanks for the suggestions @mikebrow

**Comment by thockin** [comment]
if this is just a CRI implementation, can we just go with boring names like
"oci-cri"

**Comment by rhatdan** [comment]
A few more instances of daemons named after the protocol standard - httpd, sshd, kerberosd,

**Comment by thockin** [comment]
naming the program is different than the project.  https => apache, sshd => openssh.  I don't know much about Kerberos.

Naming is hard, let's not be clever.

**Comment by rhatdan** [comment]
Actually I wanted to call it OCD.  But that has other connotations.

**Comment by mikebrow** [comment]
I sort of like kcrid easy to type not memorable to the point :-) Also like containerk or containerkd as a nod to the docker guys to explain the relationship of this interface within kubernetes. To @thockin's idea to call it oci-cri oci is what we're look at trying to avoid in the name.  Maybe runc-crid, bit long to type though.

**Comment by runcom** [comment]
just `crid`?

**Comment by mikebrow** [comment]
I google crid and the result made me want to leave it out of my list

**Comment by sarahnovotny** [comment]
I like:

kuber
containerk

I'm happy to change the name of the repo as soon as we have consensus.

@thockin and @mikebrow, i'd love for us to avoid the use of OCI *or* runc without clear trademark fair use guidelines (which based on the conversations this morning on the OCI Trademark Board call could be O(weeks) out).

**Comment by vbatts** [comment]
If it isn't against fair use, then is this issue because this project is in
the kubernetes-incubator ?
I realize there is confusion, but it seems like it can be clarified
adequately in the docs. It is a daemon that uses OCI components. That is
pretty clear.

**Comment by sarahnovotny** [comment]
no... the issue is that OCI TMB and OCI Certification Working Group aren't far enough along to make a clear decision if this falls in or out of fair use.  As a member of of both groups (TMB and Cert WG), we appreciate your patience (and hard work) as we get closer the 1.0 of all the specs and finalize a certification program and the resultant TM fair use guidelines.

**Comment by vbatts** [comment]
Right on

**Comment by ncoghlan** [comment]
(Chiming in from the perspective of someone that had coincidentally recently asked for more clarity around acceptable uses of the OCI's marks)

@sarahnovotny's suggestion of `containerk` is interesting, as it seems like that could readily become a default convention for Kubernetes CRI backend daemons (`rktk`, `nspawnk`, etc). When I first heard the `ocid` name I wondered why it was being published as a kubernetes-incubator project, and it was only in reading this thread that I properly understood that it wasn't intended to be a standalone daemon, but specifically a Kubernetes container management plugin based on the OCI interoperability standards.

So regardless of the OCI's official perspective, there may be value in adjusting the name to more clearly convey the Kubernetes connection vs being a utility for working with the OCI formats independently of any particular orchestrator.

**Comment by thockin** [comment]
the-project-soon-to-be-formerly-known-as-ocid is not a generic CRI daemon -
it is a SPECIFIC implementation of CRI for OCI runtimes.

**Comment by thockin** [comment]
I sort of reject the notion that OCI people will forbid something like
"cri-oci" or similar.  I'd rather wait for that to settle (or do it now
rename it again later) than choose a dumb name now.

cri-oci sets precendent for cri-rkt, cri-hyper, cri-docker, cri-lmctfy, etc.

**Comment by chriswright** [comment]
@thockin I don't like that notion either, working with OCI folks to DTRT

**Comment by sarahnovotny** [comment]
@chriswright and @thockin per an afternoon conversation with a subset of the OCI Trademark Board, their preference would be for us to follow the umbrella [Linux Foundation Trademark Guidelines](https://www.linuxfoundation.org/trademark-usage) until the full group meets and decides OCI Certification plan and Trademark usage guidelines.  Both of which are longer term goals.

There were no objections to cri-o or ocri as names for this incubated project.

**Comment by thockin** [comment]
I'm going to rename the repo to `cri-o` and you all can clean up the mess.

**Comment by thockin** [comment]
DONE

**Comment by mrunalp** [comment]
@thockin Thanks!
@vishh Looks like we need to re-enable travis. Could you do that?

**Comment by mikebrow** [comment]
Cool name (pun intended :-)

**Comment by sarahnovotny** [comment]
punny

**Comment by rhatdan** [comment]
Should this issue be closed.  Although not real happy with cri-o for a name.

**Comment by thockin** [comment]
you are welcome to find a new name at your own pace, now that the firedrill is over. :)
