### ISSUE TITLE
conmon should search PATH for the --runtime

### ISSUE THREAD

**Issue by anarcat** [kubernetes-incubator/cri-o#1215]
**Description**

`conmon` has pretty bad failure modes when it can't find the runtime (`runc`). I have documented this https://github.com/projectatomic/libpod/issues/119 and it is partly an issue with how `kpod` hardcodes the path to the runtime (to `/usr/bin/runc`), but I think it could be argued there is a problem in conmon itself as well.

If conmon can't find the runtime, it doesn't actually fail: exit status is zero. That should probably be fixed. But worse, it can't find the runtime *unless* it is given as an absolute path. Is there an specific reason for this?

Forcing admins to provide an absolute path make it needlessly difficult to change the runtime through regular package updates or typical `/usr/local` overrides sysadmins are accustomed to. It breaks [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) as well.

Now, kpod could fix this on its own and search `runc` in the path, but that's a little weird - it seems to me that's conmon's job and that `kpod` should just pass down `runc` (or whatever is provided as a `--runtime` config flag) down into conmon, which should do the right thing.

**Steps to reproduce the issue:**
1. install buildah (and runc, from buildah's Makefiles) on Debian stretch
2. build a container (`buildah bud whatever`)
3. start the container with `kpod --runtime=runc run projectatomic/atomicapp  true`

**Describe the results you received:**

```
ERRO[0000] Error removing container 4dd00aed2a714682abba1967cc4225878671ebc881f24726ae3bca55c5beacca from runc after creation failed 
error reading container (probably exited) json message: EOF
```

In syslog, conmon says:

```
déc 11 14:04:58 curie conmon[21323]: conmon <ninfo>: addr{sun_family=AF_UNIX, sun_path=/tmp/conmon-term.3VLNAZ} 
déc 11 14:04:58 curie conmon[21323]: conmon <ninfo>: about to waitpid: 21324 
déc 11 14:04:58 curie conmon[21323]: conmon <error>: Failed to create container: exit status 127 
```

Conmon also returns with exit code 0 when ran manually.

**Describe the results you expected:**

Conmon should have found runc in the $PATH (`/usr/local/bin/runc` in this case).

**Additional information you deem important (e.g. issue happens only occasionally):**

This also happens when `--runtime` is not provided and `runc` is not `/usr/bin/runc`, obviously (which was my original case).

**Output of `crio --version`:**

crio is technically not installed here - i believe that libpod just rips it out of crio...

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Debian 9.3 (stretch, amd64) built with golang 1.8.1

**Comment by rhatdan** [comment]
I actually would prefer that the kpod command figure this out rather then hard coding it in the C conmon.  I agree that conmon should be throwing an error when it can not find runc, along with a message on that.
kpod should force the user to specify a runc path that exists before handling it to conmon. If the user specifies a path.

**Comment by anarcat** [comment]
note that this would remove the need for hacks like this as well:

https://github.com/kubernetes-incubator/cri-o/blob/fd78dea270b37247b66eedbb08065a7f53197398/contrib/test/integration/build/runc.yml#L19

**Comment by anarcat** [comment]
i think it's fine to do a `stat` on the path provided by the user, but i still think that conmon should look into `$PATH`. i'm not proposing to hardcode anything here - just common sense...

**Comment by rhatdan** [comment]
@anarcat is this still an issue?  @baude @mheon Have we improved this situation at all?

**Comment by mheon** [comment]
We do not support searching $PATH for runc or conmon, but we do ship a configuration file now to specify their locations, and will produce good error messages when either one is not found.

**Comment by rhatdan** [comment]
Crio also has a config file for this data.  Closing this issue.

**Comment by cyphar** [comment]
Also `$PATH` would not be entirely safe in my opinion. You want to have to specify a path rather than just a name.
