### ISSUE TITLE
conmon should support a configurable logging level

### ISSUE THREAD

**Issue by ijl** [kubernetes-incubator/cri-o#1219]
conmon should support configurable logging levels to support running in production.

I see #483, but performance aside, syslog can be flooded in normal usage by unimportant conmon lines.

`write_k8s_log` in particular with `"Total bytes written` perhaps justifies a debug level, with default at info?

**Comment by mrunalp** [comment]
@ijl Sure, we can make it configurable.

**Comment by rhatdan** [comment]
Crio supports --log-level.
Closing.
