### ISSUE TITLE
Recovery from out of sync sandboxes is not possible without removing files manually

### ISSUE THREAD

**Issue by mikebrow** [kubernetes-incubator/cri-o#124]
#### Recovery from errors

Information about created pods is stored here `/var/lib/ocid/sandboxes`.
Currently, this information can get out of sync causing errors such as:

```
$ ocic pod list
FATA[0000] listing pod sandboxes failed: rpc error: code = 2 desc = error
getting container state for default-foo-0-infra: exit status 1: []
```

While we are working on resolving these issues you may need to remove sandboxes
manually:

```
$ cd /var/lib/ocid/sandboxes
$ ls
e00dea37fb97506c8de456fcd3b7d238e4176107ab84043e32319ee00ecb3e74
$ rm -drf e00dea37fb97506c8de456fcd3b7d238e4176107ab84043e32319ee00ecb3e74
```

Then restart your cri-o server. 

Example of reproduction scenario:
1) Create pod: ocic pod create --config test/testdata/sandbox_config.json
2) reboot 
3) ocic pod list fails with above error.

**Comment by runcom** [comment]
I don't think we need to take any action on this - kubelet will fully understand this case and re-start any container which the pod expect to have. (also ocid restart now fully re-sync with runc state). @mrunalp Wdyt?

**Comment by runcom** [comment]
this has greatly improved since #505 - closing but if stuff doesn't work, please open a new issue.
