### ISSUE TITLE
mountPropagation: Bidirectional

### ISSUE THREAD

**Issue by kfox1111** [kubernetes-incubator/cri-o#1247]
```
crio version 1.9.0
```

I enabled the feature gates for shared mount namespaces then set the following on a container's volume mount:
mountPropagation: Bidirectional

It works in docker but not in crio yet. openstack on top of k8s needs such features. It will be critical to adopting crio for some sites.

**Comment by mrunalp** [comment]
@kfox1111 Thanks for the report! We will look into it.

**Comment by mrunalp** [comment]
@kfox1111 Can you give us your exact steps to reproduce the issue?
cc: @rhvgoyal @runcom

**Comment by kfox1111** [comment]
ok. when I went and rebuilt step by step the instructions for how to do it to post here, it worked that time. Somewhere along the line I missed a step I think.

Sorry for the noise.

Thanks,
Kevin

**Comment by mrunalp** [comment]
@kfox1111 Awesome thanks :)
