### ISSUE TITLE
Container stats and imageFs stats can't be read by Heapster 1.5 on K8S 1.9

### ISSUE THREAD

**Issue by theatrus** [kubernetes-incubator/cri-o#1248]
**Description**

When running on a Kubernetes 1.9 cluster, with CRI-O 1.9.0 and Heapster 1.5.0 (as per the default addons), container and node stats cannot be pulled due to two not implemented methods

```
E0107 21:25:05.010468       1 manager.go:101] Error in scraping containers from kubelet_summary:172.31.85.104:10255: request failed - "500 Internal Server Error", response: "Internal Error: failed to list pod stats: failed to list all container stats: rpc error: code = Unknown desc = not implemented"
```

```
E0107 19:42:05.014803       1 summary.go:97] error while getting metrics summary from Kubelet ip-10-42-1-212.ec2.internal(10.42.1.212:10255): request failed - "500 Internal Server Error", response: "Internal Error: failed to get imageFs stats: rpc error: code = Unknown desc = not implemented"
```

I'm working on a PR to add container stats and have temporarily stubbed out the imageFs endpoint for the interim. 

**Steps to reproduce the issue:**
1. Install Kubernetes 1.9 with CRI-O 1.9
2. Run Heapster standalone version 1.5
3. Bad saddened by error messages in the Heapster log and lack of available node and container stats.

**Describe the results you received:**

Not implemented / lack of stats

**Describe the results you expected:**

Container and node stats as on Kubernetes 1.8/Heapster 1.4.

**Output of `crio --version`:**

```
crio version 1.9.0
commit: "814c6ab0913d827543696b366048056a31d9529c"
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS with cni-ipvlan-k8s-vpc

**Comment by wrigtim** [comment]
We've hit this too with Kubernetes 1.9.1 and CRI-O tag v1.9.1 😿 
Looks like the tests are only failing due to gofmt errors?

**Comment by rhatdan** [comment]
@theatrus Isn't this fixed now?

**Comment by theatrus** [comment]
Apologies - yes, this is fixed.
