### ISSUE TITLE
Comunications outside of github

### ISSUE THREAD

**Issue by rhatdan** [kubernetes-incubator/cri-o#125]
I have registered #ocid on freenode and would like to setup a mailing list for communications about OCID.  
I would like to setup a mailing list but not sure which site would be appropriate for this.

**Comment by mikebrow** [comment]
ocid or cri-o?

**Comment by mikebrow** [comment]
https://groups.google.com/forum/#!forum/kubernetes-sig-node is the place where the sig-node stuff usually gets discussed.

**Comment by rhatdan** [comment]
I really want to ignore cri-o name until we decide on a decent name for the project or OCI sets up guidance where OCID is ok.  CRI-O might be the worse possible name for this, and I don't want to change the name that everyone refers to as OCID twice.

**Comment by mikebrow** [comment]
Maybe a slack channel..

**Comment by rhatdan** [comment]
I am not a big fan of google based mailing list either.  I like the old fashioned ones.  If I can't use dwalsh@redhat.com to receive and send email, then I get locked into a walled garden.  

But I might just be an old fart yelling get off my lawn.

**Comment by mikebrow** [comment]
I'm an old fart as well and I like cri-o better than ocid, cause it's cooler and less ocd. 

Let's just do a cri slack channel.

**Comment by runcom** [comment]
Nooo no slack lol can't we just do IRC?

**Comment by mikebrow** [comment]
I presume irc #atomic is the go to for ocid/ocic discussions outside the cri use cases. 

Kubernetes discussions are up on slack and email groups on on google.

**Comment by rhatdan** [comment]
Well we are on #ocid now on freenode.  Atomic is more about the platform and the atomic CLI command.  I see #ocid being a place to talk about OCID/CRI-O as well as containers/image and containers/storage.

**Comment by runcom** [comment]
@rhatdan for containers/image and containers/storage we already have #container-projects (or something like this) on Freenode :/

**Comment by runcom** [comment]
But yeah, #ocid works for me

**Comment by cyphar** [comment]
I'm guessing this means that `#container-projects` is no longer a thing then?

**Comment by runcom** [comment]
@cyphar it is, but not for this project ofc, only for containers/* projects

**Comment by duglin** [comment]
while I'm not a fan of slack, if the rest of kube is there we really shouldn't be different.

**Comment by resouer** [comment]
Strongly suggest use kubernetes.slack.io :) We have a lot of users there now as well as sig-node, we can create a sig-crio. See: https://twitter.com/cloudposse/status/749018717040750592

And we can also integrate issue/bug/pr hooks in the group, it's awesome.

**Comment by rhatdan** [comment]
Ok, I think we can do both.  We currently have the OCID on freenode. but having an sig-ocid channel, would be fine.  I hesitate to use CRI-O since I hate the name.  Lets open a discussion on a new name if people are interested, but lets keep it OCID until we have the name.

**Comment by mrunalp** [comment]
Can we close this? I have #610 tracking request for slack channel.
