### ISSUE TITLE
grpc issue creating container

### ISSUE THREAD

**Issue by vbatts** [kubernetes-incubator/cri-o#1254]
**Description**
I'm venturing into new waters here, and surely doing bad things to cri-o. :grimacing: 

I'm working on a python library for the kubernetes CRI. 
Not sure that I've got the steps correct in creating a container in a pod, but RunPodSandbox appears to work, though the CreateContainer instruction gives cri-o a nil pointer. I'm sure it's my fault, but looking to get a full working example.

https://github.com/vbatts/python-kubernetes-cri/blob/c6153f9c6c4fe0f1233597f96695fa9bf845e74e/examples/one.py

example output: https://pastebin.com/me2KF8Zk
cri-o output from example: https://pastebin.com/5iJQX7e3

**Steps to reproduce the issue:**
1. `pip install kubernetes-cri`
2. `python ./examples/one.py`
3.

**Describe the results you received:**
panic the cri-o daemon and no container

**Describe the results you expected:**
creating a container in a pod

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**
[vbatts@chacha] {master} ~$ crio --version
crio version 1.9.0
[vbatts@chacha] {master} ~$ rpm -q cri-o
cri-o-1.9.0-4.git814c6ab.fc26.x86_64

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by vbatts** [comment]
looks like https://github.com/kubernetes/kubernetes/issues/53769 is related ...

**Comment by vbatts** [comment]
found the required field ...
The ContainerConfig metadata.name needs to be present, and match the sandbox_config.metadata.name for that matter.

Perhaps this ought not nil point and panic the crio daemon though?

**Comment by runcom** [comment]
> Perhaps this ought not nil point and panic the crio daemon though?

possible, lemme check

**Comment by runcom** [comment]
> found the required field ...
> The ContainerConfig metadata.name needs to be present, and match the sandbox_config.metadata.name for that matter.
> 
> Perhaps this ought not nil point and panic the crio daemon though?

https://github.com/kubernetes-incubator/cri-o/pull/1255
