### ISSUE TITLE
Cannot create pod after restart crio service

### ISSUE THREAD

**Issue by gouyang** [kubernetes-incubator/cri-o#1259]
**Description**
The command `crictl runp test/testdata/sandbox_config.json` cannot run successfully after restart crio service, but if restart the crio service twice, it returns to work again.

**Steps to reproduce the issue:**
Below steps are executed one after one immediately.

```
[root@localhost cri-o]# systemctl restart crio
[root@localhost cri-o]# crictl runp test/testdata/sandbox_config.json
806c14a58b59ee5c8ea28663386270d8ba43536fa8967f0602e8d30beaeecee6
[root@localhost cri-o]# systemctl restart crio
[root@localhost cri-o]# crictl runp test/testdata/sandbox_config.json
FATA[0003] run pod sandbox failed: rpc error: code = Unknown desc = conflict, name "k8s_podsandbox1_redhat.test.crio_redhat-test-crio_1" already reserved for pod "806c14a58b59ee5c8ea28663386270d8ba43536fa8967f0602e8d30beaeecee6" 
[root@localhost cri-o]# systemctl restart crio
[root@localhost cri-o]# crictl runp test/testdata/sandbox_config.json
ae2f950d7ee03d71a2b803adfe5d8ca80bfe014dd975e5074ef28def5d75f900
[root@localhost cri-o]# systemctl restart crio
[root@localhost cri-o]# crictl runp test/testdata/sandbox_config.json
FATA[0003] run pod sandbox failed: rpc error: code = Unknown desc = conflict, name "k8s_podsandbox1_redhat.test.crio_redhat-test-crio_1" already reserved for pod "ae2f950d7ee03d71a2b803adfe5d8ca80bfe014dd975e5074ef28def5d75f900"
```

**Describe the results you received:**
cannot create pod after restart crio service

**Describe the results you expected:**
it can create pod no matter how many times the crio service is restarted

**Output of `crio --version`:**

```
[root@localhost cri-o]# crio -v
crio version 1.9.0-dev
commit: "cb8033cd194bb98170d715b6f8ce873550d78706"
[root@localhost cri-o]# crictl -v
crictl version 1.0.0-alpha.0
```

**Comment by runcom** [comment]
> it can create pod no matter how many times the crio service is restarted

This assumption is wrong: kubernetes increments the Attempt field if it's going to recreate a pod with the same name/namespace stuff. If cri-o restarts and you want to run the same pod again you have to increment the Attempt or delete and recreate the same pod. The second restart is certainly wrong, we will look into that but the first is expected.

**Comment by wanghaoran1988** [comment]
> If cri-o restarts and you want to run the same pod again you have to increment the Attempt or delete and recreate the same pod. 
Does that mean if I didn't update Attempt and continue create the same pod, we should failed to create the pod?

Currently, without update the Attempt, the same pod can be created continually

**Comment by wanghaoran1988** [comment]
But after restart the crio , failed with "run pod sandbox failed: rpc error: code = Unknown desc = conflict, name "k8s_podsandbox1_redhat.test.crio_redhat-test-crio_1" already reserved for pod "f84c4518365d457e9cf3002dee2ff7c631cb22a1e0997e2713442cd1b4bb46b4" "

@runcom

**Comment by rhatdan** [comment]
@gouyang @runcom Do we still have this issue?

**Comment by gouyang** [comment]
Test on the master, not an issue any more.
