### ISSUE TITLE
Update to use the runtime command line interface from runtime-tools?

### ISSUE THREAD

**Issue by wking** [kubernetes-incubator/cri-o#1260]
Runtime-tools recently landed a [runtime command line interface spec][1].  I took a quick look to see how closely cri-o matches that spec, to see how easy it would be to slot in another runtime besides runc, and turned up a few issues (like [cri-o calling `kill --all`][2] although [`--all` is not defined in the interface spec][3]).  Is there interest in adjusting to more closely match the interface spec?  Or is there another recommended pathway for folks who want to use cri-o with a compliant runtime besides runc?

[1]: https://github.com/opencontainers/runtime-tools/blob/a0a410a4cfcee385b256e45f3d6f1ebb005c2dcc/docs/command-line-interface.md
[2]: https://github.com/kubernetes-incubator/cri-o/blob/v1.9.0/oci/oci.go#L627
[3]: https://github.com/opencontainers/runtime-tools/blob/a0a410a4cfcee385b256e45f3d6f1ebb005c2dcc/docs/command-line-interface.md#kill

**Comment by runcom** [comment]
can we work to have a --all in the spec maybe? was there anything to prevent --all to land in the spec?

/cc @mrunalp

**Comment by wking** [comment]
On Thu, Jan 18, 2018 at 08:27:53AM -0800, Antonio Murdaca wrote:
> … was there anything to prevent --all to land in the spec?

I haven't found any relevant discussion in
opencontainers/runtime-spec#513 or opencontainers/runtime-tools#321,
and I did not mention --all in opencontainers/runtime-tools@5c87cc6.
So no discussion on this specific issue.  My main concern would be
getting a definition for “all container processes”.  I started a
thread about that way back [1], but nobody else chimed in.

To avoid confusion, I'd rather approach StopContainer by sending TERM
(which, with KILL, are the only signals the command line interface
spec requires support for [2].  And that *is* discussed in
opencontainers/runtime-tools@5c87cc6) to the container process,
waiting the requested timeout, and then sending KILL to the container
processes.  If the container process was PID 1 in some PID namespace,
then other processes in that PID namespace will also be killed as part
of cleaning up that PID namespace.  That gives you clear “what
processes is this going to stop/kill” semantics without having to
involve ‘--all’ or define “container processes”.

Of course, how closely that matches runc's ‘--all’ will depend on how
runc defines “container processes” and on whether cri-o sets up new
PID namespaces for each container.  I'm not familiar enough with
either runc or cri-o to know that.

[1]: https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/n7vxlhn6Q7g
     Subject: Definining "container" and "container processes" on Linux
     Date: Thu, 08 Oct 2015 09:47:08 -0700
     Message-ID: <20151008164708.GM28418@odin.tremily.us>
[2]: https://github.com/opencontainers/runtime-tools/blob/a0a410a4cfcee385b256e45f3d6f1ebb005c2dcc/docs/command-line-interface.md#kill

**Comment by wking** [comment]
On Thu, Jan 18, 2018 at 05:32:25PM +0000, W. Trevor King wrote:
> That gives you clear “what processes is this going to stop/kill”
> semantics without having to involve ‘--all’ or define “container
> processes”.

It looks like there's some related cri-o discussion in #1010.  The way
I expect TERM to be handled is that the container init process should
be delegating any received TERM as it sees fit.  If it wants to pass
that along to the rest of its PID namespace with a kill(-1, TERM),
then the child processes will have time to gracefully close.  But I
think that delegation should be up to the container process, not
something that is handled by the runtime.

**Comment by wking** [comment]
We may want per-difference issues for this, but here are some more parts of the runtime interface used by CRI-O which are not covered in the runtime-interface spec:

* The [`exec`][1], [`update`][3], [`pause`][7], and [`resume`][8] commands.
* For `create`: the [`--no-pivot` argument][2].
* For `kill` (as discussed above): the [`--all` argument][5] and [signal names besides `KILL` and `TERM`][4].
* For `delete`: the [`--force` argument][6].

[1]: https://github.com/kubernetes-incubator/cri-o/blob/release-1.9/conmon/conmon.c#L1254
[2]:https://github.com/kubernetes-incubator/cri-o/blob/release-1.9/conmon/conmon.c#L1267
[3]: https://github.com/kubernetes-incubator/cri-o/blob/release-1.9/oci/oci.go#L544
[4]: https://github.com/kubernetes-incubator/cri-o/blob/release-1.9/oci/oci.go#L617
[5]: https://github.com/kubernetes-incubator/cri-o/blob/release-1.9/oci/oci.go#L627
[6]: https://github.com/kubernetes-incubator/cri-o/blob/release-1.9/oci/oci.go#L638
[7]: https://github.com/kubernetes-incubator/cri-o/blob/release-1.9/oci/oci.go#L747
[8]: https://github.com/kubernetes-incubator/cri-o/blob/release-1.9/oci/oci.go#L755

**Comment by mrunalp** [comment]
I think best would be to get these into runtime-interface specification. All alternatives to runc are copying the runc command line. While we work on getting those in, your best bet would be to add these options to the runtime you want to integrate right now.
