### ISSUE TITLE
crictl exec after kubectl exec

### ISSUE THREAD

**Issue by kfox1111** [kubernetes-incubator/cri-o#1266]
**Description**

crictl exec doesn't work after kubectl exec'ing into a pod.

**Describe the results you received:**
```
crictl exec -i -t -s 90cb980d2e80d hostname
FATA[0000] execing command in container synchronously failed: 
                  rpc error: code = Unknown desc = command error: exec failed: 
                  cannot allocate tty if runc will detach without setting 
                  console socket
, stdout: , stderr: , exit code -1 
```

**Describe the results you expected:**

crictl exec should work.

**Output of `crio --version`:**

```
[kfox@zathras cri-o]$ crio --version
crio version 1.9.1-dev
commit: "5321ae20e4428093cdadb80f550e872f75006c32"
```

**Comment by rhatdan** [comment]
@mrunalp @runcom Have you guys looked into this?

**Comment by rhatdan** [comment]
@umohnani8 PTAL

**Comment by runcom** [comment]
This should be fixed already, @umohnani8 could you test it out?

**Comment by rhatdan** [comment]
Closing issue, reopen if it still exists.

**Comment by umohnani8** [comment]
Tested it out with latest cri-o and it works for me.

**Comment by rhatdan** [comment]
Excellent.
