### ISSUE TITLE
[release-1.9] Backport #1116

### ISSUE THREAD

**Issue by runcom** [kubernetes-incubator/cri-o#1315]
@nalind we need https://github.com/kubernetes-incubator/cri-o/pull/1116 back ported to `release-1.9`. You've already back ported something in https://github.com/kubernetes-incubator/cri-o/pull/1297 but we're missing the fixes to how we handle image digests and that's causing errors in openshift/origin CI (https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_crio/3987/consoleFull#-141723334256cbb9a5e4b02b88ae8c2f77). In that job we're seeing an issue with image digests which I believe it's already fixed on master with https://github.com/containers/image/commit/b937756b874fc4d20542a8230c14c7c94270b9d0.

How hard is this? Is it feasible?

**Comment by nalind** [comment]
It doesn't look like there are that many adjustments required.

**Comment by runcom** [comment]
fixed, thanks Nalin
