### ISSUE TITLE
CRIO Annotation Hooks

### ISSUE THREAD

**Issue by RenaudWasTaken** [kubernetes-incubator/cri-o#1319]
**Description**
In the hooks document it is stated that the Annotations fields is matched against the container annotations:
> List of regular expressions to match against the Annotations in the container runtime spec, if an Annotation matches the hook will be run

However, the current implementation matches the Annotation field against the [sandbox annotations](https://github.com/kubernetes-incubator/cri-o/blob/cb8033cd194bb98170d715b6f8ce873550d78706/server/container_create.go#L652)

Is the documented behavior incorrect or is the implementation correct?

For some context, we implemented a feature to add annotations to Containers from the Kubernetes Device Plugin.
For NVIDIA GPUs, we need to invoke our pre-start hook on containers requesting a GPU, the container behavior is preferred as some containers in a pod might not be requesting a GPU.

Thanks!

**Comment by runcom** [comment]
We can actually prefer containers annotation over sandboxes. Is that OK?

**Comment by RenaudWasTaken** [comment]
> We can actually prefer containers annotation over sandboxes. Is that OK?

Yep :)

**Comment by runcom** [comment]
And by that I mean,

1. Look for container annotation
2. If there's a container annotation, use it
3. It there is no, fall back to sandbox annotation

**Comment by RenaudWasTaken** [comment]
That's probably a good compromise, as it wouldn't break existing clients :)
In our case we don't intend to add annotations to the sandbox, so that behavior would be a good fit.

**Comment by runcom** [comment]
@RenaudWasTaken https://github.com/kubernetes-incubator/cri-o/pull/1320 PTAL
