### ISSUE TITLE
CRI-O built without Seccomp buildtag still produces Seccomp configs

### ISSUE THREAD

**Issue by mheon** [kubernetes-incubator/cri-o#1330]
**Description**

After building CRI-O without the Seccomp buildtag, containers will still have a default Seccomp profile. This is somewhat confusing as most people would expect no seccomp tag = no Seccomp profile. Only occurs when default seccomp profile is not set to unconfined.

I suspect this is due to not clearing the default Seccomp profile in specs created by the runtime-tools/generate package.

**Steps to reproduce the issue:**
1. Run privileged container in privileged pod
2. Attempt to start podman (or any application using runc) in pod
3. Runc will error as `keyctl` syscall is blocked by the default Seccomp profile.

**Describe the results you received:**
Runc will fail, saying that keyctl returned EPERM

**Describe the results you expected:**
Runc will probably still fail, given I don't believe we mount cgroups into the container? But it will not complain about keyctl throwing EPERM.

**Additional information you deem important (e.g. issue happens only occasionally):**

Tested on current git master (33e2f82d616169dcc10fe55f7b2d36ce9385909a)

**Comment by rhatdan** [comment]
Why not use the keyctl executable to test this?
```
man keyctl
KEYCTL(1)                                                                               Linux Key Management Utilities                                                                              KEYCTL(1)

NAME
       keyctl - key management facility control

SYNOPSIS
       keyctl --version
       keyctl show [-x] [<keyring>]
       keyctl add <type> <desc> <data> <keyring>
       keyctl padd <type> <desc> <keyring>
       keyctl request <type> <desc> [<dest_keyring>]
       keyctl request2 <type> <desc> <info> [<dest_keyring>]
       keyctl prequest2 <type> <desc> [<dest_keyring>]
       keyctl update <key> <data>
...
```

**Comment by mheon** [comment]
That would be a much better test, I think. I wonder if it's in any common images by default or you'd need a dnf install to grab it.

**Comment by mheon** [comment]
I will try and make a better reproducer this afternoon using keyctl if I have time

**Comment by rhatdan** [comment]
@mheon Is this still an issue?

**Comment by mheon** [comment]
@rhatdan Pretty sure it is, no changes to the seccomp code in awhile

**Comment by rhatdan** [comment]
@umohnani8 PTAL, I think this is solved in podman, could you take the code from there and make it work in CRI-O.

**Comment by rhatdan** [comment]
@mrunalp This could be a serious issue.

**Comment by umohnani8** [comment]
@rhatdan @mheon any idea where this is solved in podman? And how can I reproduce this with keyctl?

**Comment by rhatdan** [comment]
In cmd/podman/spec.go
```
	// HANDLE SECCOMP
	if config.SeccompProfilePath != "unconfined" {
		if config.SeccompProfilePath != "" {
			seccompProfile, err := ioutil.ReadFile(config.SeccompProfilePath)
			if err != nil {
				return nil, errors.Wrapf(err, "opening seccomp profile (%s) failed", config.SeccompProfilePath)
			}
			seccompConfig, err := seccomp.LoadProfile(string(seccompProfile), configSpec)
			if err != nil {
				return nil, errors.Wrapf(err, "loading seccomp profile (%s) failed", config.SeccompProfilePath)
			}
			configSpec.Linux.Seccomp = seccompConfig
		} else {
			seccompConfig, err := seccomp.GetDefaultProfile(configSpec)
			if err != nil {
				return nil, errors.Wrapf(err, "loading seccomp profile (%s) failed", config.SeccompProfilePath)
			}
			configSpec.Linux.Seccomp = seccompConfig
		}
	}

	// Clear default Seccomp profile from Generator for privileged containers
	if config.SeccompProfilePath == "unconfined" || config.Privileged {
		configSpec.Linux.Seccomp = nil
	}
```
		configSpec.Linux.Seccomp = nil 
is the key line.  You have to null out the Seccomp filter in the spec.

**Comment by umohnani8** [comment]
I can't reproduce this issue. Build cri-o without the seccomp buildtag, and left the crio.conf unmodified. Started a privileged pod and ran a privileged fedora container(with keyutils installed) inside it and this is the output of keyctl show:
```
[root@crictl_host /]# keyctl show
keyctl show
Session Keyring
 261350128 --alswrv      0     0  keyring: _ses.0ce7f7d6ad8e72dde2658a79409bf1c747334dbdbea2cf46a6a88446d6ad4e0d
```

However with the seccomp buildtag I am seeing the same thing for `keyctl show` for privileged pod and container.
Tried it for a non-privileged pod and container and still seeing the same output as above.
@mrunalp @runcom can you reproduce this? I am seeing quite a bizarre behaviour, unless I am doing something wrong while testing this.

**Comment by mheon** [comment]
I think we need a better syscall to test with. `keyctl` seems to be working even when the call itself should be blocked?

**Comment by runcom** [comment]
@mheon I can see we null out the seccomp struct in the spec in box sandbox/container creation. Could you actually, pls, provide clear steps to reproduce?

**Comment by runcom** [comment]
also, please confirm this is not working correctly in master

**Comment by mheon** [comment]
@runcom I originally found this when we were trying to get containerized podman working, but the procedure I used then doesn't seem to be working anymore. Looking at the code, I can't see a clear path for this to happen either.

I'm going to assume it was something else blocking the syscall; probably capabilities? I might have been running unprivileged by mistake.

I'll close this, given it doesn't seem to be reproducible.
