### ISSUE TITLE
Fsnotify on hooks path

### ISSUE THREAD

**Issue by RenaudWasTaken** [kubernetes-incubator/cri-o#1331]
**Description**
Currently hooks are loaded at startup, which means that when someone places a hook inside the hook directory, they need to restart CRI-O.

Adding a hook after CRI-O starts is something that will happen when paired with the Kubernetes device plugin feature.
The device plugin is a daemonset deployed by the cluster administrator at any time during the cluster lifecycle that is expected to:
- install drivers (e.g: NVIDIA drivers)
- Detect and report devices to the Kubelet (e.g: NVIDIA GPUs)
- Add additional runtime parameters to the CRI spec to advertise the device in the container

Currently the CRI spec doesn't support pre-start hook so we are going through annotations and CRI-O hooks.

As restarting CRI-O is a pretty disruptive behavior, it would be better if the hooks could be reloaded when a new one gets added to the hooks directories.

**Comment by runcom** [comment]
We can certainly look into this but I also want to understand more about the issues cri-o arises when it restarts, could you open more issues? :)

**Comment by RenaudWasTaken** [comment]
> We can certainly look into this but I also want to understand more about the issues cri-o arises when it restarts, could you open more issues? :)

No issues arises when restarting CRI-O, we're just not really comfortable asking our user to restart CRI-O manually or requesting the permissions for our container to do it programatically.
It's also a bit complicated to have a reliable way to restart programatically CRI-O

**Comment by runcom** [comment]
That makes total sense, I thought there were issues when restarting it, Nevermind then

**Comment by mrunalp** [comment]
Sounds good! @RenaudWasTaken any chance you could work on that?

**Comment by RenaudWasTaken** [comment]
I can test it but I can't work on it, I've started the process internally to contribute to CRI-O but it usually takes a few weeks :(
