### ISSUE TITLE
Tutorial doesn't mention crio.conf

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [kubernetes-incubator/cri-o#1379]
**Description**

In the tutorial you're told to do:
```
critctl pull redis:alpine
```
However that won't work until registries have been added to /etc/crio/crio.conf and there's no mention of that in the install guide or tutorial that I can see.

**Steps to reproduce the issue:**
1. Documentation error

**Describe the results you received:**
Unable to get crio running following just the steps in the tutorial.

**Describe the results you expected:**
crio up and running.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Can you open a PR to fix this?

**Comment by umohnani8** [comment]
@rhatdan this is done. Issue can be closed.

**Comment by TomSweeneyRedHat** [comment]
Ooops, yep, my bad I should have circled back and touched this up.
