### ISSUE TITLE
issue running cri-o on rawhide

### ISSUE THREAD

**Issue by runcom** [kubernetes-incubator/cri-o#139]
On a stock rawhide I got some issues before resolving them and run cri-o. One of the was: 

```
# container_linux.go:240: creating new parent process caused "container_linux.go:1245: running lstat on namespace path \"/proc/0/ns/ipc\" caused \"lstat /proc/0/ns/ipc: no such file or directory\""
# conmon: Failed to create container
```

I don't remember how this got fixed - @mrunalp @cyphar PTAL

**Comment by cyphar** [comment]
Looks like `pid=0` for some reason. What is the git commit of runC you had when this happened?

**Comment by runcom** [comment]
> Looks like pid=0 for some reason. What is the git commit of runC you had when this happened?

master

**Comment by mrunalp** [comment]
Looks like the state of the pause container returned pid as 0. The other container joins the ipc/net namespaces of the pause container.

**Comment by runcom** [comment]
This is SELinux

**Comment by runcom** [comment]
closing in favor of https://github.com/kubernetes-incubator/cri-o/issues/528 (which happens on Fedora as well)
