### ISSUE TITLE
ENH: Add warning in tutorial for multiple cpu's

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [kubernetes-incubator/cri-o#1397]
**Description**

When running the tutorial on a Fedora 27 server VM with only one cpu, the following error is encountered when creating the container:

```
CONTAINER_ID=$(crictl create $POD_ID test/testdata/container_redis.json test/testdata/sandbox_config.json)
FATA[0000] Creating container failed: rpc error: code = Unknown desc = container create failed: container_linux.go:348: starting container process caused "process_linux.go:279: applying cgroup configuration for process caused \"failed to write 0-1 to cpuset.cpus: write /sys/fs/cgroup/cpuset/Burstable/pod_123-456/crio-b0339ca445c25731e5eb5d8770bc50a9845fda6208fce45292b2796eb070df08/cpuset.cpus
```
A warning should be added to the tutorial noting that if you don't have a multi-cpu system, then you need to edit crio/test/testdata/container_redis.json
```
./container_redis.json:   "cpuset_cpus": "0-1",
needs to change to:
./container_redis.json:   "cpuset_cpus": "0",
```
and then the command will work.

**Steps to reproduce the issue:**
1. Follow the tutorial on a single cpu Fedora 27 server

**Describe the results you received:**
Error as noted in the description

**Describe the results you expected:**
A containerId in the variable.

**Additional information you deem important (e.g. issue happens only occasionally):**

Happens frequently.

**Output of `crio --version`:**

```
crio --version
crio version 1.10.0-dev
commit: "320a102c1c75a78165d109ea4c0fd2f0fdd6f502"
```

**Additional environment details (AWS, VirtualBox, physical, etc.):

n/a

**Comment by wking** [comment]
> A warning should be added to the tutorial noting that if you don't have a multi-cpu system…

I'd rather update `container_redis.json` to only require one CPU and have filed a patch to that effect in #1399.

**Comment by TomSweeneyRedHat** [comment]
Personally I though showing people how to adjust that in the tutorial would be helpful, but don't have a strong opinion.

**Comment by wking** [comment]
On Thu, Mar 01, 2018 at 09:53:29AM -0800, Tom Sweeney wrote:
> Personally I though showing people how to adjust that in the
> tutorial would be helpful, but don't have a strong opinion.

I'm fine with tutorial docs about adjusting the setting from 0 to 0-1.
That way the docs can talk about the adjustment, but you don't *need*
the adjustment to get the tests to pass.
