### ISSUE TITLE
Travis repeats steps (that are not version dependant) for different versions of Go

### ISSUE THREAD

**Issue by agonzalezro** [kubernetes-incubator/cri-o#1400]
**Description**

The current [Travis configuration](https://github.com/kubernetes-incubator/cri-o/blob/master/.travis.yml#L30-L57) will repeat the following `make` commands for different versions of Go when the version shouldn't be important:

- `make .gitvalidation`
- `make gofmt`
- `make lint`

And not sure about `make docs`.

I know that "better safe than sorry" :) but this makes the checks on the PRs slower and if they aren't needed maybe they could be removed.

The tests run in parallel so the improvements will be minimal, however, the feedback loop would be shorter because while one the versions will be running these validations the other will be already running the tests.

**Describe the results you received:**

- Longer waiting times for a PR's checks to become green.

**Describe the results you expected:**

- A little improvement in these speeds. 

If you think the time spent during these test is irrelevant or that they are really version dependent and I missed something, please, feel free to close the issue.

**Comment by rhatdan** [comment]
COuld you open a PR to fix this?

**Comment by agonzalezro** [comment]
Sure, I just wanted to be sure that you like the approach I am proposing. I will do it soon, assign it to me if you want.

**Comment by agonzalezro** [comment]
I already opened the PR @rhatdan: https://github.com/kubernetes-incubator/cri-o/pull/1412

**Comment by rhatdan** [comment]
Awesome thanks.
