### ISSUE TITLE
don't manage service files with `make {,un}install`

### ISSUE THREAD

**Issue by cyphar** [kubernetes-incubator/cri-o#142]
Personally I don't like makefiles that modify a bunch of system state if not necessary. In addition, it actually makes it not possible for us to use the stock `Makefile` on openSUSE -- in openSUSE we package service files in a very fun and wonderful way.

And **especially bad** is that `make uninstall` actually stops and disables services. While it's not a good idea to have a running service while removing files, this could cause other issues. In general IMO we should completely split out service handling so it's not in the makefile at all (or if it is, it's somewhere optional).

**Comment by rhatdan** [comment]
Removed that from uninstall

**Comment by runcom** [comment]
should be fixed in master
