### ISSUE TITLE
Cannot start sandbox pod

### ISSUE THREAD

**Issue by 14rcole** [kubernetes-incubator/cri-o#147]
Attempting to create a pod with the following command
`sudo ./ocic pod create --config test/testdata/sandbox_config.json`
As is (almost) identical to the command in the README produces the following error on the client side:
`Creating the pod sandbox failed: rpc error: code = 2 desc = reading pid from init pipe: EOF`
I believe the error originates when the Kubernetes api is called at `cmd/client/sandbox.go:190` but I wasn't able to trace it past there.

**Comment by mrunalp** [comment]
@14rcole I think that adding syslog support to conmon will help diagnose this issue. conmon is probably exiting without sending pid back to ocid.

**Comment by mrunalp** [comment]
@14rcole Meanwhile to cleanup: runc delete -f all running containers, rm -rf /var/lib/ocid and then restart ocid server.

**Comment by 14rcole** [comment]
@mrunalp I tried cleaning up , I'm getting the same error.  I think it does have to do with conmon.  On the daemon side I'm getting the messages

`conmon: Failed to create container
INFO[0007] Signal received: child exited                
INFO[0007] Reaped process with pid 30839`

That "failed to start container" message comes from `conmon.c` line 164. It looks like `system(cmd)` is returning the error code 768

**Comment by mrunalp** [comment]
@14rcole What version of runc are you using? It should be > 1.0.0.rc1.

**Comment by 14rcole** [comment]
I was using the one in the dnf repositories, which was 0.1.1.  After building the latest release on github, it works fine.  Thank you!

**Comment by rhatdan** [comment]
Please close this issue.

**Comment by mrunalp** [comment]
@14rcole Thanks for the update!
