### ISSUE TITLE
flake: “The binary conntrack is not installed”

### ISSUE THREAD

**Issue by wking** [kubernetes-incubator/cri-o#1473]
We've been seeing these recently, e.g. on master [here][1]:

```
not ok 14 ctr logging [tty=true]
# (in test file ./ctr.bats, line 243)
#   `grep --binary -P "^[^\n]+ stdout F here is some output\x0d$" "$logpath"' failed
# 0
# time="2018-03-28 19:38:04.684473393Z" level=debug msg="[graphdriver] trying provided driver "vfs"" 
# time="2018-03-28 19:38:04.685394247Z" level=debug msg="hooks map[]" 
# time="2018-03-28 19:38:04.685692417Z" level=info msg="CNI network crionet (type=bridge) is used from /tmp/tmp.3UWlCu2HlW/cni/net.d/10-crio.conf" 
# time="2018-03-28 19:38:04.685893555Z" level=info msg="CNI network crionet (type=bridge) is used from /tmp/tmp.3UWlCu2HlW/cni/net.d/10-crio.conf" 
# ERROR: logging before flag.Parse: W0328 19:38:04.690172   15243 hostport_manager.go:68] The binary conntrack is not installed, this can cause failures in network connection cleanup.
# …
# time="2018-03-28 19:38:06.727454775Z" level=error msg="Failed to start streaming server: http: Server closed" 
# …
# 0
```

Previous instances of that flake [here][2] (still in flight) and [here][3] (recently landed).

The error text itself landed in e5fdb6bc9e (#1392), where [the test passed][4], but I haven't dug into that code to figure out what it's doing.

[1]: https://travis-ci.org/kubernetes-incubator/cri-o/jobs/359476396#L3264
[2]: https://github.com/kubernetes-incubator/cri-o/pull/1434#issuecomment-371607488
[3]: https://github.com/kubernetes-incubator/cri-o/pull/1472#issuecomment-376895263
[4]: https://travis-ci.org/kubernetes-incubator/cri-o/jobs/348319383#L3692

**Comment by wking** [comment]
Or maybe the “conntrack” message is a red herring, and the server is going down for a different reason?

**Comment by jamiehannaford** [comment]
@wking I'm also seeing this. It generally occurs when crio is unresponsive (we're using Kata containers). Did you narrow this down?

**Comment by wking** [comment]
> Did you narrow this down?

I don't think anyone has had time to dig into this.  I don't expect to have time in the near future, so anyone with time should feel free to dive in ;).  And anyone who does should post any findings back here.

**Comment by wking** [comment]
From above:

>     not ok 14 ctr logging [tty=true]

And:

> I'm also seeing this. It generally occurs when crio is unresponsive (we're using Kata containers).

My current guess is that the log tests are calling `stop` (and have been since they landed in 65527da36, #162), but that what we really should be doing is waiting for the containers to exit cleanly.  More on this with a fix in flight in #1656.

**Comment by wking** [comment]
Last instance of this was [4 days ago][1].  I haven't noticed any since #1656 landed.

[1]: https://travis-ci.org/kubernetes-incubator/cri-o/jobs/396928597#L4067

**Comment by rhatdan** [comment]
Ok I will close
