### ISSUE TITLE
StopContainer is racy

### ISSUE THREAD

**Issue by phemmer** [kubernetes-incubator/cri-o#1477]
StopContainer is racy in that if the process exits in between when the check happens and when the signal is sent, the function will error out.

https://github.com/kubernetes-incubator/cri-o/blob/1a25658eba1f34527209e379a14bd83531dcef3f/oci/oci.go#L675-L692

I ran into this issue with OpenShift 3.9, resulting in:
```
error killing pod: failed to "KillPodSandbox" for "d929a4a0-3424-11e8-be3b-005056823990" with KillPodSandboxError: "rpc error: code = Unknown desc = failed to stop infra container k8s_POD_router-1-deploy_default_d929a4a0-3424-11e8-be3b-005056823990_0 in pod sandbox f0ea226c83fa61d7bf7dbe06cb62e532b12e966380b417894a19edbf682f5694: failed to stop container f0ea226c83fa61d7bf7dbe06cb62e532b12e966380b417894a19edbf682f5694, `/usr/bin/runc kill f0ea226c83fa61d7bf7dbe06cb62e532b12e966380b417894a19edbf682f5694 TERM` failed: exit status 1"
```
With the cri-o logs showing:
```
Mar 30 10:26:39 fll2aosi01dev crio[6207]: container_linux.go:393: signaling init process caused "os: process already finished"
```

**Steps to reproduce the issue:**
1. Have a container exit
2. Try to stop the pod at the same time it exits
3. Retry over and over until you hit the race condition

**Describe the results you received:**
```
failed to stop container f0ea226c83fa61d7bf7dbe06cb62e532b12e966380b417894a19edbf682f5694, `/usr/bin/runc kill f0ea226c83fa61d7bf7dbe06cb62e532b12e966380b417894a19edbf682f5694 TERM` failed: exit status 1
```

**Describe the results you expected:**
success

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
crio version 1.9.10
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```
openshift v3.9.0-alpha.4+881f1dd-440
kubernetes v1.9.1+a0ce1bc657
etcd 3.2.8
```

**Comment by runcom** [comment]
I'll add sync around this

**Comment by runcom** [comment]
Actually, I think it's just worth checking if the process is still around before sending the signal

**Comment by phemmer** [comment]
> Actually, I think it's just worth checking if the process is still around before sending the signal

That's what the code is already doing. The problem is that between the check, and sending the signal, the process disappears.

I think the only way to solve this is going to be to re-check after sending the signal to see if it's still there, and if it's not, pretend that there was no error and return success.

**Comment by runcom** [comment]
@phemmer https://github.com/kubernetes-incubator/cri-o/pull/1478

**Comment by runcom** [comment]
@phemmer, PR has been merged into master, I'll backport it, is there any way you can test it out?

**Comment by phemmer** [comment]
not easily. I was doing something that was causing kubernetes routers to die, and were occasionally falling into this situation, but I don't remember what that was at this point. I can deploy it and see if the issue comes back, but that's about it.

**Comment by wking** [comment]
One way to test would be to launch ‘crio’ with ‘--runtime=runc.sh’
where runc.sh is something like:

  #!/bin/sh
  if test kill = "$1"
  then
    sleep 120
  fi
  exec runc "${@}"

Then run a container with ‘sleep 60’ or some such as the worker
process, tell Kubernetes to stop it, and check the logs to see the
messages added in #1478.
