### ISSUE TITLE
Conmon can only handle one attach session at a time

### ISSUE THREAD

**Issue by mheon** [kubernetes-incubator/cri-o#1481]
**Description**

Spawned from https://github.com/projectatomic/libpod/issues/580

Right now, `conmon` can only handle a single attach session at a time. If a new attach request comes in over the attach socket, the current session is overwritten and stops receiving output.

There is, as best I can tell, no fundamental reason for this - `conmon` simply doesn't have logic for handling multiple open attach FDs. This would probably complicate the callback logic for cleaning up closed connections, but otherwise it does not look too difficult.

Easiest reproducer is probably `podman` instead of `CRI-O` (the `podman run`/`podman attach` combo in the linked issue), though I imagine you can use `crictl attach` in two terminals to get two attach sessions against the same container.

**Comment by rhatdan** [comment]
@giuseppe Can you look into this?

**Comment by giuseppe** [comment]
PR here:

https://github.com/kubernetes-incubator/cri-o/pull/1483

**Comment by rhatdan** [comment]
@giuseppe Thanks.
