### ISSUE TITLE
RunPodSandbox should return same RunPodSandboxResponse when post same RunPodSandboxRequest

### ISSUE THREAD

**Issue by wanghaoran1988** [kubernetes-incubator/cri-o#1514]
**Description**

**Steps to reproduce the issue:**
1. sudo crictl -D --runtime-endpoint /var/run/crio/crio.sock runp test/testdata/sandbox_config.json
2. sudo crictl -D --runtime-endpoint /var/run/crio/crio.sock runp test/testdata/sandbox_config.json
3.

**Describe the results you received:**

the 2 step return a different sandbox id
**Describe the results you expected:**
should return same id

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
crio version 1.9.0-dev
commit: "80ee4f3f6d66468f0710f4453b4e33d714016454"
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mrunalp** [comment]
The id is a uuid that is generated when that command is run and is expected to be different each time.

**Comment by wanghaoran1988** [comment]
@mrunalp why not return the id that already created? instead of stop the one created first time and create a new one?
