### ISSUE TITLE
error updating status for container, when process was restarted

### ISSUE THREAD

**Issue by surajssd** [kubernetes-incubator/cri-o#152]
Earlier I stopped `ocid` process without stopping all containers or pods and restarted the process again

``` bash
$ ocid --runtime $(which runc)
INFO[0000] Starting reaper                              
E1017 05:59:13.930932   15542 ocicni.go:136] error updating cni config: No networks found in /etc/cni/net.d
WARN[0000] error updating status for container c4b2a99b80de8757a3a131921084af0ea2c4c83835a6e2093f39050864f75d21: error getting container state for default-podsandbox1-0-infra: exit status 1: [] 
INFO[0000] Signal received: child exited                
INFO[0003] Signal received: child exited       
[SNIP]
```

and now when I try to get pods or containers info it fatals out as

``` bash
$ sudo ocic container list
FATA[0000] listing containers failed: rpc error: code = 2 desc = error getting container state for default-podsandbox1-0-infra: exit status 1: [] 

$ sudo ocic pod list                                                                                                                                                                             
FATA[0000] listing pod sandboxes failed: rpc error: code = 2 desc = error getting container state for default-podsandbox1-0-infra: exit status 1: [] 
```

removing that container also fails

``` bash
$ sudo ocic container remove --id c4b2a99b80de8757a3a131921084af0ea2c4c83835a6e2093f39050864f75d21
FATA[0000] Removing the container failed: rpc error: code = 2 desc = failed to update container state: error getting container state for default-podsandbox1-0-infra: exit status 1: [] 
```

versions:

``` bash
$ ocic -v
ocic version 0.0.1

$ runc -v
runc version 1.0.0-rc2
commit: 3abefdff18bc201199c5dfd0e91e941cb4c61376
spec: 1.0.0-rc2-dev

$ uname -a
Linux fedora 4.5.5-300.fc24.x86_64 #1 SMP Thu May 19 13:05:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mrunalp** [comment]
Thanks for the report. Did you just start one pod/ctr and then restarted ocid?

**Comment by surajssd** [comment]
Yes one pod with one redis based container from example! You can get more context at https://github.com/kubernetes-incubator/cri-o/issues/140#issuecomment-254124217
Is there a way to have a clean setup now?

**Comment by mrunalp** [comment]
You can runc delete -f all running containers and then rm /var/lib/ocid while we fix this bug.

**Comment by cyphar** [comment]
Yeah, I've seen this quite a bit when debugging conmon bugs while working on logging.

**Comment by surajssd** [comment]
```runc list``` didnt show anything but deleting `/var/lib/ocid` helped, resetting everything!

**Comment by cyphar** [comment]
> runc list didnt show anything but deleting /var/lib/ocid helped, resetting everything!

Yeah, the reason for this is because we have two "stores" of information about containers:

1. runC has a store of what containers are running in `/var/run/runc/...`.
2. OCID has a store of information about pods and sandboxes in `/var/lib/ocid/...`.

The problem arises when these two go out of sync. On the one hand, there's not much we can do if a user is deliberately killing containers underneath us. However, in adherence with the k8s design principles, we should be "self-healing". What I mean is that we should periodically (and on load) health-check containers to make sure that the state in `/var/lib/ocid` is accurate (and update it if it is inaccurate). WDYT @mrunalp?

**Comment by mrunalp** [comment]
@cyphar kubelet itself will be doing the periodic checks and respawn pods/containers as required. I am not sure at this point whether we need to do any more syncing besides fixing bugs on ocid restart. I am working on integrating ocid with the kubelet so will have better answers soon.

**Comment by cyphar** [comment]
Okay cool @mrunalp, keep us posted (and feel free to ask for any help). :smile_cat:

**Comment by mrunalp** [comment]
@cyphar More than welcome to join in on the fun :)
To test with kubelet, build kubernetes, start ocid, CONTAINER_RUNTIME="ocid" CONTAINER_RUNTIME_ENDPOINT=/var/run/ocid.sock ./hack/local-up-cluster.sh. After that you can call kubectl create -f /path/to/pod.json. Warning it doesn't work yet ;). I am going through that and making fixes for whatever we need to get a pod running.

**Comment by runcom** [comment]
#505
