### ISSUE TITLE
Add Kata Containers check to the CI workflow of this repository

### ISSUE THREAD

**Issue by chavafg** [kubernetes-incubator/cri-o#1530]
**Description**

The kata-containers project has created a job for testing every PR that is opened in this repository using the kata-containers runtime. 
The job can be consulted at: http://kata-jenkins-ci.westus2.cloudapp.azure.com/job/kata-containers-crio-PR/ 

Right now the job is polling the PRs using a cron job and now I would like to set a webhook for this job and also report back to this github repo. Can you could help me integrating it into your repository.

Thanks.

**Comment by runcom** [comment]
/cc @derekwaynecarr @stevekuznetsov 

@stevekuznetsov do you remember how we did to integrate with the openshift CI? :angel:

**Comment by chavafg** [comment]
@stevekuznetsov yes, it is a jenkins job, so it would be awesome your infrastructure to trigger the our jenkins job. Would you need something on my side?

**Comment by sboeuf** [comment]
@stevekuznetsov oh yeah this would make a lot of sense because I'd hope we could use all the `/retest` and `/test-all` keywords. The goal is to be seamlessly integrated into your CI and we need your guidance for that ;)

**Comment by stevekuznetsov** [comment]
Cool, definition of Jenkins servers we know how to trigger on is [here](https://github.com/openshift/release/blob/master/cluster/ci/config/prow/config.yaml#L6-L11). To set up a connection to yours I would need:

 - server URL
 - max number of executor slots you want these CI jobs occupying 
 - (privately) a user name and token for basic auth to Jenkins that can launch and cancel jobs

When we launch a job we will provide [all of these](https://github.com/kubernetes/test-infra/tree/master/prow#job-environment-variables) environment variables to the job, so any of those that are used will need to be set as parameters in your job. The main intent here is to communicate what code needs to be cloned and tested. We provide a [utility](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/clonerefs) that can clone given the configuration in those vars, but you can do it yourself as well. That's the minimum level of integration, if you have a cloud storage bucket in GCS we can talk about also pushing artifacts there.

**Comment by chavafg** [comment]
@stevekuznetsov just send you an email with the details. Thanks

**Comment by chavafg** [comment]
Closing this issue as the integration is complete. Thanks all.

**Comment by stevekuznetsov** [comment]
@chavafg is the Jenkins server at that address down? We are seeing errors attempting to contact you:

```
 {"component":"jenkins-operator","error":"error listing jenkins builds: cannot list builds from the queue: Get http://kata-jenkins-ci.westus2.cloudapp.azure.com//queue/api/json?tree=items[task[name],actions[parameters[name,value]]]: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)","level":"error","msg":"Error syncing.","time":"2018-06-12T14:24:57Z"}
```

**Comment by runcom** [comment]
yeah, jobs aren't triggered

**Comment by chavafg** [comment]
Our jenkins is currently down, should be up in the next couple of hours. Will keep you updated.
