### ISSUE TITLE
images retrieve

### ISSUE THREAD

**Issue by cucushift** [kubernetes-incubator/cri-o#1561]
hi folks, i have a doubt about `cri-o container runtime`,when i use cri-o as ` container runtime` ,why some local images can only retrieve by `ctictl --runtime-endpoint "/var/run/crio/crio.sock" images`,and `docker images` or `atomic images list` can't find them.Don't all imags respect the `OCI Image Format Specification`  ? Is this because of **storage** or `docker-shim`? thanks a lot.

**Comment by rhatdan** [comment]
CRI-O and Docker use different storage backends.  If you use podman images, you should see the images.
We are working on integrating atomic and podman, by adding a varlink interface to podman and then atomic will be able to list images stored in containers/storage created by buildah/podman or CRI-O.

**Comment by cucushift** [comment]
@rhatdan thanks.
