### ISSUE TITLE
tutorial.md path can't use make

### ISSUE THREAD

**Issue by hmtai** [kubernetes-incubator/cri-o#1570]
When I follow the cri-o/tutorial.md to use cri-o, on the step Get crictl,I can't use make command.
```
go get github.com/kubernetes-incubator/cri-tools/cmd/crictl
cd $GOPATH/src/github.com/kubernetes-incubator/cri-tools/cmd/crictl
make
make install
``` 
But when I ```cd $GOPATH/src/github.com/kubernetes-incubator/cri-tools```it works.
Does it a type error?

**Comment by giuseppe** [comment]
no, that looks like an error in the tutorial.md file, I've opened a PR:

https://github.com/kubernetes-incubator/cri-o/pull/1571

**Comment by hmtai** [comment]
:)
