### ISSUE TITLE
the problem of `make install` when the docs is not built

### ISSUE THREAD

**Issue by laijs** [kubernetes-incubator/cri-o#160]
there is still a problem which starts from #141.
although #141 was almost reverted, the problem still exists.

```
make clean   # remove the docs/*.[58]
make install # failed, stderr:
             # install -m 644  /usr/share/man/man8
             # install: missing destination file operand after ‘/usr/share/man/man8’
make install # success. (the above make install provided the docs/*.[58])
```

The reason is that `$(wildcard docs/*.5)` is calculated when the makefile is loaded, not when the install-shell-script is executed.

we should use `$(wildcard docs/*.5.md)` and calculate docs/%.5 from it.
maybe we should introduce `make install-docs`.

**Comment by rhatdan** [comment]
It was decided not to do make all when doing a make install so this is not an issue.  But I believe the other man pages handling has been implemented.  This should be closed.
