### ISSUE TITLE
Double logging to syslog and stdout/stderr?

### ISSUE THREAD

**Issue by portante** [kubernetes-incubator/cri-o#1604]
Why are conmon logs written to both stdout/stderr and syslog?  When run via systemd, won't this result in double the log output?

https://github.com/kubernetes-incubator/cri-o/blob/master/conmon/conmon.c#L142

**Comment by runcom** [comment]
@mrunalp @giuseppe ^^

**Comment by mrunalp** [comment]
I think we could have a compile option depending on whether we plan to use systemdd cgroups or not for these calls. The other option would be a flag to the conmon binary.

**Comment by giuseppe** [comment]
I think the best option would be a runtime option so that the same conmon binary can be used in both way (by CRI-O and podman)

**Comment by rhatdan** [comment]
I agree.

**Comment by mrunalp** [comment]
I'll create a PR.
