### ISSUE TITLE
Conmon timestamp buffer too small

### ISSUE THREAD

**Issue by mheon** [kubernetes-incubator/cri-o#1635]
**Description**

On some systems, conmon may fail to write anything to the attach socket at the timestamp buffer is too small.

I'm not sure exactly what kind of locale generates this, but I have shell on a system that consistently produces 45-length timestamps (longer than the 44 length of the buffer).

An example timestamp:
`2018-06-21T01:33:55.102183860+05:1800 stdout`

@edsantiago suggests that the error is at https://github.com/kubernetes-incubator/cri-o/blob/master/conmon/conmon.c#L311 and `off % 3600` should actually be `(off % 3600) / 60`

**Comment by mheon** [comment]
Found this while tracking down https://github.com/projectatomic/libpod/issues/580

**Comment by edsantiago** [comment]
Reasoning: this is one of those weird non-integer-hour tz offsets. @mheon helpfully provided a sample timestamp:
```
2018-06-21T01:33:55.102183860+05:1800
                              ^^^^^^^
```
That should be `05:30`.

**Comment by rhatdan** [comment]
Can you open a PR to fix it.

**Comment by mheon** [comment]
@rhatdan Sure, I'll take this one
