### ISSUE TITLE
Use runtime for untrusted workload even if privileged pod

### ISSUE THREAD

**Issue by sboeuf** [kubernetes-incubator/cri-o#1662]
We should not prevent CRI-O from starting the runtime defined for untrusted workloads if one or several containers of the pod need to be privileged. For instance, Kata Containers can provide a fully privileged environment, but the user has to understand that it will not run on the host with those privileges.

`kube-system` pods are the exception because they assume they will be able to modify things on the host, whilst a runtime relying on virtual machines will never be able to provide such a thing. That's why it would be good to add a check for the pod namespace and gate the runtime decision based on the name.

**Comment by mrunalp** [comment]
I think that this will change with RuntimeClass changes being proposed in kubernetes. However, no objections making these changes meanwhile.

**Comment by sboeuf** [comment]
@mrunalp yes I agree `RuntimeClass` is the long term goal.

**Comment by egernst** [comment]
Per talk this morning, @rhatdan was spot on: let's just let the annotation specify the behavior: if an untrusted runtime is provided and the untrusted annotation is present, use the untrusted runtime regardless of privilege setting.

This won't help in the default untrusted cluster setup.  In that case the user would have to patch the priv workload to say "please use untrusted runtime".  I'll dig in the code and send a PR.

**Comment by runcom** [comment]
:+1: ok with this meanwhile RuntimeClass become a thing

**Comment by rhatdan** [comment]
Obviously I like the idea.
:+1:
