### ISSUE TITLE
containers states should be saved and restored

### ISSUE THREAD

**Issue by runcom** [kubernetes-incubator/cri-o#17]
Right now if I create a pod sanbox named "test", stop ocid, restart ocid, and try to start a sandbox again with the same name ocid will of course tell me "test" already exists. This is fine but "./ocic pod remove --id test" tells me that "test" isn't in the server sandboxes - that's because sandboxes are checked on filesystem paths on start while on removal they're checked against the "server.state.sandboxes" field which is in memory and wihch is not restored on start.

**Comment by runcom** [comment]
The same applies with containers - commands like "remove" will fail while ocid knows they exist because it checks paths under /var/lib/ocid/{sandboxes|containers}

**Comment by runcom** [comment]
Sanboxes and containers in server.stage should need some sort of locking also. 

@mrunalp I've assigned this to myself but if you're already working on this feel free to reassign this to you.

**Comment by mikebrow** [comment]
Similar issue:
I did a runc kill default-podsandbox1-0-infra ... 
Subsequently ocid reports:
```
WARN[0000] error updating status for container &{be35f4b6476a80153b03e92c6e19f63e3c13aacb79e35445c32febca10036c51 default-podsandbox1-0-infra /var/lib/ocid/sandboxes/f121332f19e0a46c71ea286c3af0fd175e0cd86659fe596bd20ab12256cc1f2b /var/lib/ocid/sandboxes/f121332f19e0a46c71ea286c3af0fd175e0cd86659fe596bd20ab12256cc1f2b map[group:test] f121332f19e0a46c71ea286c3af0fd175e0cd86659fe596bd20ab12256cc1f2b %!s(bool=false) %!s(*oci.ContainerState=<nil>) {%!s(int32=0) %!s(uint32=0)}}: error getting container state for default-podsandbox1-0-infra: exit status 1: [] 
DEBU[0000] sandboxes: map[f121332f19e0a46c71ea286c3af0fd175e0cd86659fe596bd20ab12256cc1f2b:0xc420342af0] 
DEBU[0000] containers: &{map[be35f4b6476a80153b03e92c6e19f63e3c13aacb79e35445c32febca10036c51:0xc4203716c0] {{0 0} 0 0 0 0}}
```
And the default name is reserved...
```
mike@mike-VirtualBox:~/go/src/github.com/kubernetes-incubator/cri-o$ sudo ocic pod create --config test/testdata/sandbox_config.json
[sudo] password for mike: 
FATA[0000] Creating the pod sandbox failed: rpc error: code = 2 desc = conflict, name default-podsandbox1-0 already reserved 
```
And it can't be removed from the cli:
```
mike@mike-VirtualBox:~/go/src/github.com/kubernetes-incubator/cri-o$ sudo ocic pod status --id default-podsandbox1-0
FATA[0000] getting the pod sandbox status failed: rpc error: code = 2 desc = PodSandbox with ID starting with default-podsandbox1-0 not found: ID does not exist 
mike@mike-VirtualBox:~/go/src/github.com/kubernetes-incubator/cri-o$ sudo ocic pod remove --id default-podsandbox1-0
FATA[0000] removing the pod sandbox failed: rpc error: code = 2 desc = PodSandbox with ID starting with default-podsandbox1-0 not found: ID does not exist 
```

**Comment by rhatdan** [comment]
We also need to load the list of contaiers at OCID start time in order to gather the currently used MCS Labels, so that OCID does not reuse these MCS Labels for other containers.

**Comment by rhatdan** [comment]
Is  anyone working on this?

**Comment by runcom** [comment]
I am Dan.

**Comment by rhatdan** [comment]
Excellent.

**Comment by runcom** [comment]
> Similar issue:
> I did a runc kill default-podsandbox1-0-infra ...

@mikebrow @mrunalp this will need another issue to tackle that problem - right now we look for sandboxes/containers in /var/lib/ocid - if someone kills a contianer directly from runc we don't really have a way to recover from that _now_ - I'll open another issue for that but I'm now just going to implement what we already have for sandboxes (namely a restore function which loads from /var/lib/ocid/{sandboxes,containers})
