### ISSUE TITLE
Prototype conmon with --console-socket

### ISSUE THREAD

**Issue by mrunalp** [kubernetes-incubator/cri-o#171]
This will help with the push into the spec. docker/garden will be doing the same to prove out the API.

**Comment by cyphar** [comment]
Would you like me to work on it? I can implement it as a fork of my #162 PR.

**Comment by mrunalp** [comment]
@cyphar Yes, if you have the cycles :) I will assign this one to you.

**Comment by cyphar** [comment]
@mrunalp The prototype works. It lives in [this branch](https://github.com/cyphar/cri-o/tree/conmon-logging-consolesocket), and it works with both `tty=true` and `tty=false`. It still has a lot of debugging statements in it, but it should work fine for logging as well as #162. I haven't tried redis, but I'm sure that it will have similar issues to #162 unless some of the stuff I've removed has also fixed that.

**Comment by mrunalp** [comment]
@cyphar Nice! I will try that out shortly (still traveling).

**Comment by mrunalp** [comment]
@cyphar I just tested this with redis. Works fine :)

**Comment by cyphar** [comment]
Awesome! :smile_cat: But is #162 still broken for you? Just so I can see if I can narrow it down and so we can get it merged. :D

**Comment by mrunalp** [comment]
@cyphar I need to test #162 again. I am back finally so will be back on it tomorrow.

**Comment by runcom** [comment]
we do have this now https://github.com/kubernetes-incubator/cri-o/blob/master/conmon/conmon.c
