### ISSUE TITLE
failed to get valid ipv4 address for sandbox in an ipv6-only cluster

### ISSUE THREAD

**Issue by uablrek** [kubernetes-incubator/cri-o#1713]
**Description**

Starting a pod in an ipv6-only cluster fails with;

```
failed to get valid ipv4 address for sandbox...
```

**Steps to reproduce the issue:**
1. Start an ipv6-only k8s cluster with cri-o
2. Deploy some pod with ports

**Describe the results you received:**

Pods fails to start in an ipv6-cluster with cri-o.

**Describe the results you expected:**

Pods can be started.

**Additional information you deem important (e.g. issue happens only occasionally):**

The bug is [here](https://github.com/kubernetes-incubator/cri-o/blob/3961eb3959b3391ac4c00ae658d30667cdc30c5f/server/sandbox_network.go#L42).

If I remove the "To4()" is works fine. I checked out the latest source and made this small fix (hence the "dirty" in the verison below).

With the small patch applied;

```
# kubectl get nodes -o wide
NAME      STATUS    ROLES     AGE       VERSION                            INTERNAL-IP   EXTERNAL-IP   OS-IMAGE      KERNEL-VERSION   CONTAINER-RUNTIME
vm-001    Ready     <none>    15m       v1.11.2-beta.0.23+e5008de6b6637d   2000::1       <none>        Ekvm System   4.17.3           cri-o://1.12.0-dev
...
# kubectl get pods -o wide
NAME                               READY     STATUS    RESTARTS   AGE       IP               NODE      NOMINATED NODE
cgen-deployment-774bf75c67-4hmzb   1/1       Running   0          13m       fd00:3000:1::2   vm-001    <none>
...
```

**Output of `crio --version`:**

```
crio version 1.12.0-dev
commit: "3961eb3959b3391ac4c00ae658d30667cdc30c5f-dirty"
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Own BusyBox based system running on `kvm` VMs on Ubuntu 16.04.5 LTS

**Comment by runcom** [comment]
@uablrek could you open a PR with the fix please? :)

**Comment by uablrek** [comment]
I would love to but I am forbidden by company policy. This is very frustrating and I have heard changes are on the way, but not in the near future I am afraid :-(

**Comment by rhatdan** [comment]
How about attaching a patch with the fix.  :^)

**Comment by runcom** [comment]
> I would love to but I am forbidden by company policy. This is very frustrating and I have heard changes are on the way, but not in the near future I am afraid :-(

you could contribute as an individual I guess :confused: like create the patch after work lol

**Comment by uablrek** [comment]
No, sorry can't do that. It is not simply a "leach-only" policy it is concern about intellectual property. I could be fired for leaking info even for this kind of insignificant thing. But the fix I made was simply to remove the ".To4()" string. It is of course appropriate to rename the variable.

**Comment by runcom** [comment]
opened #1716
