### ISSUE TITLE
Crio devicemapper with NVMe device

### ISSUE THREAD

**Issue by bhperry** [kubernetes-incubator/cri-o#1727]
**Description**
I'm trying to switch a kubernetes cluster over from AWS m4 instances to m5 instances, which use NVMe device types. I'm creating symlinks from the NVMe device names to the block device names (e.g. /dev/nvme2n1 --> /dev/xvdb). Crio is set up with dm.directlvm_device=/dev/xvdc, which worked on the m4s but now I get the error: `/dev/xvdc is not available for use with devicemapper`. Is NVMe incompatible with CRI-O, or am I misconfiguring something? Do I need to use the NVMe device name instead of the symlink?

**Steps to reproduce the issue:**
1. Create an m5 instance on AWS
2. Attach an EBS gp2 volume
3. crio.conf [crio] settings:
```
[crio]

root = "/var/lib/containers/storage"

runroot = "/var/run/containers/storage"

storage_driver = "devicemapper"

storage_option = [
  "dm.basesize=8G",
  "dm.directlvm_device=/dev/xvdc",
  "dm.directlvm_device_force=true",
  "dm.fs=ext4"
]
```
4. crio.service systemd unit file:
```
[Unit]
Description=CRI-O daemon
Documentation=https://github.com/kubernetes-incubator/cri-o

[Service]
Type=notify
ExecStartPre=-/usr/bin/mkdir -p /usr/share/oem/lib64
ExecStartPre=-/usr/bin/cp /data/lib64/libgpgme.so.11 /usr/share/oem/lib64/
ExecStartPre=-/usr/sbin/ldconfig
ExecStart=/opt/bin/crio --log-level=info --config /etc/crio/crio.conf
ExecReload=/bin/kill -s HUP $MAINPID
TasksMax=infinity
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity
OOMScoreAdjust=-999
TimeoutStartSec=0
Restart=on-abnormal

[Install]
WantedBy=multi-user.target
```

**Describe the results you received:**
Crio failed to start with error message: `/dev/xvdc is not available for use with devicemapper`

**Describe the results you expected:**
Crio running

**Additional information you deem important (e.g. issue happens only occasionally):**
Starting the systemd service gives unhelpful error messages. Ran `/opt/bin/crio --log-level=info --config /etc/crio/crio.conf` manually to get the error message in the "results" section.

**Output of `crio --version`:**
```
crio version 1.9.7
commit: "a98f9c902421a2d02b650f20a587b345a2ca17f1-dirty"
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS m5.large, coreos 1688.5.3

**Comment by cyphar** [comment]
The problem is the symlink -- the error message you get comes from how cri-o checks whether a disk is compatible with LVM (rather than doing a check of the path you give it, it does an `lvmdiskscan` and then checks whether the path you gave it appears in the output of the scan -- so symlinks won't show up).

A simple fix would be to configure cri-o to use `dm.directlvm_device=/dev/nvme2n1`. But from the cri-o side (or rather the https://github.com/containers/storage side) would be to evaluate symlinks before checking whether paths appear in the scan.

**Comment by bhperry** [comment]
Ok, thanks! The reason I didn't use the nvme device name initially is that I've read their ordering isn't always consistent. So I guess I'll have to figure out a way to set that dynamically. I'll create a feature request on https://github.com/containers/storage as well to add symlink functionality.
