### ISSUE TITLE
docs: crio.conf(5) is incomplete

### ISSUE THREAD

**Issue by vrothberg** [kubernetes-incubator/cri-o#1747]
The `crio.conf(5)` manpage doesn't mention all supported config options (e.g., `cgroup_manager`, `hooks_dir_path` and many more).  Is there any specific reason to hide some config options or do we need to update the manpage.

**Comment by vrothberg** [comment]
@rhatdan @mrunalp WDYT?

**Comment by rhatdan** [comment]
Nope we should mention them all, and just comment them out.

**Comment by mrunalp** [comment]
Yeah, they should all be updated. Could you open a PR to fix?

**Comment by vrothberg** [comment]
@mrunalp Sure, I can take care of it.
