### ISSUE TITLE
make `/usr/share/containers/seccomp.json` default path

### ISSUE THREAD

**Issue by vrothberg** [kubernetes-incubator/cri-o#1757]
Podman's default path to the seccomp profile is `/usr/share/containers/seccomp.json` while `/etc/containers/seccomp.json` is the override path. CRI-O's default path, however, is `/etc/containers/seccomp.json` and it has no override path.

When both packages are installed on the same system, this can lead to a problem for package update scenarios where the default seccomp profile *should* be changed but won't as config files in `/etc` are usually marked to be non-replacable.

I suggest that CRI-O follows Podman's example and sets the default path to `/usr/share/containers/seccomp.json`  while the presence of `/etc/containers/seccomp.json` will override the defaults.

**Comment by rhatdan** [comment]
SGTM

**Comment by vrothberg** [comment]
Sorry, I have mixed paths. CRI-O's default path is `/etc/crio/seccomp.json`, so there is no conflict with other packages as described above. Closing the issue as I consider it to be invalid.
