### ISSUE TITLE
About the CRI

### ISSUE THREAD

**Issue by HuKeping** [kubernetes-incubator/cri-o#186]
Hi there,

I see the docs says cri-o implements the Kubelet Container Runtime Interface, does it mean the proposed one or something else? I didn't find a spec under the master branch of kubernetes/kubernetes .

**Comment by feiskyer** [comment]
@HuKeping Check https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/runtime-client-server.md and https://github.com/kubernetes/kubernetes/tree/master/pkg/kubelet/api/v1alpha1/runtime

**Comment by HuKeping** [comment]
Thanks @feiskyer
