### ISSUE TITLE
Will rkt be supported in the future?

### ISSUE THREAD

**Issue by HuKeping** [kubernetes-incubator/cri-o#191]
Hi ,

Since cri-o is an OCI-based  implementation of k8s CRI,  and it seems rkt isn't compliant to OCI at present, so do we plan to support rkt in the future? If not , what's the opinion from coreOS guys about this project. 

Personally I like rkt very much lol.

And how about the hyper/runv?

Btw, we would not integration the whole docker daemon into this project right?

I found that many kubernetes guys talking here, are they interested with this project as well?

**Comment by cyphar** [comment]
> do we plan to support rkt in the future

rkt already has a k8s runner called rktlet. IIRC it is shipped by CoreOS. https://github.com/kubernetes-incubator/rktlet

> And how about the hyper/runv?

If they can implement the OCI runtime CLI API (which there is some significant concern about at the moment w.r.t how terminals within VMs are stunted compared to terminals in containers -- when it comes it management from the host) then yes. There's a reason that `--runtime-path` is configurable.

> Btw, we would not integration the whole docker daemon into this project right?

Nope. This is an OCI project, Docker is entirely separate. In fact, there are several design elements of this project that make it superior to Docker (even Docker+containerd+runc). In particular, `ocid` doesn't need to be running at all times. You can kill it and restart it and your containers will still be running (the new `ocid` will be able to manage all of the containers as well). It's an explicit design goal to make `ocid` **not** a Docker-like daemon, and we should probably talk about that more in the README.

> I found that many kubernetes guys talking here, are they interested with this project as well?

As far as I know they are interested (Docker has a lot of questionable design decisions that are very difficult to change, but we're starting with a fresh slate after learning from their mistakes). I also talked with some CoreOS guys at some conferences and they appear to be interested in what `ocid` is doing.

**Comment by HuKeping** [comment]
> rkt already has a k8s runner called rktlet. IIRC it is shipped by CoreOS. https://github.com/kubernetes-incubator/rktlet

yay, nice !

Since the runtimes are all resides as pkg in kubernetes, does it mean those pkg would like be all wipe out when the new CRI was ready.

**Comment by Crazykev** [comment]
@HuKeping we already have a todo list about runv integration, keep an eye on #168 if you are interested.
