### ISSUE TITLE
Add support for non-numeric user

### ISSUE THREAD

**Issue by mrunalp** [kubernetes-incubator/cri-o#197]
We need to lookup the user in `/etc/passwd` in the rootfs it it exists and convert it into uid/gid to be set in runc config.json

**Comment by cyphar** [comment]
As an aside, I implemented [this in umoci](https://github.com/cyphar/umoci/issues/25). I'm not sure that `image-tools` will ever contain the code to handle that though.

**Comment by mrunalp** [comment]
Okay. I was also thinking of using libcontainer user library for this.

**Comment by rhatdan** [comment]
@mrunalp Is this still an issue?

**Comment by mrunalp** [comment]
This has been fixed.
