### ISSUE TITLE
Add support for AppArmor

### ISSUE THREAD

**Issue by feiskyer** [kubernetes-incubator/cri-o#201]
AppArmor are passed as annotations in CRI. We need to process those keys in annotations and set AppArmor in the runc config.json.

**Comment by feiskyer** [comment]
See [CRI sandbox annotations](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/api/v1alpha1/runtime/api.proto#L234) and [libcontainer AppArmorProfile config](https://github.com/opencontainers/runc/blob/master/libcontainer/configs/config.go#L128).

**Comment by xlgao-zju** [comment]
@feiskyer I would like to pick up this issue.

**Comment by mrunalp** [comment]
@xlgao-zju Go for it. Thanks!
