### ISSUE TITLE
Fix seccomp for localhost profiles

### ISSUE THREAD

**Issue by feiskyer** [kubernetes-incubator/cri-o#202]
Seccomp are passed as annotations in CRI. We need to process those keys in annotations and set Seccomp in the runc config.json.

`runtime/default` has done (#211). Still waiting for https://github.com/kubernetes/kubernetes/issues/36997: 

> localhost/<profile-name> is relative to node's local seccomp profile root, it is defined in kubelet. But runtime doesn't know it. We should pass full profile path in CRI.

**Comment by feiskyer** [comment]
See [CRI sandbox annotations](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/api/v1alpha1/runtime/api.proto#L244) and [libcontainer seccomp config](https://github.com/opencontainers/runc/blob/master/libcontainer/configs/config.go#L26).

**Comment by runcom** [comment]
@feiskyer I'd like to work on this if you aren't already. Few questions:

* k8s has a `--seccomp-profile-root string` flag, should we have the same in `ocid` to store/load seccomp profiles for pods/containers?
* where do we store the default seccomp profile for a given runtime? k8s can pass down to oci just `runtime/default`, but where do we get its content?
* https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/api/v1alpha1/runtime/api.proto#L257, this may related to the first question, where the node's local seccomp profile root? some directory setup when starting ocid I guess, right?

**Comment by feiskyer** [comment]
@runcom Cool. Seccomp profile is indeed a problem, I think CRI should pass full path to runtimes instead of relative one. Filed https://github.com/kubernetes/kubernetes/issues/36997 to fix this.

**Comment by runcom** [comment]
> @runcom Cool and good catch. Seccomp profile is indeed a problem, I think CRI should pass full path to runtimes instead of relative one. Filed kubernetes/kubernetes#36997 to fix this.

thanks :+1: I'll follow that issue and when done, I'll implement it here in `cri-o`

**Comment by feiskyer** [comment]
@runcom We didn't get a consistent conclusion for kubernetes/kubernetes#36997, and the profile path will be a known issue in kubernetes 1.5, see [here]( https://github.com/kubernetes/kubernetes/issues/36997#issuecomment-261673120).

**Comment by runcom** [comment]
> @runcom We didn't get a consistent conclusion for kubernetes/kubernetes#36997, and the profile path will be a known issue in kubernetes 1.5, see here.

@feiskyer thanks, I think we can still support `runtime/default` and `unconfined` though - correct me if I'm wrong. Going to tackle this soon if we can at least use default and unconfined.

**Comment by feiskyer** [comment]
>  I think we can still support runtime/default and unconfined though

+1.

**Comment by runcom** [comment]
Let's leave this open until the upstream k8s issue about node's profiles is sorted out. @feiskyer could you change the title here?

**Comment by feiskyer** [comment]
@runcom renamed the title.

**Comment by rhatdan** [comment]
@runcom what is the state of this issue?

**Comment by runcom** [comment]
@rhatdan still blocked on https://github.com/kubernetes/kubernetes/pull/46332

**Comment by runcom** [comment]
https://github.com/kubernetes/kubernetes/pull/46332 has been merged for node-local seccomp profiles - however we are still waiting on a seccomp spec I guess https://github.com/kubernetes/kubernetes/issues/39128
