### ISSUE TITLE
Add CNI integration

### ISSUE THREAD

**Issue by mrunalp** [kubernetes-incubator/cri-o#208]
We have CNI integration but lack the README to use it. @rajatchopra is going to add this.

**Comment by sameo** [comment]
@mrunalp Do you agree this is fixed with commit a4f5c3a8c4db24b0f7c2d11d2570a1a20006ca0e ?

**Comment by cyphar** [comment]
@sameo Can we please include the "sample CNI configuration" in the repo so that distributions can package it, and that the README is just "here's a sample file".

**Comment by runcom** [comment]
> @sameo Can we please include the "sample CNI configuration" in the repo so that distributions can package it, and that the README is just "here's a sample file".

@cyphar mmm, why not having people checkout CNI repo since they basically have the same examples? it won't change, but if the config changes we'll need to track CNI from this repo

**Comment by runcom** [comment]
(no strong opinion on this though, feel free to include a config sample if you feel strongly about it)

**Comment by cyphar** [comment]
Including the CNI source code in an RPM just to get an example configuration seems to me to be a _little_ overkill. ;)

**Comment by runcom** [comment]
> Including the CNI source code in an RPM just to get an example configuration seems to me to be a little  overkill. ;)

nah, I didn't mean that (if I got correctly what you said)

**Comment by cyphar** [comment]
> why not having people checkout CNI repo since they basically have the same examples?

I was assuming "people" meant me packaging ocid. I'll add an example tomorrow (/me -> bed). :wink:

**Comment by runcom** [comment]
@cyphar the misunderstanding lies in me saying _checkout CNI repo_ - by checkout I meant _have a look on the github repo on the web_

**Comment by cyphar** [comment]
Ah, right. "go check out" not `git checkout`. :smile_cat:

**Comment by runcom** [comment]
> Ah, right. "go check out" not git checkout.

I should take another english class soon...myb

**Comment by mrunalp** [comment]
@sameo Yeah, I think we are good. I am okay either ways on adding the config files. Will wait for @cyphar

**Comment by cyphar** [comment]
This is in #295.
