### ISSUE TITLE
Add support for port forwarding

### ISSUE THREAD

**Issue by mrunalp** [kubernetes-incubator/cri-o#209]
We need to figure out where will this be handled. @rajatchopra is going to talk to CNI team and get back.

**Comment by feiskyer** [comment]
@mrunalp Do you mean implement port forwarding in CNI?

**Comment by mrunalp** [comment]
That is what needs to be figured out whether it has to be delegated to CNI or we need to handle it here directly.

**Comment by Crazykev** [comment]
@mrunalp Could we use the same way as dockershim did, like using `nsenter` and `socat`,  do that job?  Or is there any benefit to delegate to CNI?

**Comment by cyphar** [comment]
> Or is there any benefit to delegate to CNI?

CNI directly matches the networking model for k8s, and also means that we don't have to deal with any networking code inside cri-o.

**Comment by rajatchopra** [comment]
CNI plans to put in plugin chaining (https://github.com/containernetworking/cni/pull/339) based on this spec (https://gist.github.com/squeed/c69206c51f7d38d1cbb5211a3fde5d06)

Until that gets merged we cannot have a clean way of doing port forwarding through CNI.

Even then, port forwarding is an event that occurs during the pod lifetime. That means CNI should be able to handle events or 'update' calls. Not in CNI yet again.

Upshot: short term we cannot expect the port forwarding code to start working through cni.

**Comment by mrunalp** [comment]
@Crazykev @cyphar @rajatchopra Looks like in the short term we can follow the dockershim model of using nsenter + socat. Or a custom binary that does the same.

**Comment by rajatchopra** [comment]
+1 custom binary
We can take the binary into a cni plugin when cni spec is ready with the mechanism.

**Comment by mrunalp** [comment]
This has been completed.
