### ISSUE TITLE
Clean container files on CreateContainer failure

### ISSUE THREAD

**Issue by runcom** [kubernetes-incubator/cri-o#22]
Filing issue so we don't forget. If `CreateContainer` https://github.com/kubernetes-incubator/ocid/blob/master/server/runtime.go#L307 fails we should not leave files and dirs around in `/var/lib/ocid`.

I already fixed this in `CreatePodSandbox` in the first commit of https://github.com/kubernetes-incubator/ocid/pull/15

**Comment by mrunalp** [comment]
I am working on this one. Assigning to myself.
