### ISSUE TITLE
Add support for kpod run

### ISSUE THREAD

**Issue by mrunalp** [kubernetes-incubator/cri-o#221]
This command will support launching pods. It may involve refactoring the code so it could be better shared between ocid/kpod. We could follow the CLI from here and add what is missing 
http://kubernetes.io/docs/user-guide/pods/single-container/

**Comment by mheon** [comment]
I've started work on this. Right now, I'm refactoring parts of the server to allow kpod to use the same underlying runtime code as the cri-o server.

**Comment by runcom** [comment]
> Right now, I'm refactoring parts of the server to allow kpod to use the same underlying runtime code as the cri-o server.

cool, please submit those changes first if possible

**Comment by Crazykev** [comment]
> Right now, I'm refactoring parts of the server to allow kpod to use the same underlying runtime code as the cri-o server.

@mheon Does this have any progress? If it's almost done, I'll just hold on.

**Comment by mheon** [comment]
@Crazykev I'm working on it, but still working out the best way to cleanly separate the two - if you're going to be touching that part of the codebase, feel free.

**Comment by Crazykev** [comment]
@mheon I feel like this is the common part we are working, and just like you said, for now, I don't have a clear way to separate the two either. Will be very appreciate if you can bring a wip PR when you figure out how to do that.

**Comment by rhatdan** [comment]
Yes lets open a WIP pull request to get people like @mrunalp thoughts.

**Comment by rhatdan** [comment]
@mrunalp lets change the title on this to kpod run.
@mheon Could you update the status on this.

**Comment by mheon** [comment]
Presently working on refactoring to make containers independent from pods, so they can be created without requiring a pod be created prior. This will allow `kpod run` to be written.

**Comment by rhatdan** [comment]
kpod run is now available in libpod repo.
