### ISSUE TITLE
Add support for kpod exec

### ISSUE THREAD

**Issue by mrunalp** [kubernetes-incubator/cri-o#223]
Support exec'ing into pods using kpod.

**Comment by feiskyer** [comment]
Maybe add a unified issue for tracking kpod feature?

**Comment by mrunalp** [comment]
@feiskyer We could add a tracking issue that links to individual issues so they could be assigned to whoever wants to work on them.

**Comment by rhatdan** [comment]
@feiskyer what we are looking for is a way to allow contributors to grab different issues, so we don't have multiple people working on the same feature.

**Comment by feiskyer** [comment]
> what we are looking for is a way to allow contributors to grab different issues, so we don't have multiple people working on the same feature.

yeah. make senses to me. Thanks.

**Comment by Crazykev** [comment]
@mrunalp If it's fine with you, I would like take this as a start.

**Comment by mrunalp** [comment]
@Crazykev Sure, thanks!

**Comment by rhatdan** [comment]
@Crazykev Did you ever work on this?

**Comment by mrunalp** [comment]
@rhatdan I believe we will need to re-assign all of these kpod issues.

**Comment by rhatdan** [comment]
Yes, I think either you or @mheon have to work on this.

**Comment by Crazykev** [comment]
@rhatdan Not working on this recently, please re-assign someone else.

**Comment by rhatdan** [comment]
@baude  was working on this.  Moving it to libpod repo.
