### ISSUE TITLE
Add support for kpod ps

### ISSUE THREAD

**Issue by mrunalp** [kubernetes-incubator/cri-o#224]
Support listing pods using kpod.

**Comment by GrantSeltzer** [comment]
I've been working on this, you can assign me to it.

**Comment by rhatdan** [comment]
Should be reassigned to @baude and renamed to kpod ps

**Comment by umohnani8** [comment]
kpod ps was added https://github.com/kubernetes-incubator/cri-o/pull/776
@rhatdan @mrunalp issue can be closed
