### ISSUE TITLE
Add support kpod list images

### ISSUE THREAD

**Issue by mrunalp** [kubernetes-incubator/cri-o#225]
Support listing images in image store using kpod.

**Comment by nhlfr** [comment]
I would like to work on this, please assign me

**Comment by runcom** [comment]
@nhlfr thanks! Please not there are still 2 PRs flying around #189 and #210 that must be in master before going with this one. Also, note that we're trying to abstract most of what we have under `server/` right now to have a clean API shared between `cri-o` (the CRI implementation) and `kpod`.

**Comment by rhatdan** [comment]
@14rcole Is working on this.  Please link your pull request to this issue.

**Comment by umohnani8** [comment]
kpod images was added https://github.com/kubernetes-incubator/cri-o/pull/606
@rhatdan @mrunalp issue can be closed
