### ISSUE TITLE
Add support for image info

### ISSUE THREAD

**Issue by mrunalp** [kubernetes-incubator/cri-o#226]
Support getting information about an image using kpod.

**Comment by jawnsy** [comment]
@mrunalp @runcom Can you add some instructions on how to get started with this?

**Comment by rhatdan** [comment]
@14rcole is working on this kpod inspect --images  Please link your pull request.

**Comment by umohnani8** [comment]
kpod inspect was added https://github.com/kubernetes-incubator/cri-o/pull/648
@rhatdan @mrunalp issue can be closed
