### ISSUE TITLE
Add support for kpod remove image

### ISSUE THREAD

**Issue by mrunalp** [kubernetes-incubator/cri-o#227]
Add support for removing images (that aren't in use) using kpod which could be used for cleaning up node storage.

**Comment by surajssd** [comment]
@mrunalp can you assign this to me?

**Comment by feiskyer** [comment]
@surajssd Cool. Assigned.

**Comment by surajssd** [comment]
@feiskyer thanks :) Working on it now!

**Comment by rhatdan** [comment]
@14rcole has a pull request for this.  Ryan please add link.

**Comment by umohnani8** [comment]
Was added a while back https://github.com/kubernetes-incubator/cri-o/pull/606.
@rhatdan @mrunalp  issue can be closed.
