### ISSUE TITLE
Add support for kpod pod info

### ISSUE THREAD

**Issue by mrunalp** [kubernetes-incubator/cri-o#229]
Add support for displaying information about a pod including resource usage.

**Comment by xlgao-zju** [comment]
@mrunalp I would like to pick up this issue.

**Comment by feiskyer** [comment]
@xlgao-zju Cool. Marked as assigned.

**Comment by rhatdan** [comment]
@xlgao-zju have you worked on this?  We are now following the docker CLI, not sure if this overlaps or would stay as a separate command.

**Comment by xlgao-zju** [comment]
@rhatdan No, actually. Feel free to close this or reassign this to someone else.

**Comment by rhatdan** [comment]
@mrunalp Lets close this and see if we need extra commands once we have completed the kpod suite.
