### ISSUE TITLE
Pod sandbox container setup

### ISSUE THREAD

**Issue by mrunalp** [kubernetes-incubator/cri-o#23]
Today, the creation is manual. We need to automate it and make it user configurable.

**Comment by runcom** [comment]
@mrunalp should every pod sandbox run kubernetes/pause? I haven't really understood if that's the case

**Comment by runcom** [comment]
This seems to be related to https://github.com/kubernetes-incubator/ocid/issues/8 though - since we need a way to setup images before attempting to run containers

**Comment by mrunalp** [comment]
@runcom Yes, each pod needs to run it. But, what we do today is end up pointing to the same rootfs and make the rootfs readonly in config so it is shared by all the pod infra containers. Also, the reason why we are running it is because at some point we want to be able to run systemd/init in the pause container (if the user wants). Another alternative in the short term is to just replace the pod infra container by bind mounted ipc and net namespaces. 

Also, yes, the final solution will be in #8 for anything related to container filesystem setup.
