### ISSUE TITLE
StopPodSandbox() fails when called multiple times and network enabled

### ISSUE THREAD

**Issue by sameo** [kubernetes-incubator/cri-o#232]
According to the CRI specs:

```
This call is idempotent, and must not return an error if all relevant
resources have already been reclaimed. kubelet will call StopPodSandbox
at least once before calling RemovePodSandbox. It will also attempt to
reclaim resources eagerly, as soon as a sandbox is not needed. Hence,
multiple StopPodSandbox calls are expected.
```

However when running CRI-O `StopPodSandbox()` more than once on the same pod, ocicni returns an error:

```
E1206 11:16:58.643915   29033 ocicni.go:233] Error deleting network: failed to Statfs "/proc/29117/ns/net": no such file or directory
```

**Comment by sameo** [comment]
@runcom @mrunalp Also, are we expecting the sandbox networking namespace to be closed and removed on a `StopPodSandbox()` call ?

**Comment by feiskyer** [comment]
> Also, are we expecting the sandbox networking namespace to be closed and removed on a StopPodSandbox() call ?

According to [cri](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/api/v1alpha1/runtime/api.proto#L15), network resources should be released on `StopPodSandbox()`.

**Comment by runcom** [comment]
we can just check if the netns is still around - if it isn't stop will be a no-op as it should be.

**Comment by runcom** [comment]
ping @rajatchopra wdyt?

**Comment by runcom** [comment]
@sameo can you share a reproducer? are you using a CNI plugin for this bug to trigger?

**Comment by sameo** [comment]
@runcom Yes, I'm using the CNI bridge plugin. Just adding:

```
$ cat /etc/cni/net.d/10-mynet.conf 
{
    "cniVersion": "0.2.0",
    "name": "mynet",
    "type": "bridge",
    "bridge": "cni0",
    "isGateway": true,
    "ipMasq": true,
    "ipam": {
        "type": "host-local",
        "subnet": "10.88.0.0/16",
        "routes": [
            { "dst": "0.0.0.0/0" }
        ]
    }
}
```

should reproduce the issue.

**Comment by rajatchopra** [comment]
Fair to check netns validity before calling, or skip to a no op.
