### ISSUE TITLE
apparmor: handle cases where profiles are unloaded

### ISSUE THREAD

**Issue by cyphar** [kubernetes-incubator/cri-o#255]
From docker/docker#29130 it is possible for AppArmor profiles to be unloaded by system services (such as unattended upgrades). This is because we are generating the profiles ourselves and inserting them directly. Basically we just have to port docker/docker#29130 to cri-o.

**Comment by runcom** [comment]
https://github.com/kubernetes-incubator/cri-o/pull/239#issuecomment-265435462

**Comment by cyphar** [comment]
There are several issues with that PR. I'm submitting my own (I already started writing it before checking).

**Comment by xlgao-zju** [comment]
I think we should close this issue, since #239 has been in.

**Comment by cyphar** [comment]
Yup.

**Comment by feiskyer** [comment]
yes, already solved in #239.
