### ISSUE TITLE
Missing networking functional tests

### ISSUE THREAD

**Issue by sameo** [kubernetes-incubator/cri-o#266]
We currently do not test networking at all with bats. We'd like to at least test the following use cases:

* Host network: verify that we're living in the right namespace when using the host network.
* Create a temporary CNI bridge plugin configuration and verify that:
   * We get an eth0 interface in the networking namespace, set with the correct IP
   * We can ping the host network back

And in order to do that we need to be able to pass a CNI configuration file directory to `ocicni` so that we can create temporary CNI files for the purpose of network testing.

**Comment by sameo** [comment]
Please assign that one to me.

**Comment by mrunalp** [comment]
@sameo Thanks!
