### ISSUE TITLE
Error `wait: no child process`

### ISSUE THREAD

**Issue by Crazykev** [kubernetes-incubator/cri-o#268]
When make local test,  will run into this error `wait: no child process` intermittently. In [here](https://github.com/kubernetes-incubator/cri-o/blob/master/oci/oci.go#L300)  and [here](https://github.com/kubernetes-incubator/cri-o/blob/master/utils/utils.go#L29) when we call `cmd.Run`. 

When look deep in the golang source code, will see a race condition in `cmd.Run`, that process may finished before `cmd.Wait` could be scheduled. 

I don't think this is a serious problem, so we may be need to filter it manually.

**Comment by Crazykev** [comment]
@runcom I have checked related man page with [ECHILD](http://man7.org/linux/man-pages/man2/waitpid.2.html#ERRORS)

> ECHILD 
(for waitpid() or waitid()) The process specified by pid
              (waitpid()) or idtype and id (waitid()) does not exist or is
              not a child of the calling process.  (This can happen for
              one's own child if the action for SIGCHLD is set to SIG_IGN.
              See also the Linux Notes section about threads.)

As pointed early, when a race condition happen, we may receive an ECHILD error, since this imply that we have set SIGCHLD to SIG_IGN(not sure when did that, maybe set by golang defaultly), this won't lead to a zombie problem, so it's not harm to ignore them. Do you have other concerns about this?

**Comment by runcom** [comment]
See https://github.com/kubernetes-incubator/cri-o/pull/272
