### ISSUE TITLE
Consider adding cgroup driver or other workaround to support pod level QoS

### ISSUE THREAD

**Issue by resouer** [kubernetes-incubator/cri-o#270]
Encountered this issue when working on pod level QoS support: #271. This feature is important for fine grained QoS tiers, and meaningful to hypervisor containers like runV, CC to figure out its VM's resource boundary.

**Background:**
The basic idea of pod level QoS is: kubelet will create a pod level `cgroupParent` path and pass this value to runtimes, so for example, in CRI+docker we will have `/Bu/Bu-podxxx/` as parent, and create cgroupfs like this:
```
/Bu/Bu-podxxx/containerID/memory_limit_of_container
/Bu/Bu-podxxx/memory_limit_of_pod
```

That's why runtime should be aware of cgroup driver and convert `/Bu/Bu-podxxx/` to `/Bu.slice/Bu-podxxx.slice/` if needed. 

**The Problem:**
But I see now cri-o just [pass `cgroupParent` directly to runC](https://github.com/kubernetes-incubator/cri-o/blob/master/server/sandbox_run.go#L248), which would not work for pod level QoS because cri-o is expected to add `containerID` after `/Bu/Bu-podxxx/` and make sure this newly created `cgroupPath` in right syntax.

**Proposal:**
So, we can:
1. make cri-o become cgroup driver aware
2. stick to only one type of cgroup driver
3. make runC be able to deal with syntax convert
4. make kubelet generate `cgroupParent` in right syntax. (This is unlikely since CRI does not assume runtime expose cgroup information or define a `Info()` api)

One concern is cgroup awareness requires taking care of consistency with runC's configuration.

Any suggestion on this problem?

**Comment by runcom** [comment]
@mrunalp @cyphar

**Comment by cyphar** [comment]
I would recommend just sticking with runC's `cgroupfs` driver. The systemd one is ... questionable at best.

**Comment by resouer** [comment]
while @mrunalp thought both cgroup type should be supported, https://github.com/kubernetes-incubator/cri-o/pull/271#issuecomment-267198572  ...

btw, is runc using systemd by default (did not look code, just based on my env)

**Comment by mrunalp** [comment]
Default is cgroupfs.

**Comment by resouer** [comment]
@cyphar So could you please explain more details about your concern about `systemd`?

**Comment by cyphar** [comment]
We have had a very long history if issues with `systemd`. The TransientUnit DBus API that they provide does not have enough controls for our `cgroup` modification requirements in runC -- so what we do is that we manually modify the cgroup settings after setting up a `systemd` slice (using the `cgroupfs` code).

So the only difference between `cgroupfs` and `systemd` is that with `systemd` we tell `systemd` about the container we're creating. The problem with that is that `systemd` quite often has issues where it will randomly start moving cgroups around which then means that containers get broken. This has been moving to be more usable in more recent versions of `systemd` (especially with the `Delegate` keyword).

However, I'm still not one to trust `systemd`. I think their model (one daemon that manages absolutely everything) clashes with how runC operates -- and trying to resolve the issue completely would require us to effectively reimplement `systemd-nspawn` (and thus become `rkt`).

**Comment by rhatdan** [comment]
I think we should continue to support both.  At some point Systemd might be come the sole controller/designator for Cgroups, as cgroup2 gets implemented.

**Comment by cyphar** [comment]
@rhatdan 

> as cgroup2 gets implemented.

Heh, cgroup2 is already implemented (in the kernel, the runC code still isn't there because I still haven't managed to boot a system using `cgroupv2`) and `systemd` is basically enshrined as the only controller for the whole stack. The only way to get out of it is to ask `systemd` to delegate to you (which Docker already requires and `ocid` will also require), at which point you should be using `cgroupfs`.

**Comment by resouer** [comment]
OK, so let's stick to cgroupfs in code and close this for now. Thank you for all advices.
