### ISSUE TITLE
CNI netns(s) leaking

### ISSUE THREAD

**Issue by runcom** [kubernetes-incubator/cri-o#273]
I have a bunch of:
```
/run/netns/cni-0d9d20e6-5728-763a-5c2b-db6acad98c1c
/run/netns/cni-233057eb-f3dd-4c88-426a-ee5a6ded3472
/run/netns/cni-23dd840c-3b60-5fbc-5272-2caa3014f41a
/run/netns/cni-2a419ce5-19da-1082-cf21-2bd63c1e8ed5
/run/netns/cni-2d7122db-1f71-4191-ee5f-34c415b2019b
/run/netns/cni-3f26173b-4b3e-0b12-7b08-203da18a3578
/run/netns/cni-43b36dbf-484b-db9c-dc6b-ddf0b308e54e
/run/netns/cni-4c81d509-5fc9-1e2e-0c6d-11c3c6388e1e
/run/netns/cni-588b7921-9414-5a95-c9da-16c85abe8953
/run/netns/cni-5b9eccf8-c538-6fac-36b7-cf265177810d
/run/netns/cni-65d42733-8f53-b758-7835-7a2a09cd2feb
/run/netns/cni-783d970e-9fcf-5a69-4614-50c31d38dd5c
/run/netns/cni-840c35ef-7e06-6f6e-f5db-a3c3ce29f484
/run/netns/cni-87833194-0e7c-4030-99d8-f4e8d5af9746
/run/netns/cni-8b0cb7b8-bce7-ec40-d16b-171b67dcf9fb
/run/netns/cni-987940f1-00f5-bfdc-4507-0306004b3f9f
/run/netns/cni-a6b02f7f-0f48-1257-5c78-14c93732ea43
/run/netns/cni-b1531181-8643-52f5-699c-1929bea46efa
/run/netns/cni-b1a80b68-8af6-0f4a-5402-d1733ba50ee4
/run/netns/cni-bc7dcfe8-eeac-b549-b915-17ddcc54da3d
/run/netns/cni-be3c71c5-db8d-1d8f-0394-c220ce7623c2
/run/netns/cni-c32093c2-c4b4-e108-d9e5-860f3ddd9102
/run/netns/cni-d14636b0-b1e5-c6e3-8a72-21a2893b0196
/run/netns/cni-ef6a1e32-ef44-fd9d-6d3c-fa6adb16032a
/run/netns/cni-f9176049-d834-fbf9-5809-52aa7c170f9a
```
in my mounts. I'm sure every runc containers has been properly stopped (and ocid is stopped as well) - not sure what could cause this leak. (I have a bunch of veth(s) on the system also still lying around).

@mrunalp @rajatchopra PTAL

**Comment by runcom** [comment]
could be actually my fault since I directly remove runc containers via `runc` rather than with `ocic` - will check and get back

**Comment by sameo** [comment]
@runcom Removing them with ocic should remove all the netns and clear the host veths. Please let me know if it doesn't and assign the issue to me if that's so.

**Comment by runcom** [comment]
> @runcom Removing them with ocic should remove all the netns and clear the host veths. Please let me know if it doesn't and assign the issue to me if that's so.

now the issue is I'm not able to reproduce this anymore - like, those mounts aren't created anymore (running k8s+CRI-O)

**Comment by runcom** [comment]
oh, could be tests (when they fail)

**Comment by runcom** [comment]
right, this is happening with failing tests that leaves stuff on the host:
```
18:06:22 [~] ls -la /run/netns
total 0
drwxr-xr-x.  2 root root   80 Dec 14 18:05 .
drwxr-xr-x. 51 root root 1460 Dec 14 18:05 ..
-r--r--r--.  1 root root    0 Dec 14 18:05 cni-80ba0d58-5b9a-cee2-3ea9-10b9691d94df
lrwxrwxrwx.  1 root root   55 Dec 14 18:05 redhat.test.ocid-podsandbox1-1-1d19c604 -> /var/run/netns/cni-80ba0d58-5b9a-cee2-3ea9-10b9691d94df
```

**Comment by runcom** [comment]
@sameo tests aren't really using network (nor testing networking) right now, but I have CNI plugins on my system and network gets setup automatically. Is there any way to disable this?

**Comment by runcom** [comment]
@sameo (sorry for multiple comments). Even when tests run fine and no errors or containers are kept running I do have a leak:
```
/run/netns/cni-000c92c6-593f-6ab8-af8d-d000299f753e
```
I can reproduce by just running `sudo make localintegration` on my host (with CNI setup as per instructions in the README)

**Comment by sameo** [comment]
@runcom Let me try and fix that leak.

**Comment by sameo** [comment]
@runcom Can you please test PR #276 ? It does fix a leak I could reproduce when running localintegration. With that patch, you netns should be all cleared.

I need to see if I can reproduce the error case now.
