### ISSUE TITLE
Missing a dependency file with a list of dependencies and its coresponding commits

### ISSUE THREAD

**Issue by ingvagabund** [kubernetes-incubator/cri-o#280]
Please, provide glide.lock, Godeps.json, glock.yml or any file that captures the current dependencies used on the projects.

**Comment by runcom** [comment]
@ingvagabund look for `hack/vendor.sh`

**Comment by ingvagabund** [comment]
I found the file, still, it is non-standard way to store the deps. I got automatic tooling that read the dependency file and checks if each dependency's corresponding commit is already packaged in distro.

**Comment by runcom** [comment]
I know it isn't, we're using that which is used by docker as well.

**Comment by mrunalp** [comment]
@ingvagabund We cycled through all of the dependency managers that you mention early on in the project. Each of them had their own downsides and were not consistent in pulling just the right dependencies. Hence we switched to this simple hack/vendor.sh script.

**Comment by ingvagabund** [comment]
@mrunalp is there a predefined format for the vendor.sh? Can i expect each line with a dependency will always start with `clone git ` prefix?

**Comment by runcom** [comment]
@ingvagabund yes, when there's a dependency you have a line consistently starting with `clone `.
