### ISSUE TITLE
Tests don't work on openSUSE

### ISSUE THREAD

**Issue by cyphar** [kubernetes-incubator/cri-o#293]
I tried running the test suite, and it just hanged after the apparmor tests were done (all of which failed except for the first one). There's also the lovely no-cleanup issue which means that running the test suite again causes all of the tests to fail.

I'll investigate further, I'm just putting it here to remind myself of this.

**Comment by runcom** [comment]
> There's also the lovely no-cleanup issue which means that running the test suite again causes all of the tests to fail.

@mrunalp thought at using `TRAP` for the cleanup, I'll let him chime in but the idea sounds good to me

**Comment by mrunalp** [comment]
@cyphar I have been using a stupid cleanup script for starting tests with a clean slate. I'll post it here. Tests have gotten much better for us but there are still a few flakes. If you figure out specific issues that need fixing please post more details :)

**Comment by mrunalp** [comment]
cleanup.sh
```
#!/bin/bash -x

runc list | awk '{print $1}' | grep -v ID | xargs runc delete -f
mount | grep shm | grep /tmp/tmp | awk '{print $3}' | xargs umount
mount | grep devicemapper | grep /tmp/tmp | awk '{print $3}' | xargs umount
rm -rf /tmp/tmp.*
mount | grep shm | grep /var/lib/ocid | awk '{print $3}' | xargs umount
mount | grep devicemapper | grep /var/lib/ocid | awk '{print $3}' | xargs umount
rm -rf /var/lib/ocid
```

**Comment by rhatdan** [comment]
@cyphar is this still an issue, or can we close this?

**Comment by rhatdan** [comment]
Since CRI-O Seems to be working with OpenSUSE, I am going to close this issue.
