### ISSUE TITLE
containers state is flawed wrt storage

### ISSUE THREAD

**Issue by runcom** [kubernetes-incubator/cri-o#294]
Running tests with both k8s and ocic, the result is storage state is not consistent across restarts and 4/5 that results in an ocid panic. I don't really have a way to reproduce, just playing around. I tried to fix most of the panic here https://github.com/kubernetes-incubator/cri-o/compare/master...runcom:alpha (my commits on top of @nalind's #189). There are still many panics because that `s.Update()` at the beginning of each request makes stuff harder also, for instance, removing a container results in bad state because `s.Update()` does play with `s.state.containers` but we're also removing a container from there and that ends up in a panic..

Opened just for tracking, I don't fully have a fix for this except the commits in https://github.com/kubernetes-incubator/cri-o/compare/master...runcom:alpha (they doesn't fully fix this though)

**Comment by mrunalp** [comment]
@runcom I think we should refactor and add a separate storage interface through which all persistence calls go. It will be easier to support different backends that way as well as interoperate with kpod.

**Comment by runcom** [comment]
#505
