### ISSUE TITLE
conmon depends on GLib (glib.h)

### ISSUE THREAD

**Issue by jawnsy** [kubernetes-incubator/cri-o#297]
It looks like conmon links to GNOME's GLib library, but is only using a handful of functions. It adds some weight to the resulting binary, so we should consider removing the dependency.

Possibilities:

* Rewrite conmon in Rust? (seems kinda ambitious)
* Use builtin libc filehandling support, e.g. `fopen` and friends
* ???

Here are the errors that result if you drop the include for `glib.h`:

```
cc -Wall -Wextra    -c -o conmon.o conmon.c
conmon.c: In function ‘main’:
conmon.c:69:2: error: unknown type name ‘GError’
  GError *err = NULL;
  ^~~~~~
conmon.c:174:2: warning: implicit declaration of function ‘g_file_get_contents’ [-Wimplicit-function-declaration]
  g_file_get_contents("pidfile", &contents, NULL, &err);
  ^~~~~~~~~~~~~~~~~~~
conmon.c:176:54: error: request for member ‘message’ in something not a structure or union
   fprintf(stderr, "Failed to read pidfile: %s\n", err->message);
                                                      ^~
conmon.c:177:3: warning: implicit declaration of function ‘g_error_free’ [-Wimplicit-function-declaration]
   g_error_free(err);
   ^~~~~~~~~~~~
conmon.c:284:4: warning: implicit declaration of function ‘g_file_set_contents’ [-Wimplicit-function-declaration]
    g_file_set_contents("exit", status_str,
    ^~~~~~~~~~~~~~~~~~~
conmon.c:289:21: error: request for member ‘message’ in something not a structure or union
      status_str, err->message);
                     ^~
<builtin>: recipe for target 'conmon.o' failed
make: *** [conmon.o] Error 1
```

**Comment by cyphar** [comment]
Yeah, this is one of the things that we need to discuss for #24, as well as the streaming server requirements. Specifically, we need to decide if we're going to switch languages to support streaming, because implementing many-to-many streaming in a single C binary is going to be ... fun.

> Use builtin libc filehandling support, e.g. fopen and friends

The thing is, `glib` is actually useful for the things we're using it for. The only justification I can see for dropping `glib` is if we change languages.

**Comment by cyphar** [comment]
Also #162 #282.

**Comment by mrunalp** [comment]
On the topic of Rust, I am keeping an eye on the the `mio` and `tokio` libraries. Once they are stable, it will become a very good candidate :wink:

**Comment by runcom** [comment]
> On the topic of Rust, I am keeping an eye on the the mio and tokio libraries. Once they are stable, it will become a very good candidate

are `mio` and `tokio` going to support async file I/O though? I know libuv does but I cannot find any library for rust which does file I/O :confused:

**Comment by cyphar** [comment]
I've been looking into `libuv`. It looks quite good (and I've interacted with it a bit while hacking on NeoVim), though I'm still wondering how we're going to implement the API for the streaming server. But that will also be an issue for Rust as well.

**Comment by mrunalp** [comment]
Closing this. We have switched to using glib for handling this. We can revisit in future if necessary.
