### ISSUE TITLE
Default PREFIX should be /usr/local

### ISSUE THREAD

**Issue by jawnsy** [kubernetes-incubator/cri-o#300]
By default, `sudo make install` installs binaries into `/usr/bin`, but in my opinion we should instead be installing into `/usr/local/bin` to avoid conflicts with vendor binaries.

Code reference: https://github.com/kubernetes-incubator/cri-o/blob/master/Makefile#L11

This may need to be overridden in vendor (rpm/deb) builds so that files are installed to the proper location, but this is normal/expected practice for packagers and something they know how to handle well.

**Comment by mrunalp** [comment]
@rhatdan @cyphar PTAL

**Comment by jawnsy** [comment]
Dug up the appropriate section of the [Filesystem Hierarchy Standard](http://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s09.html):

> The `/usr/local` hierarchy is for use by the system administrator when installing software locally. It needs to be safe from being overwritten when the system software is updated. It may be used for programs and data that are shareable amongst a group of hosts, but not found in `/usr`.
>
> Locally installed software must be placed within `/usr/local` rather than `/usr` unless it is being installed to replace or upgrade software in `/usr`.

If you are on rawhide, and you `dnf install ocid`, then `sudo make install` will currently overwrite the system binary. Subsequent `dnf upgrade` runs may overwrite ocid.

On the other hand, this does mean that the `PATH` needs to be configured correctly (that is, `/usr/local` must take precedence over `/usr`). On a clean system, this is generally the case:

```
$ docker run --rm -it debian:unstable /bin/sh -c 'echo $PATH'
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
$ docker run --rm -it fedora:rawhide /bin/sh -c 'echo $PATH'
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

**Comment by mrunalp** [comment]
Could you create a PR for this?

**Comment by rhatdan** [comment]
SGTM
I personally do not like installing stuff by default in /usr/local, since I always get confused about which package I am using, or I have old cruft in /usr/local.  But this seems to be the rules.  

```
make PREFIX=/usr install
```

If we used something like autoconf to generate the Makefile, then this would not be as big a problem.
