### ISSUE TITLE
tags and versions

### ISSUE THREAD

**Issue by cyphar** [kubernetes-incubator/cri-o#303]
Currently `ocid` doesn't have any version tags. While I realise it's all very active development, it is simply not practical to package `ocid` before it has some concept of versioning. Maybe we should just tag the current version as `0.0.0` and then bump it as often as we feel is appropriate.

**Comment by jawnsy** [comment]
+1. Versions are a good idea to have. Now that we have a package in rawhide, it helps if we use semantic versioning to communicate to maintainers the likelihood of breakages. It's also generally understood that anything before the 1.0.0 release is subject to change, so wouldn't be any different from today.

Kubernetes and OpenShift add git commit id's for the build as well, which might be useful: https://github.com/kubernetes/kubernetes/blob/master/pkg/version/base.go

**Comment by cyphar** [comment]
> It's also generally understood that anything before the 1.0.0 release is subject to change, so wouldn't be any different from today.

Yup. I'm not sure how the version was handled in rawhide, but in openSUSE most people end up creating horrible versions like `0.0.0+20161231.gitHASH`, which isn't a helpful version number at all.

> Kubernetes and OpenShift add git commit id's for the build as well, which might be useful: https://github.com/kubernetes/kubernetes/blob/master/pkg/version/base.go

Sure, but remember that commit ids are not a replacement for versions. We should use something like `0.0.0~git<hash>` which won't cause issues with RPM's version comparison algorithms. :wink:

**Comment by jawnsy** [comment]
For reference, the latest package build in rawhide is `0-0.7.git2e6070f.fc26` https://apps.fedoraproject.org/packages/ocid/

It would be a good idea to pick a version scheme compatible with Debian's `dpkg` as well: https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Version

> The upstream_version may contain only alphanumerics and the characters . + - : ~ (full stop, plus, hyphen, colon, tilde) and should start with a digit.

So the same type of version number, like `0.7~git2e6070f` should be good for everyone (I have no idea where Fedora got the version number, maybe @lsm5 can shed some light).

**Comment by lsm5** [comment]
the version number used is `0`, the release tag is what follows after the `-` so `0.7.git2e6070f`, and `2e6070f` was the commit id used from @runcom's branch https://github.com/runcom/ocid-1/commits/alpha

**Comment by rhatdan** [comment]
I agree we should have version tags.

**Comment by mrunalp** [comment]
I pushed a v0.0.0 tag just now.

**Comment by cyphar** [comment]
Closing.
