### ISSUE TITLE
Configurable stop signals for containers (read from image config)

### ISSUE THREAD

**Issue by jawnsy** [kubernetes-incubator/cri-o#306]
When `StopContainer` is called, the container will be forcibly terminated with the `SIGKILL` signal, which cannot be caught or handled by processes.  This immediately kills processes without prior warning, which may result in data loss for some types of workloads (such as databases) or other undesirable behaviour (such as connection timeouts, as applications don't have a chance to gracefully close connections).

Code reference: https://github.com/kubernetes-incubator/cri-o/blob/master/oci/oci.go#L278

List of available signals: https://en.wikipedia.org/wiki/Unix_signal#POSIX_signals

We should consider a more graceful shutdown sequence, such as:

0. Send process `SIGTERM`
0. Wait up to 60 seconds for the process to die
0. Log an warning ("process did not stop after ...") and issue a `SIGKILL` to forcibly kill the process

I think Docker Engine currently does something like this, so we can use that behaviour as inspiration.

**Comment by jjlakis** [comment]
+1. `SIGKILL` lefts everything including mounts, child processes etc. 

> 0. Send process SIGTERM
> 1. Wait up to 60 seconds for the process to die
> 2. Log an warning ("process did not stop after ...") and issue a SIGKILL to forcibly kill the process

Looks good, but I think we should use `Timeout` field from `StopContainerRequest` as a time to wait before sending `SIGKILL`. Unless someone has an another idea to catch this value.

**Comment by jawnsy** [comment]
Also relevant to this discussion, apparently it's [configurable in the `Dockerfile`](https://docs.docker.com/engine/reference/builder/#/stopsignal). I don't have strong opinions on the exact semantics of this, but we should look around at what other container runtimes are doing.

**Comment by rhatdan** [comment]
Should the signal be configurable.  Docker supports the STOPSIGNAL.  Systemd as pid 1 in a container requires a weird signal,  SIGRTMIN+3.

**Comment by mrunalp** [comment]
@rhatdan We will have to read if from the image config. AFAIK, kubernetes doesn't pass a specific signal over CRI.

**Comment by rhatdan** [comment]
That is fine, if we can at least get it from the json.

**Comment by jawnsy** [comment]
Retitled this since #305 (already merged) covers the original complaint :smile:

**Comment by runcom** [comment]
The "configure the stop signal" is just something docker only has right now. That value is embedded in the `container_config` field of an image config (it shouldn't be there in the first place). The OCI image-spec isn't using `container_config` (for obvious reasons).
This stop signal should come directly from the kubelet in the `ContainerConfig` when creating containers.

**Comment by runcom** [comment]
#539
