### ISSUE TITLE
ExecSync code path does not work with all OCI compatible runtimes

### ISSUE THREAD

**Issue by sameo** [kubernetes-incubator/cri-o#309]
The `ExecSync` code path and tests expects to be run with `runc`:

- It is only waiting for the runtime pid to get the command exit status (and does not support waiting from any other process created by the runtime).
- Negative testing are comparing the error strings with `runc` specific output.

As a consequence CRI-O `ExecSync` fails on e.g. Clear Containers.

**Comment by sameo** [comment]
@runcom @mrunalp  I'm currently working on fixing this one, so please assign it to me.

**Comment by mrunalp** [comment]
@sameo Thanks!
