### ISSUE TITLE
Separate IDs and names for containers

### ISSUE THREAD

**Issue by mrunalp** [kubernetes-incubator/cri-o#31]
We should generate IDs for pods/containers as primary keys instead of their names.

**Comment by runcom** [comment]
What would happen if someone tries to create twice a container named the same? But probably different config?

**Comment by runcom** [comment]
We will probably need a lookup table for names to tell fastly it's duplicate and stuff like these..

**Comment by mrunalp** [comment]
Yeah the namespace would be different in meta.
