### ISSUE TITLE
"make install" fails if go-md2man was not installed

### ISSUE THREAD

**Issue by jawnsy** [kubernetes-incubator/cri-o#311]
The build runs fine (though doesn't generate docs) if `go-md2man` is not installed:

```
$ make
make -C conmon
make[1]: Entering directory `/home/jawnsy/projects/cri-o/conmon'
make[1]: `conmon' is up to date.
make[1]: Leaving directory `/home/jawnsy/projects/cri-o/conmon'
make -C pause
make[1]: Entering directory `/home/jawnsy/projects/cri-o/pause'
make[1]: `pause' is up to date.
make[1]: Leaving directory `/home/jawnsy/projects/cri-o/pause'
which: no go-md2man in (/usr/local/bin:/bin)
ERROR: go-md2man not found. Consider 'make install.tools' target
make: *** [docs/ocid.conf.5] Error 1
```

So far, so good. But if you then `make install`, it fails because the documentation isn't present. Either we should turn `go-md2man` into a hard error (it's already an error, though the wording of the message implies it's optional), or we should make it truly optional. Personally I'd prefer the latter, but I understand that may make testing more difficult.

```
$ sudo make install
install -D -m 755 kpod /usr/local/bin/kpod
install -D -m 755 ocid /usr/local/bin/ocid
install -D -m 755 ocic /usr/local/bin/ocic
install -D -m 755 conmon/conmon /usr/local/libexec/ocid/conmon
install -D -m 755 pause/pause /usr/local/libexec/ocid/pause
install -d -m 755 /usr/local/share/man/man{1,5,8}
install -m 644 docs/kpod.1 docs/kpod-launch.1 -t /usr/local/share/man/man1
install: cannot stat ‘docs/kpod.1’: No such file or directory
install: cannot stat ‘docs/kpod-launch.1’: No such file or directory
make: *** [install] Error 1
```

**Comment by runcom** [comment]
I'm fine having an hard error which exists make if go-md2man isn't available

**Comment by jawnsy** [comment]
Yeah, it's a hard error, but I guess it happens to be at the end. I mostly just meant the word "Consider" makes it sound like it's just a recommended dependency, rather than a required dependency

**Comment by runcom** [comment]
mmm to me it's a required dependency, no? `make` should run fine the whole making process (think about `go` itself not being available) and so, we need go-md2bin to always be present on `make` (`make binaries` is another story maybe).
I don't really have a strong opinion here to be honest...it's like checking if `go` is installed before running the `make` process..

**Comment by runcom** [comment]
should be fixed according to https://github.com/kubernetes-incubator/cri-o/pull/320#issuecomment-273314980
