### ISSUE TITLE
Generate bash completions for kpod

### ISSUE THREAD

**Issue by jawnsy** [kubernetes-incubator/cri-o#312]
There are some bash completions checked in for kpod (cri-o/completions/bash/kpod), however, I suggest using the [built-in completion rules](https://github.com/urfave/cli#bash-completion) for `urfave/cli` to make maintenance easier. It would have some advantages:

* For developers who have never written a bash completion (like this guy *two thumbs pointed at self*)
* Easier to keep code in sync with completions

I think this is what OpenShift origin does; for example in the `oc help` output:

```
Settings Commands:
  logout          End the current server session
  config          Change configuration files for the client
  whoami          Return information about the current session
  completion      Output shell completion code for the given shell (bash or zsh)
```

I don't know if urfave/cli can do zsh completions. I think origin uses the same library kubernetes does: https://github.com/spf13/cobra so switching to that might be an option too

**Comment by rhatdan** [comment]
I think the built in completion rules was very limited, only handled one level if it improves I say  yes, but I think for a while these will have to be hand maintained.

**Comment by rhatdan** [comment]
@mrunalp We have bash completions for kpod, so this can be closed.
