### ISSUE TITLE
Use idiomatic Go project structure and "go install" for builds

### ISSUE THREAD

**Issue by jawnsy** [kubernetes-incubator/cri-o#313]
We currently use `go build` to build. Is there any reason we couldn't use the idiomatic Go project structure?

For example:

```
export GOPATH=/home/jawnsy/projects/cri-o
mkdir $GOPATH/src/github.com/kubernetes-incubator/ && cd "$_"
git clone git@github.com:kubernetes-incubator/cri-o.git # or your fork
cd cri-o
go install github.com/kubernetes-incubator/cmd/server
```

We would, of course, modify the `Makefile` to do the same. One upside is that binaries would be built outside the VCS, so we wouldn't need to worry about accidentally checking in ocid/ocic. The install instructions for `ocic` or `kpod` could be simplified as well (e.g. something like `go get -u github.com/kubernetes-incubator/cri-o/cmd/ocic`)

I think kubernetes and origin use a special GOPATH (_output), so that's also an option we could evaluate as well. A separate build output directory makes implementing `make clean` easier: you just have to nuke that whole directory.

**Comment by jawnsy** [comment]
You're right, with `.gitignore` it's not a problem, but we have to remember to update it for new binaries (in addition to updating many of the make targets).

The main reason I mention this is because I want to run tests as: `go test github.com/kubernetes-incubator/test/integration` and that doesn't work today. It also means that you have to clone the project and use the Makefile to build (instead of using `go get` and having Go manage it all automagically).

I also noticed that if I set my GOPATH as described, `go build` fails:

```
$ echo $GOPATH
/home/jawnsy/projects/cri-o/
$ make
go build --tags "selinux seccomp  " -o ocid ./cmd/server/
cmd/server/daemon_linux.go:6:2: cannot find package "github.com/Sirupsen/logrus" in any of:
	/usr/lib/golang/src/github.com/Sirupsen/logrus (from $GOROOT)
	/home/jawnsy/projects/cri-o/src/github.com/kubernetes-incubator/cri-o/vendor/src/github.com/Sirupsen/logrus (from $GOPATH)
```

I'm not sure why it's looking under `vendor/src` either... I thought vendored deps go right under `vendor`? If you try to `go install` it blows up (e.g. since it's looking for vendor/github.com/BurntSushi/toml instead of vendor/src/...):

```
$ go install github.com/kubernetes-incubator/cri-o/cmd/server
server/config.go:7:2: cannot find package "github.com/BurntSushi/toml" in any of:
	/home/jawnsy/projects/cri-o/src/github.com/kubernetes-incubator/cri-o/vendor/github.com/BurntSushi/toml (vendor tree)
...
```

Then if you try `go test` (after I added onsi/ginkgo to hack/vendor and ran the script):

```
$ go test github.com/kubernetes-incubator/cri-o/test/integration
# github.com/kubernetes-incubator/cri-o/test/integration
test/integration/integration_test.go:4:2: cannot find package "github.com/onsi/ginkgo" in any of:
	/home/jawnsy/projects/cri-o/src/github.com/kubernetes-incubator/cri-o/vendor/github.com/onsi/ginkgo (vendor tree)
```

Argh! :smile:

**Comment by jawnsy** [comment]
Dan Mace also pointed out that using `go install` means that we will use a package cache, rather than clean-building every time. This should speed up builds, especially when incremental changes are made.

I also noticed suggest renaming `client` and `server` to `ocic` and `ocid` accordingly, as they're not currently `go get`'able

Sidenote, I wonder if changing to this pattern would also fix this problem:

```
$ go get -u github.com/kubernetes-incubator/cri-o/cmd/client
# github.com/kubernetes-incubator/cri-o/cmd/client
./container.go:69: cannot use conn (type *"google.golang.org/grpc".ClientConn) as type *"k8s.io/kubernetes/vendor/google.golang.org/grpc".ClientConn in argument to runtime.NewRuntimeServiceClient
./container.go:116: cannot use conn (type *"google.golang.org/grpc".ClientConn) as type *"k8s.io/kubernetes/vendor/google.golang.org/grpc".ClientConn in argument to runtime.NewRuntimeServiceClient
./container.go:143: cannot use conn (type *"google.golang.org/grpc".ClientConn) as type *"k8s.io/kubernetes/vendor/google.golang.org/grpc".ClientConn in argument to runtime.NewRuntimeServiceClien
```

**Comment by jawnsy** [comment]
@mrunalp @runcom @cyphar Would you consider a PR for this? I'd be happy to work on one if you're open to making this change, or at least evaluating it. It does mean that it'll be a little more annoying to get started with this, since it requires creating an appropriate `GOPATH` first (e.g. `mkdir -p cri-o/src/github.com/kubernetes-incubator && cd $_ && git clone ...` as explained above)

But I think it's worth it, and should improve performance of incremental builds.

We could just try it and time before/after to see if the package cache helps?

**Comment by mrunalp** [comment]
I see no harm in exploring it.
