### ISSUE TITLE
Promote DefaultConfig to server/config.go instead of cmd/server/config.go

### ISSUE THREAD

**Issue by jawnsy** [kubernetes-incubator/cri-o#315]
I'm working on creating an embedded test server for integration tests (so that we don't have to shell out to ocid).

OpenShift Origin [starts an embedded etcd server and origin master](https://github.com/openshift/origin/blob/master/test/integration/api_paths_test.go#L20) (with other options, like only starting the API server) during tests. I think the idea is [borrowed from kubernetes](https://github.com/kubernetes/kubernetes/blob/master/test/integration/scheduler/scheduler_test.go#L54). This makes it easier to start up/tear down the daemon, and since it's fully embedded, parallel tests mean that each test runner can use its own server.

One challenge is that `cmd/server/config.go` is a `main` package, so we can't simply import it to invoke `DefaultConfig` from tests.

Therefore, I suggest promoting this function to `server/config.go` instead. I'm happy to open a PR for this if you think it makes sense.

**Comment by runcom** [comment]
Makes sense to me assuming the command still remains there right? (you want to basically move the command functionality in the server I guess). Ping @cyphar also.
