### ISSUE TITLE
Mount source directory read-only in integration tests

### ISSUE THREAD

**Issue by jawnsy** [kubernetes-incubator/cri-o#323]
`make integration` runs the build in a Docker image, which mounts the source directory into the container. Some of the tests appear to be writing temporary data to some of these directories (e.g. `test/testdata/redis-image/...`), which create leave files (with root permissions) around.

If developing as a non-root user, these files cause build failures for subsequent builds (since `docker build` can't read them when sending the build context to the daemon).

```
19:12 jawnsy@frost ~/projects/cri-o/src/github.com/kubernetes-incubator/cri-o/test/testdata/redis-image $ ls -al
total 46M
drwxr-xr-x  2 root   root     35 Jan 18 18:29 .
drwxrwxr-x. 3 jawnsy jawnsy 4.0K Jan 18 18:29 ..
-rw-------  1 root   root    45M Jan 18 18:59 dir-put-blob608478832
```

The source directory should be mounted read-only, and these temporary files should be put somewhere else (e.g. `/tmp`) inside the container.

**Comment by runcom** [comment]
The reason for this is to collect artifacts from within the container (eg a test.log). The example you are giving is the one from the copyimg binary right? Why is that created by root

**Comment by jawnsy** [comment]
@runcom It's not the end of the world, but subsequent `docker build` runs will fail, because my nonprivileged user can't read the file in order to send it (as part of the build context) to the daemon. I'd suggest mounting a separate directory for test data as read-writable, with the source directory mounted as read-only, which gives us the option of not mounting the test data directory if we don't want to preserve it (it'd be written to the copy-on-write layer and be destroyed when the container goes away)

**Comment by rhatdan** [comment]
@jawnsy is this still an issue?

**Comment by jawnsy** [comment]
Haven't checked for awhile, let's assume not anymore :)
