### ISSUE TITLE
containers and pods are  not created

### ISSUE THREAD

**Issue by whatdhack** [kubernetes-incubator/cri-o#341]
Ran ocid and ocic as per the  instructions.

ocid --debug
ocic pod run --config ./test/testdata/sandbox_config.json

Error message :
Creating the pod sandbox failed: rpc error: code = 2 desc = reading pid from init pipe: EOF

The reason is the following are not created,   although the debug message falsely  claims otherwise . 

pod sandbox "67ada844bbf37b68a7dfd4c6a8cbb85426c37fe5e8622b66b6559a4d6f24a420" has work directory "/var/lib/ocid/aufs-containers/67ada844bbf37b68a7dfd4c6a8cbb85426c37fe5e8622b66b6559a4d6f24a420/userdata" 
DEBU[2017-01-26 17:55:24.124383444-08:00] pod sandbox "67ada844bbf37b68a7dfd4c6a8cbb85426c37fe5e8622b66b6559a4d6f24a420" has run directory "/var/run/containers/aufs-containers/67ada844bbf37b68a7dfd4c6a8cbb85426c37fe5e8622b66b6559a4d6f24a420/userdata" 
DEBU[2017-01-26 17:55:24.137665153-08:00] mounted container "67ada844bbf37b68a7dfd4c6a8cbb85426c37fe5e8622b66b6559a4d6f24a420" at "/var/lib/ocid/aufs/mnt/9acb6abb56f2d2d900869467b9622dccb4d0a6366b7de1a8a9d815bac0693253" 

Is it a known issue ?

**Comment by mrunalp** [comment]
@whatdhack What version of runc are you using? The latest won't work without #162. We need a version  https://github.com/opencontainers/runc/commit/47ea5c75ebeb40a317d2cfa95f9c3536c00c1eea or older.

**Comment by whatdhack** [comment]
The latest.

**Comment by whatdhack** [comment]
Seems to be working with opencontainers/runc@47ea5c7  .  Although I am not sure I understand why those directories were not created with the latest runc.  At first brush it  looks like ocid creating those directories should have nothing to do with  whether there is a valid runc or not  .  Would certainly like to understand that a bit more .  Any pointer would be appreciated .

**Comment by rhatdan** [comment]
@mrunalp I believe this is fixed and can be closed.
