### ISSUE TITLE
support multiple runtimes

### ISSUE THREAD

**Issue by runcom** [kubernetes-incubator/cri-o#346]
Placeholder till upstream https://github.com/kubernetes/kubernetes/pull/40662#event-940637569 is figured out. I'll be working on this.

**Comment by mrunalp** [comment]
As upstream pointed out, networking maybe tricky here. @sameo do you know if we can have a clearcontainer and runc pod using the same CNI plugin be able to reach each other?

**Comment by sameo** [comment]
@mrunalp I can't speak for other hypervisor based runtimes, but with the default CNI plugins a runc pod and a Clear Containers one would be able to reach each others.
In that regard CNI is actually a lot saner than e.g. CNM because it returns a complete netns configuration and it's up to the runtime implementation to bridge it transparently to whatever networking model it uses. With Clear Containers we bridge the CNI created interfaces with QEMU at the L2 level, so it's pretty much transparent and it can definitely reach runc created pods.

**Comment by mrunalp** [comment]
@sameo Nice :) That will surely help with mixed runtimes!

**Comment by rhatdan** [comment]
Sounds good, but most workloads probably do not have to communicate.  Looking to use kvm containers for running untrusted commands like users builds.

**Comment by feiskyer** [comment]
We could support runtime choosing by pod annotations, e.g. `runtime.ocid.kubernetes.io=runc|clearcontainer|runv`. And networking should be ok for those runtimes for bridge cni network plugin. 

Some potential problems:

- hypervisor based runtimes do not support host-networking
- hypervisor based runtimes may not support all cni plugins

I think ocid should report an error on such cases.

**Comment by jjlakis** [comment]
+1 for choosing by pod annotations. BTW. It seems to be a good place to mention, that there's a solution to run different runtimes (by different I mean runtimes with different "shims", for example, docker and runc+cor) on single node - https://github.com/Mirantis/virtlet/blob/master/docs/criproxy.md

**Comment by cyphar** [comment]
One thing that needs to be considered (especially for projects like Atomic, Kubic and CoreOS) is that an upgrade from one cluster type to another needs to be handled in a fairly smooth way. It looks like the upstream PR was closed, but I would like to know what the intended upgrade process would be.

For Kubic/CaaSP, we would try to drain each node (still running on Docker) and then reboot into using `cri-o`. But the important thing to note is that using annotations would mean that you couldn't upgrade like that.

**Comment by feiskyer** [comment]
> For Kubic/CaaSP, we would try to drain each node (still running on Docker) and then reboot into using cri-o. But the important thing to note is that using annotations would mean that you couldn't upgrade like that.

Why couldn't upgrade by drain? Annotations are part of pod spec, it doesn't change because of restarting or recreating.

**Comment by cyphar** [comment]
@feiskyer Sorry, you currently could update by drain, but if we start making it so that you have annotations set on Pods to specify what runtime to use then I'm wondering what the upgrade process is going to be (can you gradually change annotations of a set of Pods under a replication controller or similar?).

**Comment by sameo** [comment]
@feiskyer 

> Some potential problems:
    hypervisor based runtimes do not support host-networking

With k8s running some of its components (e.g. kube-proxy) as privileged containers with host networking access, how do you guys plan to support that with runV ?

**Comment by feiskyer** [comment]
> can you gradually change annotations of a set of Pods under a replication controller or similar?

@cyphar I mean set the annotations on pod template in the rc spec, so each pod created by rc will carry the annotation.

> Out of curiosity: with k8s running some of its components (e.g. kube-proxy) as privileged containers with host networking access, how do you guys plan to support that with runV ?

runV doesn't support host networking, that why we need multiple runtimes, e.g. switch to runc for host-networking pods.

**Comment by cyphar** [comment]
@feiskyer 

> @cyphar I mean set the annotations on pod template in the rc spec, so each pod created by rc will carry the annotation.

Yeah, I thought so. So we need to be careful with making it impossible for people to switch a cluster to a different runtime without rewriting all of their RC templates (and then doing a blue-green two switch RCs).

**Comment by rhatdan** [comment]
@sameo @cyphar We support multiple runtimes so can this be closed?
