### ISSUE TITLE
bump c/image, c/storage, image-spec

### ISSUE THREAD

**Issue by runcom** [kubernetes-incubator/cri-o#347]
Just a placeholder issue since we changed a lot in there and CRI-O needs to pick up those changes, above all:

https://github.com/opencontainers/image-spec/pull/544
https://github.com/containers/image/pull/232

and many more.

**Comment by runcom** [comment]
anyone want to take a stab at this? :angel: @jawnsy maybe? :smile:

**Comment by jawnsy** [comment]
Sure, can give this a try. Just a matter of updating dependencies & running `dep`, right? And re-testing, of course

**Comment by runcom** [comment]
> Sure, can give this a try. Just a matter of updating dependencies & running dep, right?

yup!

**Comment by runcom** [comment]
we're pretty ok with this at this point I guess.
