### ISSUE TITLE
CreateContainer: invalid checksum digest format

### ISSUE THREAD

**Issue by jjlakis** [kubernetes-incubator/cri-o#361]
To reproduce:
1. Start latest `ocid` locally 
2.  Ensure you **don't have** `redis` image pulled:
```
$ sudo ocic image list
ID: b4e147b184614008974d9dbb0ad7874636bd207cde0d414819701e4564dcccd1
Tag: docker.io/kubernetes/pause:latest
Tag: kubernetes/pause
Tag: docker.io/kubernetes/pause
```
3. Run sandbox using test config:
```
$ sudo ocic pod run --config test/testdata/sandbox_config.json
52a28e732c1387764653fadae1d7a44f64643d79404ee725e6be82dca791e74a
```
4. Try to run `redis` container using test config:
```
$ sudo ocic ctr create --pod 52a28e732c1387764653fadae1d7a44f64643d79404ee725e6be82dca791e74a --config test/testdata/container_redis.json
```

What I see:
```
Creating container failed: rpc error: code = 2 desc = invalid checksum digest format
```

What is expected:
Container created successfully and image is pulled.

If image is pulled before - container is starting and everything is fine. I'm not sure we want user to pull image before starting container, but even if we want - this is an inadequate error.

**Comment by runcom** [comment]
That's how the CRI behaves I guess, as in, it first call `PullImage` and only after that it can start the container.

**Comment by jjlakis** [comment]
> That's how the CRI behaves I guess, as in, it first call PullImage and only after that it can start the container.

At least kubelet is doing this, looking for ImageList first. So, IMO we should return error  like "you have to pull the image first" instead of this random message.

**Comment by runcom** [comment]
> At least kubelet is doing this, looking for ImageList first. So, IMO we should return error like "you have to pull the image first" instead of this random message.

:+1: right

**Comment by runcom** [comment]
@nalind could you take a look at this?
