### ISSUE TITLE
How to pull image behind proxy

### ISSUE THREAD

**Issue by gouyang** [kubernetes-incubator/cri-o#372]
My server could not reach gcr.io, how to configure proxy to pull images?

**Comment by mrunalp** [comment]
@nalind @runcom could you help with this question?

**Comment by runcom** [comment]
containers/image is reading environment variables for proxies (as Docker does). You should be able to set HTTP_PROXY and the like accordingly and cri-o should pull images just fine.

**Comment by runcom** [comment]
closing this as I replied above - feel free to comment if it's not working for you

**Comment by schmitch** [comment]
@runcom sorry to interfere in this old issue. however I think just using `HTTP_PROXY` is sometimes not suitable. In Docker http_proxy get's passed to docker which means that my whole kubernetes traffic would go through the proxy.

cri-o should make it better and have registry_http_proxy and registry_https_proxy to only proxy image pulls.

**Comment by l0nax** [comment]
Any Updates about Registry Mirrors/ Proxies?

**Comment by haircommander** [comment]
Yes, CRI-O's image management library containers/image now supports registry mirroring! I don't have an easy pointer to the documentation other than https://github.com/containers/image/blob/master/registries.conf

**Comment by haircommander** [comment]
@vrothberg @mtrmac do you have any other resources?

**Comment by vrothberg** [comment]
@rhatdan and @QiWang19 are currently working on a new configuration file that can be shared by CRI-O, Podman, etc. One idea of that config was to split the logic of http_proxies (e.g., pulling, container, etc.). I think that a pull-only proxy setting belongs in `/etc/containers/registries.conf` but I don't know if there's a decision.

**Comment by etegan** [comment]
> Yes, CRI-O's image management library containers/image now supports registry mirroring! I don't have an easy pointer to the documentation other than https://github.com/containers/image/blob/master/registries.conf

From which version of cri-o is this supported? From what I can see it is version 2 of the registries.conf format that has this feature.

**Comment by rhatdan** [comment]
It is supported on OpenShift 4.2.  @umohnani8 @mrunalp @haircommander What is the version of CRI-O for that release?

**Comment by nalind** [comment]
OpenShift 4.2 is based on Kubernetes 1.14, so it uses CRI-O 1.14.
