### ISSUE TITLE
Can I use minikube instead of using local-up-cluster.sh ?

### ISSUE THREAD

**Issue by vbmade2000** [kubernetes-incubator/cri-o#375]
I was not able to setup Kubernetes using local-up-cluster.sh. Can I use minikube to setup local cluster ?

**Comment by runcom** [comment]
I never tested that, would be nice to find out.

**Comment by vbmade2000** [comment]
Sure. I would try that.

**Comment by mzylowski** [comment]
What problem you find with local-up-cluster.sh ? Can you elaborate?

**Comment by vbmade2000** [comment]
@mzylowski Sure. Following is a trace.
[vbmade2000@localhost hack]$ ./local-up-cluster.sh 
WARNING : This script MAY be run as root for docker socket / iptables functionality; if failures occur, retry as root.
make: Entering directory '/home/vbmade2000/Documents/Projects/src/k8s.io/kubernetes'
make[1]: Entering directory '/home/vbmade2000/Documents/Projects/src/k8s.io/kubernetes'
+++ [0228 02:34:27] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [0228 02:34:28] Generating bindata:
    test/e2e/generated/gobindata_util.go
~/Documents/Projects/src/k8s.io/kubernetes ~/Documents/Projects/src/k8s.io/kubernetes/test/e2e/generated
~/Documents/Projects/src/k8s.io/kubernetes/test/e2e/generated
+++ [0228 02:34:29] Building go targets for linux/amd64:
    cmd/libs/go2idl/deepcopy-gen
+++ [0228 02:34:37] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [0228 02:34:37] Generating bindata:
    test/e2e/generated/gobindata_util.go
~/Documents/Projects/src/k8s.io/kubernetes ~/Documents/Projects/src/k8s.io/kubernetes/test/e2e/generated
~/Documents/Projects/src/k8s.io/kubernetes/test/e2e/generated
+++ [0228 02:34:38] Building go targets for linux/amd64:
    cmd/libs/go2idl/defaulter-gen
+++ [0228 02:34:43] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [0228 02:34:43] Generating bindata:
    test/e2e/generated/gobindata_util.go
~/Documents/Projects/src/k8s.io/kubernetes ~/Documents/Projects/src/k8s.io/kubernetes/test/e2e/generated
~/Documents/Projects/src/k8s.io/kubernetes/test/e2e/generated
+++ [0228 02:34:43] Building go targets for linux/amd64:
    cmd/libs/go2idl/conversion-gen
+++ [0228 02:34:54] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [0228 02:34:54] Generating bindata:
    test/e2e/generated/gobindata_util.go
~/Documents/Projects/src/k8s.io/kubernetes ~/Documents/Projects/src/k8s.io/kubernetes/test/e2e/generated
~/Documents/Projects/src/k8s.io/kubernetes/test/e2e/generated
+++ [0228 02:34:55] Building go targets for linux/amd64:
    cmd/libs/go2idl/openapi-gen
make[1]: Leaving directory '/home/vbmade2000/Documents/Projects/src/k8s.io/kubernetes'
+++ [0228 02:35:06] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [0228 02:35:06] Generating bindata:
    test/e2e/generated/gobindata_util.go
~/Documents/Projects/src/k8s.io/kubernetes ~/Documents/Projects/src/k8s.io/kubernetes/test/e2e/generated
~/Documents/Projects/src/k8s.io/kubernetes/test/e2e/generated
+++ [0228 02:35:06] Building go targets for linux/amd64:
    cmd/kubectl
    cmd/hyperkube
    vendor/k8s.io/kube-aggregator
+++ [0228 02:35:07] +++ Warning: stdlib pkg with cgo flag not found.
+++ [0228 02:35:07] +++ Warning: stdlib pkg cannot be rebuilt since /usr/lib/golang/pkg is not writable by vbmade2000
+++ [0228 02:35:07] +++ Warning: Make /usr/lib/golang/pkg writable for vbmade2000 for a one-time stdlib install, Or
+++ [0228 02:35:07] +++ Warning: Rebuild stdlib using the command 'CGO_ENABLED=0 go install -a -installsuffix cgo std'
+++ [0228 02:35:07] +++ Falling back to go build, which is slower
    **go build k8s.io/kubernetes/cmd/kube-controller-manager/app: /usr/lib/golang/pkg/tool/linux_amd64/compile: signal: killed
!!! [0228 02:50:40] Call tree:
!!! [0228 02:50:40]  1: /home/vbmade2000/Documents/Projects/src/k8s.io/kubernetes/hack/lib/golang.sh:742 kube::golang::build_binaries_for_platform(...)
!!! [0228 02:50:40]  2: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0228 02:50:40] Call tree:
!!! [0228 02:50:40]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0228 02:50:40] Call tree:
!!! [0228 02:50:41]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
Makefile:89: recipe for target 'all' failed
make: *** [all] Error 1
make: Leaving directory '/home/vbmade2000/Documents/Projects/src/k8s.io/kubernetes'
!!! Error in ./local-up-cluster.sh:152
  Error in ./local-up-cluster.sh:152. 'make -C "${KUBE_ROOT}" WHAT="cmd/kubectl cmd/hyperkube vendor/k8s.io/kube-aggregator"' exited with status 2
Call stack:
  1: ./local-up-cluster.sh:152 main(...)
Exiting with status 1

I am myself not a Kubernetes user so can't figure out what is happening here.

**Comment by jawnsy** [comment]
Are you using the golang package from Fedora? Or else where did your package come from? I ask because of these messages:

```
+++ [0228 02:35:07] +++ Warning: stdlib pkg with cgo flag not found.
+++ [0228 02:35:07] +++ Warning: stdlib pkg cannot be rebuilt since /usr/lib/golang/pkg is not writable by vbmade2000
+++ [0228 02:35:07] +++ Warning: Make /usr/lib/golang/pkg writable for vbmade2000 for a one-time stdlib install, Or
+++ [0228 02:35:07] +++ Warning: Rebuild stdlib using the command 'CGO_ENABLED=0 go install -a -installsuffix cgo std'
```

Things seem to fall back to using `go build`, though it notes that it's slower (versus `go install`, which caches compiled packages for subsequent builds):

```
+++ [0228 02:35:07] +++ Falling back to go build, which is slower
**go build k8s.io/kubernetes/cmd/kube-controller-manager/app: /usr/lib/golang/pkg/tool/linux_amd64/compile: signal: killed
```

 I can only guess that `signal: killed` means that the build ran out of memory - how much memory do you have on your system?

**Comment by vbmade2000** [comment]
@jawnsy yes I have installed golang package from fedora. I am using fedora now. I use 2 GB memory with 2 processor core for VM.

**Comment by jawnsy** [comment]
Are you running rawhide or the latest stable? If on rawhide, can you try running this command: `GOPATH="" go list -f '{{ if .Stale }} {{ .ImportPath }} {{ .StaleReason }} {{ end }}' ...` (the "..." is necessary too)

If you see output saying "build ID mismatch", then try installing `golang-tests` (it was a packaging issue, which has probably been resolved by now)

You will need more memory for `go build` though. Can you increase the memory available to your VM? Alternately, you can try reducing to 1 core (I think go will compile in parallel, and will use as many processes as there are CPUs, so that only leaves 1 GB per process)

I use a 4GB VM for building cri-o (Kubernetes probably needs even more; for OpenShift I use 8GB + some swap, on a 2-core system). This is just due to the large size of the codebase, unfortunately.

There may be more ideas here: https://github.com/kubernetes/kubernetes/issues/11852

**Comment by vbmade2000** [comment]
I use Fedora 25. Following is an output.

```
[vbmade2000@localhost ~]$ cat /etc/os-release 
NAME=Fedora
VERSION="25 (Workstation Edition)"
ID=fedora
VERSION_ID=25
PRETTY_NAME="Fedora 25 (Workstation Edition)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:25"
HOME_URL="https://fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=25
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=25
PRIVACY_POLICY_URL=https://fedoraproject.org/wiki/Legal:PrivacyPolicy
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

**Comment by vbmade2000** [comment]
Yes I can try increasing memory up to 4 GB. Let me try that after increasing memory.

**Comment by jawnsy** [comment]
OK, that's good. Blank means that the package cache is correct. I don't know if there's other dependencies that need to be installed for `cgo` (I currently build origin/kubernetes on separate systems from cri-o). Hopefully more memory and/or reducing build jobs resolves the issue.

**Comment by vbmade2000** [comment]
Yes hope so. I would try with minikiube otherwise. I think there should be a separate script which can build development environment for this project :)

**Comment by feiskyer** [comment]
https://github.com/kubernetes/kubernetes/pull/38975 is adding `make test-e2e-minikube`, but I don't think it will include cri-o inside.

**Comment by vbmade2000** [comment]
@jawnsy Looks like increasing memory worked. Following is an output.
```
[vbmade2000@localhost hack]$ sudo ./local-up-cluster.sh 
[sudo] password for vbmade2000: 
make: Entering directory '/home/vbmade2000/Documents/Projects/src/k8s.io/kubernetes'
make[1]: Entering directory '/home/vbmade2000/Documents/Projects/src/k8s.io/kubernetes'
make[1]: Leaving directory '/home/vbmade2000/Documents/Projects/src/k8s.io/kubernetes'
+++ [0301 22:06:01] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [0301 22:06:01] Generating bindata:
    test/e2e/generated/gobindata_util.go
/home/vbmade2000/Documents/Projects/src/k8s.io/kubernetes /home/vbmade2000/Documents/Projects/src/k8s.io/kubernetes/test/e2e/generated
/home/vbmade2000/Documents/Projects/src/k8s.io/kubernetes/test/e2e/generated
+++ [0301 22:06:01] Building go targets for linux/amd64:
    cmd/kubectl
    cmd/hyperkube
    vendor/k8s.io/kube-aggregator
make: Leaving directory '/home/vbmade2000/Documents/Projects/src/k8s.io/kubernetes'
Kubelet cgroup driver defaulted to use: cgroupfs
API SERVER insecure port is free, proceeding...
API SERVER secure port is free, proceeding...
Failed to successfully run 'cfssl', please verify that cfssl and cfssljson are in $PATH.
Hint: export PATH=$PATH:$GOPATH/bin; go get -u github.com/cloudflare/cfssl/cmd/...
```

Still it is not able to find cfssl and cfssljson binaries while both are available on $PATH.

```
[vbmade2000@localhost hack]$ cfssl
No command is given.
Usage:
Available commands:
	scan
	bundle
	version
	gencert
	gencrl
	revoke
	genkey
	ocsprefresh
	ocspsign
	print-defaults
	certinfo
	ocspserve
	selfsign
	info
	sign
	serve
	ocspdump
Top-level flags:
  -allow_verification_with_non_compliant_keys
    	Allow a SignatureVerifier to use keys which are technically non-compliant with RFC6962.

```

**Comment by jawnsy** [comment]
@vbmade2000 Woohoo! Progress! I have no idea what the `cfssl` problem could be, though :/

**Comment by vbmade2000** [comment]
@jawnsy yeah :) 
cfssl is some library from cloudflare for PKI.

**Comment by jawnsy** [comment]
Oh, wait, I just noticed you're running local-up-cluster with sudo but you checked cfssl as your normal user. Can you try `sudo -E` (to preserve your PATH) or sudo go get cfssl?

**Comment by vbmade2000** [comment]
Tried both approach you suggested but none of them worked.
Removed cfssl check and started api server with secure-port=0 option. Looks like it is running. Working on CNI now :)

**Comment by vbmade2000** [comment]
Failing to run OCID. Following is a trace.

```
ocid.service - Open Container Initiative Daemon
   Loaded: loaded (/etc/systemd/system/ocid.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2017-03-03 02:15:13 CST; 58s ago
     Docs: https://github.com/kubernetes-incubator/cri-o
  Process: 87140 ExecStart=/usr/bin/ocid $OCID_STORAGE_OPTIONS $OCID_NETWORK_OPTIONS ExecReload=/bin/kill -s HUP $MAINPID (code=exited, status=203/EXEC)
 Main PID: 87140 (code=exited, status=203/EXEC)

Mar 03 02:15:13 localhost.localdomain systemd[1]: Starting Open Container Initiative Daemon...
Mar 03 02:15:13 localhost.localdomain systemd[1]: ocid.service: Main process exited, code=exited, status=203/EXEC
Mar 03 02:15:13 localhost.localdomain systemd[1]: Failed to start Open Container Initiative Daemon.
Mar 03 02:15:13 localhost.localdomain systemd[1]: ocid.service: Unit entered failed state.
Mar 03 02:15:13 localhost.localdomain systemd[1]: ocid.service: Failed with result 'exit-code'.
~       
```

**Comment by mrunalp** [comment]
@vbmade2000 Can you try running it manually with `ocid --debug` ?

**Comment by vbmade2000** [comment]
@mrunalp Here is the output of ocid --debug

```
[root@localhost cri-o]# ./ocid --debug
DEBU[2017-03-05 10:34:18.297006911-06:00] [zfs] zfs command is not available: exec: "zfs": executable file not found in $PATH 
DEBU[2017-03-05 10:34:18.299602609-06:00] devicemapper: driver version is 4.35.0       
DEBU[2017-03-05 10:34:18.300123597-06:00] devmapper: Generated prefix: container-253:0-288037 
DEBU[2017-03-05 10:34:18.300159069-06:00] devmapper: Checking for existence of the pool container-253:0-288037-pool 
DEBU[2017-03-05 10:34:18.300284338-06:00] devmapper: Pool doesn't exist. Creating it.  
DEBU[2017-03-05 10:34:18.300360404-06:00] devmapper: Creating loopback file /var/lib/ocid/devicemapper/devicemapper/data for device-manage use 
DEBU[2017-03-05 10:34:18.320124444-06:00] devmapper: Creating loopback file /var/lib/ocid/devicemapper/devicemapper/metadata for device-manage use 
WARN[2017-03-05 10:34:18.378235859-06:00] devmapper: Usage of loopback devices is strongly discouraged for production use. Please use `--storage-opt dm.thinpooldev`. 
DEBU[2017-03-05 10:34:18.378293882-06:00] devmapper: Failed to read /var/lib/ocid/devicemapper/metadata/base with err: open /var/lib/ocid/devicemapper/metadata/base: no such file or directory 
DEBU[2017-03-05 10:34:18.378306322-06:00] devmapper: Initializing base device-mapper thin volume 
DEBU[2017-03-05 10:34:18.380797137-06:00] devicemapper: CreateDevice(poolName=/dev/mapper/container-253:0-288037-pool, deviceID=1) 
DEBU[2017-03-05 10:34:18.381860888-06:00] devmapper: Registering device (id 1) with FS size 10737418240 
DEBU[2017-03-05 10:34:18.381896281-06:00] devmapper: registerDevice(1, )               
DEBU[2017-03-05 10:34:18.391803294-06:00] devmapper: Creating filesystem on base device-mapper thin volume 
DEBU[2017-03-05 10:34:18.391832436-06:00] devmapper: activateDeviceIfNeeded()          
INFO[2017-03-05 10:34:18.490585109-06:00] devmapper: Creating filesystem xfs on device container-253:0-288037-base 
INFO[2017-03-05 10:34:18.531463671-06:00] devmapper: Successfully created filesystem xfs on device container-253:0-288037-base 
DEBU[2017-03-05 10:34:18.539228666-06:00] devmapper: activateDeviceIfNeeded()          
DEBU[2017-03-05 10:34:18.558616074-06:00] devmapper: UUID for device: /dev/mapper/container-253:0-288037-base is:2a2bc394-8694-4b36-9add-74559174bde2 
DEBU[2017-03-05 10:34:18.559442711-06:00] devmapper: deactivateDevice()                
DEBU[2017-03-05 10:34:18.559527322-06:00] devmapper: removeDevice START(container-253:0-288037-base) 
DEBU[2017-03-05 10:34:18.585224914-06:00] devmapper: removeDevice END(container-253:0-288037-base) 
DEBU[2017-03-05 10:34:18.585266264-06:00] devmapper: deactivateDevice END()            
DEBU[2017-03-05 10:34:18.604316362-06:00] sandboxes: map[]                             
DEBU[2017-03-05 10:34:18.604472452-06:00] containers: &{map[] {{0 0} 0 0 0 0}}  
```       

It is not able to find zfs command executable. Can it be the reason ?

**Comment by nikinath** [comment]
I faced a similar problem and was able to solve it by placing $GOPATH in root path (not the ideal case, I agree). Please see if this could help you: https://github.com/kubernetes/kubernetes/issues/3184#issuecomment-285935360

**Comment by rhatdan** [comment]
@vbmade2000 Is this still an issue.  Just trying to cleanup issues.

**Comment by vbmade2000** [comment]
@rhatdan I was not able to check for this issue due to unavailability of bandwidth. You can close it.

**Comment by rhatdan** [comment]
@mrunalp Please Close.

**Comment by jayunit100** [comment]
i think this is an issue on master b/c minikube isn't honoring any alt. container runtimes when docker isnt there, It crashes if docker isnt available.  see https://github.com/kubernetes/minikube/issues/3153

**Comment by jayunit100** [comment]
- *no, minikube is not a substitute for local up cluster *.
As an example, consider that for alternate container runtimes, minikube actually won't work (i.e. vm-driver=none will blow up if docker isnt around, but crio and other runtimes can be used with local-up-cluster, https://github.com/kubernetes-sigs/cri-o/blob/master/README.md ).  

So there is at least one use case where minikube wont be a substitute for local up cluster.

But for simplistic situations, minikube w/ vm-driver=none might work as a reasonable single node, non VM substitute for local-up-cluster.
