### ISSUE TITLE
Do we really still care about golang 1.6 tests?

### ISSUE THREAD

**Issue by rhatdan** [kubernetes-incubator/cri-o#393]
Would eliminating 1.6 tests speed up testing?

**Comment by jawnsy** [comment]
Tests run in parallel, so I don't think they cost much, but if we're OK dropping support for 1.6 then I'm in favor of eliminating tests on it. I think everything actually runs inside Docker (e.g. `make integration` does `docker build -t ocid_dev:HEAD .`) which is `FROM golang:1.7` so we're not actually getting better test coverage.

cc @mrunalp @sameo @runcom @cyphar @nalind

**Comment by nalind** [comment]
Upstream, we probably don't need to care about 1.6.
At the moment, 1.6 is the latest version of golang that we have on RHEL 7, so with my downstream hat on I'm still interested in making sure that we can build using 1.6.

**Comment by runcom** [comment]
I'm ok keeping 1.6 as long as RHEL builds with 1.6 (and drop it once we rebase to 1.7)

**Comment by rhatdan** [comment]
@runcom Hasn't RHEL moved on from GOLANG 1.6?
