### ISSUE TITLE
Image status is requested with the wrong image name

### ISSUE THREAD

**Issue by sameo** [kubernetes-incubator/cri-o#403]
When launching a k8s pod with the docker hub `sameo/nginx-kubecon` image:

```
kubectl run nginx --image=sameo/nginx-kubecon:1.0 --port=80
```
(Note we're asking for a tagged image, not a `latest` one)

 `ocid` initially pulls and stores the image as expected:

```
# ocic image status -id 4a97d18023383cecad7694a2daf8383e093ccbdd36a1f1af862db90ed8b9f340
ID: 4a97d18023383cecad7694a2daf8383e093ccbdd36a1f1af862db90ed8b9f340
Tag: docker.io/sameo/nginx-kubecon:latest
Tag: sameo/nginx-kubecon:1.0
Tag: docker.io/sameo/nginx-kubecon
Size: 180932784
```

When launching a subsequent pod with the same image, `ocid` pulls the image again. After adding some debug in `vendor/github.com/containers/storage/storage/images.go` for dumping the images map (byname and byid), I see that the problem is `ocid` is asking for a status for an image with the name being set to `docker.io/sameo/nginx-kubecon:1.0` while we stored this image with the following tags:

```
Tag: docker.io/sameo/nginx-kubecon:latest
Tag: sameo/nginx-kubecon:1.0
Tag: docker.io/sameo/nginx-kubecon
```

As a consequence, the image is pulled again.

**Comment by sameo** [comment]
cc @nalind

**Comment by mrunalp** [comment]
cc: @runcom

**Comment by runcom** [comment]
Yup I remember this issue! @nalind any idea what's happening here?

**Comment by nalind** [comment]
It looks like we're losing the `1.0` tag and adding `latest` by mistake.  My current guess is that https://github.com/nalind/cri-o/commit/e7c0e23e40098a79f822589dbed372ba58ac35cf will fix it, but I'm not completely clear on whether or not we're expected to add the `latest` tag to an image if it's not what we pulled.

**Comment by mrunalp** [comment]
@nalind I would think that we only add latest if someone asks for it. In case of latest, k8s would ask us to repull each time anyways, so it doesn't matter as much.
