### ISSUE TITLE
s.Update race

### ISSUE THREAD

**Issue by mrunalp** [kubernetes-incubator/cri-o#407]
We have a race condition in server Update() call that is easy to reproduce when running e2e tests.

**Comment by runcom** [comment]
We have those calls to prevent any unwanted state with other parties playing around with containers storage. Ideally, we could have a knob in ocid to have it started _standalone_ and not worry about external state changing (most k8s setup) would do this, and a _non-standalone_ mode where we could reload state at each server op. @mrunalp @nalind wdyt?

**Comment by sameo** [comment]
@runcom If we fix the race, we may not need those 2 modes and could keep the code simpler.

**Comment by runcom** [comment]
@sameo yeah, I discussed that with @mrunalp as well, so either locking or a new mode works for me
