### ISSUE TITLE
Missing ENV variables from the image config in the runc config.json

### ISSUE THREAD

**Issue by mrunalp** [kubernetes-incubator/cri-o#411]
While testing with httpd (https://github.com/docker-library/httpd/blob/b95f1aba991d613f971fe8c66dc23fb4d8f3e9a7/2.4/alpine/Dockerfile), I noticed that we don't set the ENV variables set in the image config. 

@nalind @runcom

**Comment by mrunalp** [comment]
Ditto for working directory.

**Comment by runcom** [comment]
closed by https://github.com/kubernetes-incubator/cri-o/pull/412
