### ISSUE TITLE
Failure during kill pod

### ISSUE THREAD

**Issue by mrunalp** [kubernetes-incubator/cri-o#438]
I saw this while testing with k8s today. I don't have a way to reproduce this yet.
```
ERROR: logging before flag.Parse: E0407 13:02:48.928305   14684 ocicni.go:245] Error deleting network: unknown FS magic on "/var/run/netns/cni-8cebcf43-76cd-ff54-f573-0c7b3f5a413b": 1021994
```

**Comment by cyphar** [comment]
So, that number is the `TMPFS_MAGIC` number. It looks like for some reason we have a tmpfs file (rather than a network namespace "file") bindmounted into `/var/run/netns`. I'm not sure what would cause it, but that looks like the bug to me.

**Comment by rhatdan** [comment]
@cyphar @mrunalp Is this still an issue?

**Comment by mrunalp** [comment]
@rhatdan I haven't seen this again. We could close it and re-open if required.

**Comment by rhatdan** [comment]
@mrunalp Lets close it.
