### ISSUE TITLE
specs.LinuxCapabilities changed

### ISSUE THREAD

**Issue by runcom** [kubernetes-incubator/cri-o#448]
Getting this warn:
```
WARN[2017-04-13 14:43:55.887380894+02:00] could not load new sandbox container 37977b72183c726b36a77626157e6d7a6de8770274b44f313aeb442788d2cd0d: json: cannot unmarshal array into Go value of type specs.LinuxCapabilities, ignoring
```
@mrunalp @cyphar

**Comment by cyphar** [comment]
Hmmm. Let me check this one out.

**Comment by cyphar** [comment]
@runcom Just to make sure, have you removed all of your old data (since this represents a schema change)?

**Comment by cyphar** [comment]
As an aside, it looks to me like this command is broken now:

```
% sudo ./ocic pod run --name sandbox0 --config test/testdata/sandbox_config.json
Creating the pod sandbox failed: rpc error: code = 11 desc = EOF
```

In particular it looks like the `userdata` directory doesn't exist:

```
DEBU[2017-04-14 00:10:26.519989057+10:00] running conmon: /usr/lib/ocid/conmon          args=[-c redhat.test.ocid-sandbox0-1-infra -r /usr/bin/crio-runc -b /var/run/containers/storage/btrfs-containers/a9871ea0c21d9c7d47f62ea77915595cc18bb3bc3211676ecd6770fd18e37330/userdata -p /var/run/containers/storage/btrfs-containers/a9871ea0c21d9c7d47f62ea77915595cc18bb3bc3211676ecd6770fd18e37330/userdata/pidfile -l /var/log/ocid/pods/a9871ea0c21d9c7d47f62ea77915595cc18bb3bc3211676ecd6770fd18e37330/a9871ea0c21d9c7d47f62ea77915595cc18bb3bc3211676ecd6770fd18e37330.log]
[conmon:i]: about to waitpid: 16581
[conmon:e]: Failed to create container: exit status 1
```

When you try to look at it:

```
% sudo ls /var/run/containers/storage/btrfs-containers/a9871ea0c21d9c7d47f62ea77915595cc18bb3bc3211676ecd6770fd18e37330/userdata
ls: cannot access '/var/run/containers/storage/btrfs-containers/a9871ea0c21d9c7d47f62ea77915595cc18bb3bc3211676ecd6770fd18e37330/userdata': No such file or directory
```

And I checked the strace logs and the reason runC is dying is because of `chdir` failing...

**Comment by runcom** [comment]
Right, I didn't, let me do that and re-test

**Comment by runcom** [comment]
> As an aside, it looks to me like this command is broken now:
> 
> % sudo ./ocic pod run --name sandbox0 --config test/testdata/sandbox_config.json
> Creating the pod sandbox failed: rpc error: code = 11 desc = EOF

@cyphar I got that as well and fixed it by just recompiling and using the latest runc master :)

**Comment by mrunalp** [comment]
I think both of you are right about 1. incompatible config from older data 2. older runc.
Please retest and let me know :)

**Comment by runcom** [comment]
yeah, removing old data fixed my issue.

**Comment by cyphar** [comment]
Oh yeah, I forgot to update runC. ;)

**Comment by mrunalp** [comment]
Can we close this?

**Comment by cyphar** [comment]
:+1: Though we should eventually add some defensive code that will tell you if you forgot to upgrade runC (runC tells you what spec version it follows). We could also do the same for `conmon`.
