### ISSUE TITLE
Cannot start a container that has stopped

### ISSUE THREAD

**Issue by gouyang** [kubernetes-incubator/cri-o#453]
Is this a bug or by design?

```
$ sudo /usr/local/bin/ocic ctr stop --id 4cd17a60cb35a373fc7de386c8fcb85759238967f6daf81251439482d51b9e1b
4cd17a60cb35a373fc7de386c8fcb85759238967f6daf81251439482d51b9e1b
$ sudo /usr/local/bin/ocic ctr start --id 4cd17a60cb35a373fc7de386c8fcb85759238967f6daf81251439482d51b9e1b
Starting the container failed: rpc error: code = 2 desc = failed to start container 4cd17a60cb35a373fc7de386c8fcb85759238967f6daf81251439482d51b9e1b: `/usr/local/bin/runc start redhat.test.ocid-podsandbox1-1-podsandbox1-redis-0` failed: exit status 1
```

In ocid --debug

```
DEBU[2017-04-17 10:30:01.689538505+08:00] StopContainerRequest &StopContainerRequest{ContainerId:4cd17a60cb35a373fc7de386c8fcb85759238967f6daf81251439482d51b9e1b,Timeout:0,} 
DEBU[2017-04-17 10:30:01.689598295+08:00] updating sandbox and container information   
closing fd 11
closing fd 5
PID 16035 exited with status 0
PID 16036 exited with status 0
DEBU[2017-04-17 10:30:01.730931240+08:00] StopContainerResponse: &StopContainerResponse{} 
DEBU[2017-04-17 10:30:09.960408191+08:00] StartContainerRequest &StartContainerRequest{ContainerId:4cd17a60cb35a373fc7de386c8fcb85759238967f6daf81251439482d51b9e1b,} 
DEBU[2017-04-17 10:30:09.960470872+08:00] updating sandbox and container information   
cannot start a container that has stopped
```

**Comment by surajssd** [comment]
I could recreate these errors

```bash
cd $GOPATH/src/github.com/kubernetes-incubator/cri-o

ocic image pull docker://redis:latest
POD_ID=$(ocic pod run --config test/testdata/sandbox_config.json)
ocic pod status --id $POD_ID

CONTAINER_ID=$(ocic ctr create --pod $POD_ID --config test/testdata/container_redis.json)

ocic ctr start --id $CONTAINER_ID
ocic ctr status --id $CONTAINER_ID

ocic ctr stop --id $CONTAINER_ID
ocic ctr status --id $CONTAINER_ID

ocic ctr start --id $CONTAINER_ID
ocic ctr status --id $CONTAINER_ID
```

this one looks fine

```bash
cat /var/log/ocid/pods/$POD_ID/$CONTAINER_ID.log
```

**Comment by surajssd** [comment]
This comes from the code in runc [here](https://github.com/opencontainers/runc/blob/4815f67a5fae118f8c74178ac14b94f10a3f0b76/start.go#L36). I think it is legitimate behavior.

**Comment by gouyang** [comment]
A stopped object usually means can be started late, the current situation should and must be modified in my opinion.

**Comment by cyphar** [comment]
I just checked the spec (https://github.com/opencontainers/runtime-spec/blob/master/runtime.md#start) and it looks like this behaviour is not mandated (either way) by the runtime-spec. In addition, it looks like we've always done things that way after the `create`-`start` split.

@crosbymichael WDYT? Should we enable `start` to basically restart the container? It's a bit ugly because we'd have to basically do `delete`+`create`+`start` in one go -- which would not be pretty IMO.

**Comment by cyphar** [comment]
But more importantly @gouyang the important question is whether the CRI expects this to work as you describe (`cri-o` is just meant to be there for the CRI's benefit, you shouldn't really be using it as a user). If it does we could implement it in `cri-o`.

**Comment by mrunalp** [comment]
CRI doesn't expect to be able to start a stopped container. kubelet will spawn another container if for some reason the container dies.

**Comment by gouyang** [comment]
I'm fine if CRI doesn't expect to start a stopped container, just need an issue to track this situation.

**Comment by runcom** [comment]
Mmm not sure why this needs an issue if CRI is expecting this behavior

**Comment by cyphar** [comment]
@gouyang But cri-o is a CRI implementation -- if the CRI doesn't expect some behaviour we aren't meant to implement it (especially since there are still parts of the CRI we do need to implement -- so we would be better served if we work on those).

**Comment by gouyang** [comment]
1. There is no document about this in this project.
2. The CRI spec https://github.com/opencontainers/runtime-spec/blob/master/runtime.md#start doesn't mention what if to start a stopped container.
3. The error looks not useful in ocic, can we improve the error message just like ocid `cannot start a container that has stopped`?

```
$ sudo /usr/local/bin/ocic ctr stop --id 4cd17a60cb35a373fc7de386c8fcb85759238967f6daf81251439482d51b9e1b
4cd17a60cb35a373fc7de386c8fcb85759238967f6daf81251439482d51b9e1b
$ sudo /usr/local/bin/ocic ctr start --id 4cd17a60cb35a373fc7de386c8fcb85759238967f6daf81251439482d51b9e1b
Starting the container failed: rpc error: code = 2 desc = failed to start container 4cd17a60cb35a373fc7de386c8fcb85759238967f6daf81251439482d51b9e1b: `/usr/local/bin/runc start redhat.test.ocid-podsandbox1-1-podsandbox1-redis-0` failed: exit status 1
```

And I think sooner or later someone will have the question like me, if the documentation is not enough, an issue and the discussion in the issue helps.

**Comment by mrunalp** [comment]
crioctl/ocic is mainly a debugging tool. cri-o works fine with k8s.
