### ISSUE TITLE
Rename binaries

### ISSUE THREAD

**Issue by mrunalp** [kubernetes-incubator/cri-o#479]
We should rename the binaries from ocid to criod (suggestions?) and ocic to cricli (suggestions?)

**Comment by sameo** [comment]
Should we continue using ocic or start looking at cri-tools for the client command:

https://github.com/kubernetes-incubator/cri-tools/tree/master/cmd/crictl

**Comment by mrunalp** [comment]
@sameo Yes, we could start looking into switching to cri-tools. Maybe we can do that for the 0.4 release.

**Comment by jawnsy** [comment]
Just wanted to link @rhatdan's [comment](https://github.com/kubernetes-incubator/cri-o/issues/476#issuecomment-298225174) from #476:

> We had better move forward with the rename of the package and the daemon before we get to far with packaging.
>
> I suggest
> package name crio.
> Daemon criod
> Client cri
>
> I can prepare a patch for this change if it is agreed upon.
