### ISSUE TITLE
configure containers registries in CRI-O

### ISSUE THREAD

**Issue by runcom** [kubernetes-incubator/cri-o#494]
Right now, if you pass an image name unqualified (meaning, with not hostname/port in it, e.g. `docker pull fedora`), CRI-O assumes `docker.io`. This was the original behavior introduced with `docker` back then. To not break existing deployments, we'd like to have a configuration to setup _additional_ and _blocked_ registries in order to assume other registries (not `docker.io`) and block certain one (think about heavy locked deployments where developers aren't allowed to pull from `docker.io` forinstance).

**Comment by rhatdan** [comment]
This should be moved to containers/image or containers/storage?  It should be in a config file provided by them.

**Comment by runcom** [comment]
I have a branch for this, it will be done directly in cri-o, containers/image and storage will always be given the fully qualified image name.

**Comment by rhatdan** [comment]
Ok, Only issue I would see if whether or not we wanted buildah to have the same support.
