### ISSUE TITLE
Remove ocic and switch to crictl

### ISSUE THREAD

**Issue by sameo** [kubernetes-incubator/cri-o#504]
[crictl](https://github.com/kubernetes-incubator/cri-tools/tree/master/cmd/crictl) is providing all the `ocic` features (and more, see the already implemented `crictl attach` command) and will most likely become the official CRI cli for Kubernetes.

Hence we should drop our `ocic` code and switch to `crictl`

**Comment by runcom** [comment]
working on this also.

**Comment by runcom** [comment]
We need to drop crioctl from tests and delete it in favor of crictl

**Comment by mdshuai** [comment]
@runcom I want to try this, but don't know why need delete crioctl from the test?

**Comment by runcom** [comment]
> @runcom I want to try this, but don't know why need delete crioctl from the test?

the tests under `./test/*.bats` are using `crioctl` but we want them to use `crictl`. `crictl` is already wired in but we're not using it everywhere and that's why we can't remove `crioctl` yet. Also, the `crictl` command line is different than `crioctl` so, one example could be:
```diff
diff --git a/test/ctr.bats b/test/ctr.bats
index f41d16f11..211c18a08 100644
--- a/test/ctr.bats
+++ b/test/ctr.bats
@@ -8,7 +8,7 @@ function teardown() {
 
 @test "ctr not found correct error message" {
        start_crio
-       run crioctl ctr status --id randomid
+       run crictl inspect randomid
        echo "$output"
        [ "$status" -eq 1 ]
        [[ "$output" =~ "container with ID starting with randomid not found" ]]
```

**Comment by TomSweeneyRedHat** [comment]
@weiwei04 has been working on this in #1158.  I'm moving the todo from that issue here to track it, and will close #1158.

This is a umbrella issue to track the crioctl -> crictl progress

Some todos:

    replace crioctl with crictl in e2e tests #1156 #1159

    remove crioctl code
