### ISSUE TITLE
measure performance

### ISSUE THREAD

**Issue by runcom** [kubernetes-incubator/cri-o#519]
Now that we can run basic pods in kube we'll need some sort of benchmarks from kube e2e density to gather info such as how many pod per min, pod per node and whatnot. Let's leave this open for anyone to contribute

**Comment by rhatdan** [comment]
@jeremyeder team is beginning to look at this.

**Comment by jeremyeder** [comment]
JFYI @sjug we can report data back here once we've run tests and reviewed internally.

**Comment by rhatdan** [comment]
I think @sjug runs these regularly.  I am closing this issue.
