### ISSUE TITLE
Add support for mount propagation

### ISSUE THREAD

**Issue by mrunalp** [kubernetes-incubator/cri-o#541]
Ensure that mount propagation works correctly to inject volumes from the host or to host.

**Comment by runcom** [comment]
Many of the potential issues here must be addressed in containers/storage also.

**Comment by mrunalp** [comment]
Yes we can create another issue there.

**Comment by rhatdan** [comment]
Has this been verified?

**Comment by mrunalp** [comment]
Actually, this is still being worked on in upstream k8s.

**Comment by runcom** [comment]
Fixed in master, the CRI passes mount propagation options as well
