### ISSUE TITLE
Add support for host ports

### ISSUE THREAD

**Issue by mrunalp** [kubernetes-incubator/cri-o#560]
We will need to add support for node ports in k8s using iptables. 
@rajatchopra Can you let us know the specifics of what we need to do for this?

**Comment by mrunalp** [comment]
cc: @sameo

**Comment by rajatchopra** [comment]
@mrunalp I assume you mean HostPort support here. 
Unfortunately, the runtime has to handle that until kubernetes and cni converge for passing the hostport configuration over through cni to the plugin itself (~ after kube 1.7).
Meanwhile, we should be able to use kubenet libraries directly and get the support in crio. It will be done asynchronously from the CNI calls. The other option would be to get dirty with proxy/iptables directly. If the kubenet option sounds good, I will pull up the required things and we can work on the solution.

**Comment by mrunalp** [comment]
@rajatchopra using kubenet for now sounds good!

**Comment by apilloud** [comment]
Getting HostPorts working is at the top of my todo list. I'll take this on today unless someone else is on it.

**Comment by mrunalp** [comment]
@apilloud Go for it! :)

**Comment by rajatchopra** [comment]
@apilloud 
+1

In my mind I was planning to use this:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/network/hostport

Especially this call: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/network/hostport/hostport_syncer.go#L156

Any other way is just fine. Will be happy to review the PR. Thanks.
