### ISSUE TITLE
Build binaries for all supported architectures

### ISSUE THREAD

**Issue by luxas** [kubernetes-incubator/cri-o#578]
@runcom https://github.com/kubernetes/community/blob/master/contributors/design-proposals/multi-platform.md

**Comment by runcom** [comment]
@luxas thanks for the issue, we'll try to work on this asap (hopefully you can also help us :smile: )

**Comment by rhatdan** [comment]
@lsm5 could you see if CRI-O builds on other arches?

**Comment by lsm5** [comment]
is it ok/enough to consider arches supported by fedora? It failed for s390x for some reason, I gotta revisit it, but it's available for other arches https://koji.fedoraproject.org/koji/buildinfo?buildID=913950

**Comment by rhatdan** [comment]
@luxas WDYT?

**Comment by luxas** [comment]
arm, arm64, ppc64le and s390x are the official platforms for k8s, but introducing three new in one go and investigating / following up with s390x SGTM. Also you might contact some s390x people to help if you want

**Comment by rhatdan** [comment]
I think we can close this issue?

**Comment by luxas** [comment]
What platforms do you build for now?

**Comment by rhatdan** [comment]
Checking today on Fedora.
```
koji download-build  cri-o-1.0.0.rc.1-3.gitbb1da97.fc26
cri-o-1.0.0.rc.1-3.gitbb1da97.fc26.ppc64le.rpm
[====================================] 100%  20.42 MiBB
cri-o-1.0.0.rc.1-3.gitbb1da97.fc26.x86_64.rpm
[====================================] 100%  23.82 MiBB
cri-o-1.0.0.rc.1-3.gitbb1da97.fc26.i686.rpm
[====================================] 100%  21.83 MiBB
cri-o-1.0.0.rc.1-3.gitbb1da97.fc26.armv7hl.rpm
[====================================] 100%  20.83 MiBB
cri-o-1.0.0.rc.1-3.gitbb1da97.fc26.aarch64.rpm
[====================================] 100%  21.10 MiBB
cri-o-devel-1.0.0.rc.1-3.gitbb1da97.fc26.noarch.rpm
[====================================] 100%   3.91 MiBB
cri-o-1.0.0.rc.1-3.gitbb1da97.fc26.src.rpm
[====================================] 100%   5.62 MiBB
```
