### ISSUE TITLE
Container names may not be unique

### ISSUE THREAD

**Issue by alexlarsson** [kubernetes-incubator/cri-o#617]
Server.generateContainerIDandName() creates a runc name for the sandbox like this:
```
	nameStr := fmt.Sprintf("%s-%s-%v", podName, name, attempt)
```

This seems unsafe wrt collisions. For instance, say you have a pod "foo-bar", and with a container "gazonk", and you have another pod named "foo", with a container named "bar-gazonk". These two will get the same container name.

I don't know the behaviour up the stack, but it seems to me that even if this is unlikely to happen by accident, it could happen deliberately as some form of attack.

**Comment by runcom** [comment]
we're missing the pod sandbox UID in both containers and sandbox names, I'll add it.
