### ISSUE TITLE
gometalinter  is not available on Fedora

### ISSUE THREAD

**Issue by rhatdan** [kubernetes-incubator/cri-o#68]
``` 
make lint
checking lint
./.tool/lint: line 9: gometalinter: command not found
make: *** [Makefile:26: lint] Error 127
[Exit 2]
```

**Comment by runcom** [comment]
@rhatdan you need to run "make install.tools" before running that

**Comment by mrunalp** [comment]
@rhatdan Also, added instructions to get started in #67

**Comment by runcom** [comment]
@rhatdan if `make install.tools` works we can close this I guess

**Comment by rhatdan** [comment]
Why not have this happen automatically?  Does install.tools require root?

**Comment by rhatdan** [comment]
Ok not, but it would be nice if 
make lint triggered a make install.tools the first time, or at least told me I need to do make install.tools

**Comment by runcom** [comment]
> Ok not, but it would be nice if 
> make lint triggered a make install.tools the first time, or at least told me I need to do make install.tools

I'm fixing that
