### ISSUE TITLE
Add --creds to kpod pull

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [kubernetes-incubator/cri-o#689]
There are changes for the "buildah from" command to add credentials.  That PR is currently under review at: https://github.com/projectatomic/buildah/pull/204.  Similar functionality should be added to kpod pull.  The code in buildah is based on the code from skopeo.

**Comment by TomSweeneyRedHat** [comment]
As a note, I'll be working on this issue unless Urvashi has beaten me to the punch with here work in the space.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @umohnani8 Has this been merged?

**Comment by umohnani8** [comment]
I think @TomSweeneyRedHat was working on it. I do not see the --creds flag in kpod pull though. I can add it in with my already open PR for the authfile flag.

**Comment by rhatdan** [comment]
Do that.

**Comment by TomSweeneyRedHat** [comment]
@redhatdan I've been a slacker.  It's been on the list but keeps being pushed down.  I've not gotten --creds or --auth into kpod pull or push.  I think pull may have it already, but I wanted to test and then add as necessary.

**Comment by umohnani8** [comment]
Fixed in https://github.com/kubernetes-incubator/cri-o/pull/1015

**Comment by umohnani8** [comment]
And fixed in https://github.com/kubernetes-incubator/cri-o/pull/1074

**Comment by umohnani8** [comment]
@TomSweeneyRedHat @rhatdan can one of you please close this issue. I don't think I have the permission to.
