### ISSUE TITLE
precisely document the scope of this project

### ISSUE THREAD

**Issue by TomasTomecek** [kubernetes-incubator/cri-o#690]
I just got pinged about whether cri-o is going to be a standalone container runtime. As far as I remember, the answer is that it's meant to be used explicitly with kubernetes (can't find it anywhere). Is this correct? If so, can we stress it in the readme? (can send a PR)

**Comment by rhatdan** [comment]
We are building out the kpod tools to allow you to do most things with containers without requiring CRI-O to be running.  kpor run,exec, rmi, rm ...  But the primary goal of this is to be to help people diagnose what is going on in a k8s/CRI-O environment.  
Most people who are running kubernetes with upstream docker project, use docker cli to diagnose issues, so we want to build out kpod to be able to do the same thing.  
But it is an OpenSource project so if people want to do other standalone container runtime activities with kpod, we would be all for it.

**Comment by TomasTomecek** [comment]
Seems like that cri-o version in Fedora rawhide falls behing upstream a bit since I cannot see `run` nor `exec`. There is just `launch` and it says:

```
$ kpod -s overlay2 launch
this functionality is not yet implemented
```

I'm assuming from your detailed description that at some point I could be able to run and manage my containers using kpod and not need any daemons to interact with.

**Comment by mheon** [comment]
@TomasTomecek kpod is still very much a work in progress, and neither of those are yet implemented in master, never mind our released versions. Image management has already been implemented, and basic container management is now being worked on.

Your second point is spot on, though. Once complete, kpod should be able to manage containers and pods on its own without a CRI-O daemon running.

**Comment by TomasTomecek** [comment]
> kpod should be able to manage containers and pods on its own without a CRI-O daemon running

Neat! This is great news. Not sure if you guys have this documented or you would like to share this in a roadmap. If not, I'm good and we can close this one.
