### ISSUE TITLE
GO idiomatic (not)

### ISSUE THREAD

**Issue by runcom** [kubernetes-incubator/cri-o#710]
Stuff like https://github.com/kubernetes-incubator/cri-o/blob/master/libkpod/containerData.go aren't go idiomatic, that file should be `container_data.go` . This also should be underscored https://github.com/kubernetes-incubator/cri-o/blob/master/libkpod/containerserver.go

@14rcole @mheon PTAL

**Comment by rhatdan** [comment]
Lets open a pull request to rename them.

**Comment by mheon** [comment]
@runcom Good catch. Haven't been watching file naming when reviewing stuff, I'll try to look for this from now on.

Opened #711 to fix.
