### ISSUE TITLE
Sirupsen and sirupsen

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-o#712]
runc and containerd are all moving up to `sirupsen` v1.0.0.

cri-o and packages it's using are still at `Sirupsen` v0.11.5.

Are we going to update to `sirupsen`?

**Comment by runcom** [comment]
We do yes!

**Comment by Random-Liu** [comment]
@runcom Cool! Thanks!

**Comment by mrunalp** [comment]
Created #716 to fix. Thanks!

**Comment by Random-Liu** [comment]
Close this since https://github.com/kubernetes-incubator/cri-o/pull/735 is merged.
