### ISSUE TITLE
Breakout https://github.com/kubernetes-incubator/cri-o/pkg/ocicni into separate repo

### ISSUE THREAD

**Issue by crosbymichael** [kubernetes-incubator/cri-o#715]
Can we break this package out into a separate repo as it seems like it is used by multiple CNI users.

**Comment by mrunalp** [comment]
Sure, we are working on it. I'll update here once it is done. Thanks!

**Comment by crosbymichael** [comment]
Thanks

**Comment by Random-Liu** [comment]
Thanks~

**Comment by crosbymichael** [comment]
@mrunalp any update on this move?

**Comment by cyphar** [comment]
We moved this into the repo several months ago, to aid development. If we're going to move it somewhere it really should be in a organisation repo rather than a personal repo (which was the case previously).

**Comment by mrunalp** [comment]
I have moved it to https://github.com/cri-o/ocicni but haven't cleaned up that repo yet.
