### ISSUE TITLE
run pod failed with runc-1.0-rc3/rc2

### ISSUE THREAD

**Issue by sak0** [kubernetes-incubator/cri-o#723]
### base env
**crioctl --version**
crioctl version 1.0.0-alpha.0

**kpod version**
Version:       0.0.1
Go Version:    go1.8
Git Commit:    fa6e2d8
Built:         Tue Aug  1 03:56:00 2017
OS/Arch:       linux/amd64

**uname -r**
4.10.9-1.el7.elrepo.x86_64

### with [runc-1.0-rc3](https://github.com/opencontainers/runc/releases/download/v1.0.0-rc3/runc-linux-amd64) Failed
**crioctl pod run --config test/testdata/sandbox_config.json**
Creating the pod sandbox failed: rpc error: code = 2 desc = container create failed: target os  mismatch with current os linux
`DEBU[2017-08-02 10:48:52.341474936-04:00] running conmon: /usr/local/libexec/crio/conmon  args=[-c 561754f9bbfa782dc0b1533ebce7cb6315733a92297c45163b671fd94942431a -u 561754f9bbfa782dc0b1533ebce7cb6315733a92297c45163b671fd94942431a -r /usr/bin/runc -b /var/run/containers/storage/overlay2-containers/561754f9bbfa782dc0b1533ebce7cb6315733a92297c45163b671fd94942431a/userdata -p /var/run/containers/storage/overlay2-containers/561754f9bbfa782dc0b1533ebce7cb6315733a92297c45163b671fd94942431a/userdata/pidfile -l /var/log/crio/pods/561754f9bbfa782dc0b1533ebce7cb6315733a92297c45163b671fd94942431a/561754f9bbfa782dc0b1533ebce7cb6315733a92297c45163b671fd94942431a.log]
DEBU[2017-08-02 10:48:52.350021923-04:00] Received container pid: -1                   
DEBU[2017-08-02 10:48:52.350097659-04:00] Container creation error: target os  mismatch with current os linux`

### with [runc-1.0-rc2](https://github.com/opencontainers/runc/releases/download/v1.0.0-rc2/runc-linux-amd64) Failed
**crioctl pod run --config test/testdata/sandbox_config.json**
Creating the pod sandbox failed: rpc error: code = 2 desc = container create failed: json: cannot unmarshal object into Go value of type []string
`DEBU[2017-08-02 10:52:31.788420222-04:00] running conmon: /usr/local/libexec/crio/conmon  args=[-c ee0c4ad8c822975692b88246105dfa619838c3944e71b251c24364200ecdc52a -u ee0c4ad8c822975692b88246105dfa619838c3944e71b251c24364200ecdc52a -r /usr/bin/runc -b /var/run/containers/storage/overlay2-containers/ee0c4ad8c822975692b88246105dfa619838c3944e71b251c24364200ecdc52a/userdata -p /var/run/containers/storage/overlay2-containers/ee0c4ad8c822975692b88246105dfa619838c3944e71b251c24364200ecdc52a/userdata/pidfile -l /var/log/crio/pods/ee0c4ad8c822975692b88246105dfa619838c3944e71b251c24364200ecdc52a/ee0c4ad8c822975692b88246105dfa619838c3944e71b251c24364200ecdc52a.log]
DEBU[2017-08-02 10:52:31.797172355-04:00] Received container pid: -1                   
DEBU[2017-08-02 10:52:31.797212879-04:00] Container creation error: json: cannot unmarshal object into Go value of type []string`

### with [runc-master](https://github.com/opencontainers/runc.git) Success
cause runc commit ["Remove Platform as no longer in OCI spec"](https://github.com/opencontainers/runc/pull/1495/commits/e1146182a8cebb5a6133a9e298a5e4acf99652e9)

so i guess this version of crio  only work with runc-1.0.0-rc4? or i have some configure mistake?

**Comment by runcom** [comment]
You need at least rc4 yeah

**Comment by rhatdan** [comment]
The master branch should be working with runc 1.0.0 - Released.
