### ISSUE TITLE
Enable cross compilation for ocic tool

### ISSUE THREAD

**Issue by jawnsy** [kubernetes-incubator/cri-o#75]
The companion tool developed for testing ocid is generally useful for any CRI-based runtime, so it would be useful to provide cross-compiled versions for other platforms.

It seems the `gimme` tool used by Travis CI to manage the Go dependency can [handle cross compilation quite easily](https://github.com/travis-ci/gimme#travisyml), however, it may be easiest if we split the ocic tool into its own repository. Otherwise, I suppose we'll need to detect that we're cross compiling in our Makefile and then avoid trying to build the daemon.

**Comment by runcom** [comment]
seems like we could need this in a second development stage - we're currently targeting runc now

**Comment by jawnsy** [comment]
@runcom What do you think about splitting `ocic` into a separate project? This should make it easier to cross-compile, plus builds probably wouldn't need sudo (since we don't need docker) - which should make them run faster.

**Comment by runcom** [comment]
> @runcom What do you think about splitting ocic into a separate project? This should make it easier to cross-compile, plus builds probably wouldn't need sudo (since we don't need docker) - which should make them run faster.

it's not something in the current scope of the project https://github.com/kubernetes-incubator/cri-o#what-is-not-in-scope-for-this-project

**Comment by rhatdan** [comment]
Can't you just switch it in the Makefile?

Is
make ocic?
Enough?

I have fears of the security issues of making ocic  and ocid listen to the network, yet another process listening on the network giving root access to anyone who can connect.

**Comment by mrunalp** [comment]
We will switch to cri-tools at some point.
