### ISSUE TITLE
Support for restarting the kubelet without killing pods/containers

### ISSUE THREAD

**Issue by fabiand** [kubernetes-incubator/cri-o#756]
I'm not sure about today's state, but we - KubeVirt - will need a way to ensure that our containers (as part of pods) will survive a kubelet restart/reload.

This probably relies on cri-o's support but also on the support in kubelet. This issue is about making sure that cri-o will support this use-case.

**Comment by mrunalp** [comment]
@fabiand We do support that today and have a test to ensure that it doesn't break. 
In CreateContainer CRI API, we spawn conmon which in turn starts the container/VM and monitors it. This allows us to restart the cri-o daemon w/o taking down the running containers.

**Comment by fabiand** [comment]
Cool - I was not aware of this, I need to play a little more with K8s/CRI-O then.
