### ISSUE TITLE
crio does not update IPAM from kubelet

### ISSUE THREAD

**Issue by kelseyhightower** [kubernetes-incubator/cri-o#791]
Environment:
```
crio version 1.0.0-alpha.0
Kubernetes v1.7.4
```

When the kubelet starts up it issues the following RPC call:

```
I0826 15:43:50.360610   11530 kubelet_node_status.go:85] Successfully registered node worker0
I0826 15:43:50.362794   11530 kuberuntime_manager.go:901] updating runtime config through cri with podcidr 10.200.0.0/24
I0826 15:43:50.363434   11530 kubelet_network.go:326] Setting Pod CIDR:  -> 10.200.0.0/24
```

When using `kubenet` and the Docker CRI integration, the Pod CIDR received from the kubelet is used to update the CNI network config; this does not seem to be the case with CRI-O.

I'm starting CRI-O with the following CNI config:

```
{
  "name": "mynet",
  "type": "bridge",
  "ipam": {
    "type": "host-local"
  }
}
```

Yes, I'm leaving out the subnet on purpose in hopes that CRI-O will update it based on the RPC call from the kubelet.

When I attempt to run a pod I get the following errors from CRI-O:

```
6d818fd 
INFO[2017-08-26 15:45:42.613717471Z] Using netns path default                     
INFO[2017-08-26 15:45:42.613769977Z] About to run with conf.Network.Type=bridge   
ERRO[2017-08-26 15:45:42.630868233Z] Error adding network: no IP ranges specified 
ERRO[2017-08-26 15:45:42.631102340Z] Error while adding to cni network: no IP ranges specified
```

**Comment by kelseyhightower** [comment]
I can get things working by manually updating the CNI config with the following settings based on the IP address assigned to the node:

```
{
  "name": "mynet",
  "type": "bridge",
  "hairpinMode": false,
  "ipMasq": false,
  "isGateway": true,
  "ipam": {
    "type": "host-local",
    "gateway": "10.200.0.1",
    "subnet": "10.200.0.0/24",
    "routes": [{ "dst": "0.0.0.0/0" }]
  }
}
```

I'm still researching, but is this the responsibility of CRI-O?

**Comment by kelseyhightower** [comment]
Looks like CRI makes it optional on what to do when `podCIDR` is sent to the runtime through the `UpdateRuntimeConfig` interface.

https://github.com/kubernetes/community/blob/master/contributors/devel/kubelet-cri-networking.md

**Comment by kelseyhightower** [comment]
Looks like this was discussed here: https://github.com/kubernetes-incubator/cri-o/pull/281

**Comment by runcom** [comment]
I'm taking care of this by caring about podCIDR only if host-local, I'll have a PR soon

**Comment by runcom** [comment]
Opened https://github.com/kubernetes/kubernetes/issues/51427 upstream in kube as it's too much of an hack to figure out we're using `kubenet` and update config accordingly - also, we're missing info from the CRI

**Comment by kelseyhightower** [comment]
@runcom No worries. I'm going to use the calico CNI plugin for now. I guess one option is to be able to start cri-o without a CNI configuration in place. Still print the warning, but assume a CNI configuration will show up at some point in the future.

**Comment by kelseyhightower** [comment]
It also seems that cri-o does not pick up new CNI network configs once it's been started. Installing a CNI plugin using a daemonset presents a race condition. Seems I have to restart cri-o on each node in order to pick up the new CNI network config placed my a CNI plugin.

**Comment by mrunalp** [comment]
@rajatchopra Can you take a look at the issue with new network configs?
