### ISSUE TITLE
ocic pod remove does rm container in memory state

### ISSUE THREAD

**Issue by ipbabble** [kubernetes-incubator/cri-o#81]
[root@gideon cri-o]# ocic pod list
ID: 9112c2bac547df317c99967de8b5f63b8aafb2158ad9b640e6163eae42e9a439
Status: READY
Created: 2016-09-29 17:32:31 -0600 MDT
[root@gideon cri-o]# ocic pod stop --id=9112
9112
[root@gideon cri-o]# ocic pod list
ID: 9112c2bac547df317c99967de8b5f63b8aafb2158ad9b640e6163eae42e9a439
Status: NOTREADY
Created: 2016-09-29 17:32:31 -0600 MDT
[root@gideon cri-o]# ocic pod remove --id=9112
9112
[root@gideon cri-o]# ocic pod list
[root@gideon cri-o]# ocic ctr list
FATA[0000] listing containers failed: rpc error: code = 2 desc = error getting container state for podsandbox1-redis: exit status 1: []

**Comment by mrunalp** [comment]
Thanks @ipbabble I'll look into this one.
