### ISSUE TITLE
Currently runc needs to be built and installed and not installed using yum/dnf

### ISSUE THREAD

**Issue by ipbabble** [kubernetes-incubator/cri-o#82]
In the setting started guide it is important to point out that currently runc and cri-o are being updated regularly with some dependencies.  Intsalling runc packages will not guarentee that cri-o will run successfully at this time. Therefore it is best to install runc from a local build. Point to runc repo and the build/install instructions. 

If you have runc installed already from a package it is likely that cri-o will not run currently despite installing runc from build. The already installed runc may be in a the PATH and get picked up. It is best to remove the runc package from your system and only have the current build installed. 

Perhaps make install of runc could check if runc _package_ is already installed as a package and prompt the installer to remove the previous package.

**Comment by mrunalp** [comment]
We have updated README with expected version of runc.
