### ISSUE TITLE
add commit information to version output

### ISSUE THREAD

**Issue by egernst** [kubernetes-incubator/cri-o#825]
It would be helpful to see HEAD's SHA included in --version output for crio(ctl).

This became apparent when looking @ latest drop of kubernetes-the-hardway and wanting to know what branch/release matches 'v1.0.0-beta.0.'  Looking at the sources, there is a matching TAG for this in release-1.6 branch (and master), though the version updated in the source tree (app.Version) was updated considerably later in the source tree.

Having a SHA would make these all very clear.

Let me know what you all think.  If you agree I can put this on my to-do-list.

**Comment by egernst** [comment]
@mrunalp @sameo @runcom

**Comment by mrunalp** [comment]
This sounds good as discussed in today's call. Please open a PR :)

**Comment by runcom** [comment]
+1 (I missed the call though :/)
