### ISSUE TITLE
applying cgroup configuration for process caused \"No such device or address\""

### ISSUE THREAD

**Issue by runcom** [kubernetes-incubator/cri-o#832]
Starting a local kube cluster with cri-o master throws this when starting kube-dns:
```
  1m    2s      8       kubelet, 127.0.0.1      spec.containers{kubedns}        Warning Failed          Error: container create failed: container_linux.go:265: starting container process caused "process_linux.go:264: applying cgroup configuration for process caused \"No such device or address\""
```
I thought it was because of https://github.com/kubernetes-incubator/cri-o/pull/812 but after reverting that the issue still persists. I tested with systemd cgroup manager + fedora 26 + systemd 233-6, everything else is stock CRI-O (runc, conmon), SELinux is disabled.

It only happens to the kube-dns container, I can start any other container/pod just fine. (in the kube-dns pod, sidecar and dnsmasq containers start up just fine, it's just kube-dns...)

The same happens with cgroupfs fwiw

Not sure what's going on...

**Comment by runcom** [comment]
@mrunalp PTAL

**Comment by runcom** [comment]
Seems like it was just runc, using latest runc master works fine

**Comment by huzhengchuan** [comment]
I meet the same question. How to fix it. @runcom

**Comment by runcom** [comment]
just upgrade runc

**Comment by Hades32** [comment]
I don`t have runc installed at all. I just have followed the tutorial for "kubeadm". I only decided to use the newest docker instead of 17.03...

**Comment by rhatdan** [comment]
Well CRI-O will definitely not work without runc installed.  Unless you override with a different OCI Runtime implementation.

**Comment by Hades32** [comment]
Not sure what problem I really had, but for anybody coming here (via google) for the same reason:
You should NOT follow the tutorial (https://kubernetes.io/docs/setup/independent/install-kubeadm/) and instead use cgroupfs instead of systemd. 
Compiling runc from master didn´t change anything for me...

**Comment by MOZGIII** [comment]
Here are some snippets/examples to resolve this issue: https://gist.github.com/MOZGIII/22bf4eb811ff5d4e0bbe36444422b6d3
