### ISSUE TITLE
Need image size w/o names

### ISSUE THREAD

**Issue by runcom** [kubernetes-incubator/cri-o#857]
Extracted from https://github.com/kubernetes-incubator/cri-o/pull/848

Right now, we need image names to gather the size of an image. However, it could happen names aren't available for an image, thus not reporting image size.
We need a way here in CRI-O to get the image size from the stored image (ID?).

@nalind could you look into this?

/cc @rhatdan

**Comment by mtrmac** [comment]
The `containers-storage` AFAICT _already_ supports referencing images by IDs, using the `@`_id_ syntax.
