### ISSUE TITLE
ps -v for verbose info: PID and namespace

### ISSUE THREAD

**Issue by jzb** [kubernetes-incubator/cri-o#868]
Would be good if kpod did something like what Brendan Gregg proposed [here](https://github.com/moby/moby/issues/32501). Specifically, show PID and namespace (and possibly other useful info) that's currently not easy to see at a glance for containers. 

@umohnani8 Dan suggested I ask you to PTAL. Thanks!

**Comment by rhatdan** [comment]
@brendangregg @Maksadbek FYI

**Comment by umohnani8** [comment]
Will work on adding something like that. Want any specific info, or should I just follow what is shown in https://github.com/moby/moby/issues/32501?

**Comment by rhatdan** [comment]
Follow that for now.

**Comment by brendangregg** [comment]
Thanks, I use my script (on docker anyway) almost every day. Very handy. The screenshot doesn't show the colors. Here's a screengrab:

![screen shot 2017-09-08 at 2 55 14 pm](https://user-images.githubusercontent.com/1101211/30232623-df91aef8-94a5-11e7-8138-1cbf2403cb4f.png)

Red means it's sharing the namespace with the host.

**Comment by rhatdan** [comment]
Our goal is that you script would just need to 
sed 's/docker/kpod/g' 
And then it will work with the CRI-O project.  :^)

**Comment by rhatdan** [comment]
Kpod now has support
