### ISSUE TITLE
add Fedora 26 to CI tests

### ISSUE THREAD

**Issue by runcom** [kubernetes-incubator/cri-o#873]
Right now we run tests in CI with RHEL 7.4-latest and Fedora 25 cloud. We need to include Fedora 26 asap and probably RHEL 7.3 at this point.

@cevich could you look into this?

/cc @mrunalp

**Comment by cevich** [comment]
Supporting multiple versions of RHEL (and Fedora?) is possible, but it's not as trivial as it should be 😖 I'll open a card for it...

https://trello.com/c/bN412wF6
