### ISSUE TITLE
Prepend registries from config

### ISSUE THREAD

**Issue by luizbafilho** [kubernetes-incubator/cri-o#880]
Hi, 

I would like to know if it is possible to prepend the `registries` from `crio.conf` instead of append them in the final registries list.

I'm requesting that to avoid this error:
```
[root@k8s-minion-be-2 ~]# kpod pull redis
error pulling image from "redis": error loading image "redis": Error initializing image from source docker://redis:latest: pinging docker registry returned: Get https://registry-1.docker.io/v2/: dial tcp 52.87.53.92:443: i/o timeout
main.pullCmd
        /home/vagrant/go/src/github.com/kubernetes-incubator/cri-o/cmd/kpod/pull.go:53
github.com/kubernetes-incubator/cri-o/vendor/github.com/urfave/cli.HandleAction
        /home/vagrant/go/src/github.com/kubernetes-incubator/cri-o/vendor/github.com/urfave/cli/app.go:485
github.com/kubernetes-incubator/cri-o/vendor/github.com/urfave/cli.Command.Run
        /home/vagrant/go/src/github.com/kubernetes-incubator/cri-o/vendor/github.com/urfave/cli/command.go:193
github.com/kubernetes-incubator/cri-o/vendor/github.com/urfave/cli.(*App).Run
        /home/vagrant/go/src/github.com/kubernetes-incubator/cri-o/vendor/github.com/urfave/cli/app.go:250
main.main
        /home/vagrant/go/src/github.com/kubernetes-incubator/cri-o/cmd/kpod/main.go:90
runtime.main
        /usr/local/go/src/runtime/proc.go:185
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:2197
```

Prepend is useful when deploying kubernetes on offline nodes, which is my case. In most of enterprise deployments, nodes will not have internet access, requiring a private repository that will mostly serve as a docker hub mirror.

I'm willing to do a PR to fix that, but I couldn't find the right place to make the change. If you point me the direction would be great.

CRI-O version I'm using:
```
# crio -v
crio version 1.0.0-rc2-dev
commit: "36584e6f34e54461eaba66e8b09f2652d75d45cc-dirty"
```

**Comment by runcom** [comment]
`kpod pull` should actually do something like this: https://github.com/kubernetes-incubator/cri-o/blob/master/server/image_pull.go#L29-L90

that code is actually getting the registries list and try (one by one) each of the registries (prepending them to the image).

**Comment by runcom** [comment]
@umohnani8 could you take a look at this?

**Comment by umohnani8** [comment]
@runcom I believe https://github.com/kubernetes-incubator/cri-o/pull/841 is fixing this. The only difference is that the registries are configured in `/etc/containers/registries.conf` instead of `crio.conf`.
@baude could you please take a look at this.

**Comment by baude** [comment]
Yes #841 is fixing this, by reading the registries from /etc/containers/registries.conf which is becoming the global registries file for ALL container runtimes.

**Comment by luizbafilho** [comment]
once #841 is merged do I have to create `/etc/containers/registries.conf` or can I just use `crio.conf` ? 

I used `kpod` as a example but, I get the same error when cri-o tries to pull the image.

**Comment by rhatdan** [comment]
841 has been merged this should work now.
