### ISSUE TITLE
error: did not receive slice as parent

### ISSUE THREAD

**Issue by sjenning** [kubernetes-incubator/cri-o#896]
Running hack/local-up-cluster.sh
```
E0912 17:28:03.825920   27272 remote_runtime.go:92] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = cri-o configured with systemd cgroup manager, but did not receive slice as parent: /kubepods/pod6f71cc2a-9809-11e7-9b63-7085c20cf2ab
```
Running rc1 cri-o package from the repos on Fedora 26.

@mrunalp @derekwaynecarr

**Comment by sjenning** [comment]
related issue https://github.com/kubernetes-incubator/cri-o/issues/842

**Comment by mrunalp** [comment]
Did you set CGROUP_DRIVER=systemd for kube?

**Comment by sjenning** [comment]
ooooh, if running docker, there is code in local-up-cluster to detect the driver, but if not, kube defaults to cgroupfs. nevermind!

**Comment by rhatdan** [comment]
I hit the same issue and changed to cgroupfs.

**Comment by rhatdan** [comment]
@mrunalp I saw this issue just using the test suite, which I think now uses crictl? Do I need to change something in crictl to set the cgroup?

**Comment by runcom** [comment]
> @mrunalp I saw this issue just using the test suite, which I think now uses crictl? Do I need to change something in crictl to set the cgroup?

you shouldn't, if it happened in tests it's probably because of the fixtures that have hardcoded cgroupfs paths

**Comment by rhatdan** [comment]
@runcom install the crio package on fedora 26 with the config file set to systemd, and see if the tests fail.

**Comment by runcom** [comment]
@rhatdan they fail because crio in f26 has systemd while we have cgroupfs paths in fixtures, see here https://github.com/kubernetes-incubator/cri-o/blob/master/test/testdata/sandbox_config.json#L36

**Comment by runcom** [comment]
@rhatdan if you want tests to run fine you have to:
```
CGROUP_MANAGER=systemd make localintegration
```

**Comment by rhatdan** [comment]
We should probably change this if we are going to default to systemd, but if we stick to default of cgroupfs then it is fine.

**Comment by dghubble** [comment]
Introductory tutorial [tutorial](https://github.com/kubernetes-incubator/cri-o/blob/master/tutorial.md#pod-tutorial) leads me straight into this issue on Fedora 27 trying to create a sandbox locally.

@runcom Can you provide more context? Independent of Kubernetes or your testing, what's the right path?

**Comment by jahentao** [comment]
> We should probably change this if we are going to default to systemd, but if we stick to default of cgroupfs then it is fine.

I don't know how to modify it, is there a sample?

**Comment by haircommander** [comment]
> > We should probably change this if we are going to default to systemd, but if we stick to default of cgroupfs then it is fine.
> 
> I don't know how to modify it when use `systemd`, is there a sample?

in your `/etc/crio/crio.conf` edit the line 
```
cgroup_manager = "$MANAGER"
```
where $MANAGER is either cgroupfs or systemd

**Comment by jahentao** [comment]
> > > We should probably change this if we are going to default to systemd, but if we stick to default of cgroupfs then it is fine.
> > 
> > 
> > I don't know how to modify it when use `systemd`, is there a sample?
> 
> in your `/etc/crio/crio.conf` edit the line
> 
> ```
> cgroup_manager = "$MANAGER"
> ```
> 
> where $MANAGER is either cgroupfs or systemd

I successfully use cri-o to run pod and container, following the [guide](https://github.com/cri-o/cri-o/blob/master/tutorials/setup.md) and [tutorial](https://github.com/cri-o/cri-o/blob/master/tutorials/crictl.md), whose default `cgroup_manager` is `cgroupfs`.

when I tried to set `cgroup_manager = "systemd"` in `/etc/crio/crio.conf` and restart `crio` service.

then, I tried the same steps in [tutorial](https://github.com/cri-o/cri-o/blob/master/tutorials/crictl.md)

```
POD_ID=$(sudo crictl runp test/testdata/sandbox_config.json)
```
But I got the error below:
```
FATA[0000] run pod sandbox failed: rpc error: code = Unknown desc = cri-o configured with systemd cgroup manager, but did not receive slice as parent: /Burstable/pod_123-456
```

the `sandbox_config.json` is same as [sandbox_config.json](https://github.com/cri-o/cri-o/blob/master/test/testdata/sandbox_config.json)

**Comment by haircommander** [comment]
Ah you need to configure crictl to use systemd. I think the option is `--cgroup-driver`

**Comment by haircommander** [comment]
There's a way to set it globally but i forget how

**Comment by haircommander** [comment]
ah, sorry, I found it:
in `/etc/crictl.yaml`:
```
runtime-endpoint: unix:///var/run/crio/crio.sock
cgroup-manager: systemd
```

**Comment by xkwangcn** [comment]
> cgroup-manager:

hi, after adding cgroup-manager: systemd in /etc/crictl.yaml, could it work? I am very very confused with my errors...

**Comment by defyjoy** [comment]
Why this error is closed even if adding `cgroup-manager: systemd` does not work properly. It does not work for me are there any other bits or documentation which is needed for this to be followed ? I am confused as well this should not be closed since it does not resolve the issue for kubernetes setup with crio actually . Any pointers how to properly resolve this ?

**Comment by vofish** [comment]
Hi, guys,
Finally, I've found a solution. You should put "**--cgroup-driver=systemd**" to the **/var/lib/kubelet/kubeadm-flags.env** as _KUBELET_KUBEADM_ARGS_, then:
```
systemctl daemon-reload
systemctl restart kubelet
```
and should work.

**Comment by jmcgrath207** [comment]
made a small script for this that works for me with k8 1.20 and cri-o 1.20

```bash
# more info at https://github.com/cri-o/cri-o/blob/master/tutorials/kubeadm.md
KUBELET_EXTRA_ARGS="--feature-gates=\"AllAlpha=false,RunAsGroup=true\" --container-runtime=remote --cgroup-driver=systemd --container-runtime-endpoint='unix:///var/run/crio/crio.sock' --runtime-request-timeout=5m"
# add Kublet extra args to /etc/default/kubelet if not there
grep -qxF "KUBELET_EXTRA_ARGS=${KUBELET_EXTRA_ARGS}" /etc/default/kubelet \
|| echo "KUBELET_EXTRA_ARGS=${KUBELET_EXTRA_ARGS}" \
| sudo tee /etc/default/kubelet
```

**Comment by ttys3** [comment]
> Hi, guys,
> Finally, I've found a solution. You should put "**--cgroup-driver=systemd**" to the **/var/lib/kubelet/kubeadm-flags.env** as _KUBELET_KUBEADM_ARGS_, then:
> 
> ```
> systemctl daemon-reload
> systemctl restart kubelet
> ```
> 
> and should work.

works like a charm

**Comment by haircommander** [comment]
eventually, we'll have better docs to describe how to configure this [PR here](https://github.com/cri-o/cri-o/pull/4440)
