### ISSUE TITLE
CRI-O in container (runc) with overlay2 throws Permission Denied

### ISSUE THREAD

**Issue by runcom** [kubernetes-incubator/cri-o#914]
```
2017-09-15T11:54:38.089860076-04:00 stderr /usr/bin/openshift-deploy: error while loading shared libraries: libpthread.so.0: cannot open shared object file: Permission denied
```
@giuseppe might be worth to change overlay2 to overlay and re-test in the Origin CI. You can see the failure here https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_conformance_crio/31/ (in `S3 Artifacts->pods/<id>/deployment_0.log`). I'll try to reproduce locally with the system container and atomic meanwhile...

/cc @mrunalp

**Comment by mrunalp** [comment]
cc: @rhatdan @nalind

**Comment by rhatdan** [comment]
Permission denied probably means SELinux.  Usually this means /var/lib/containers/storage is not labeled correctly or container-selinux does not have the fixes for CRI-O.

**Comment by rhatdan** [comment]
overlay2==overlay in containers storage. there is no difference.  We don't support old `overlay` driver from Docker.

**Comment by runcom** [comment]
There are no Avcs Dan, it sounds like a kernel issue, I'll post dmesg log but no selinux denials at all

**Comment by rhatdan** [comment]
Could you try it again in permissive mode?  
You could see if there is a dontaudit rule covering this up
Disable dontaudit rules

```
# semodule -DB
```
Get the test to fail, see if there are new AVCs.
Reenable dontaudit rules.
```
# semodule -B
```

**Comment by runcom** [comment]
still no AVCs... what's weird is that the error isn't happening anymore (e.g. https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_conformance_crio/35/) not sure what's going on...

**Comment by giuseppe** [comment]
it seems the same problem is seen here: https://bugzilla.redhat.com/show_bug.cgi?id=1489555

**Comment by rhatdan** [comment]
Looks like this is fixed now.  The bugzilla seems to be different.
