### ISSUE TITLE
RHT Secrets Support

### ISSUE THREAD

**Issue by mrguitar** [kubernetes-incubator/cri-o#919]
We need the ability to pass subscription certificates for RHEL. It would also be nice to have the secrets patch extended so that other directories can be user defined and passed into the container.

**Comment by runcom** [comment]
> It would also be nice to have the secrets patch extended so that other directories can be user defined and passed into the container.

we could certainly do this with something like the following conf:
```
/usr/share/rhel/secrets:/run/secrets
/etc/pki:/etc/pki
...
```
The only thing I'm worried is when these _default mounts_ are mounted? Meaning, should we mount them _after_ every other mount for the container/image/kube are set up? That would lead to one of these _default mount_ to override something coming from the container/image/kube. Or, should we mount these first thing and then mounts from image/container/kube are applied on top? That would lead, for instance, for someone to override `/etc/secrets` and `yum install` won't work in container.

**Comment by runcom** [comment]
@rhatdan @mrunalp @rhvgoyal @nalind PTAL

**Comment by rhatdan** [comment]
They are mounted last right now.  I don't think we want /etc/pki:/etc/pki/, We need these directories to be more specific.  /run/secrets is also a directory used by kubernetes?

**Comment by runcom** [comment]
> I don't think we want /etc/pki:/etc/pki/,

`/etc/pki:/etc/pki` is just an example of what _people_ might need and I've heard people actually willing to have this.

> /run/secrets is also a directory used by kubernetes

`/run/secrets` isn't used by kube afaict but we of course need it for entitlements.

> They are mounted last right now

So, are we ok in mounting these _always_ last? at the cost of overriding specific image/kube mounts? I'm saying this because, for `/run/...` at least, images shouldn't mount run as it should be a tmpfs and we can be pretty confident it's not going to break _a lot_.
Notice that when you mount in docker with `-v /a/silly/file:/etc/resolv.conf`, even if docker mounts a real resolv.conf, the `-v` overrides the real resolv. So `-v` is mounted last as well.
I'm just worried of people abusing this feature breaking almost everything.

**Comment by rhatdan** [comment]
I believe we should check if the /run/secrets is a mount point, we do nothing.  If it is not a mount point then we add it as a mount point.  That would probably work, the problem with volume mounting it is that we have to make sure SELinux works.  Currently SELinux allows reading all content in /usr.  If we start to mount in from /etc, we could have issues.

**Comment by runcom** [comment]
> I believe we should check if the /run/secrets is a mount point, we do nothing. If it is not a mount point then we add it as a mount point. That would probably work, the problem with volume mounting it is that we have to make sure SELinux works. Currently SELinux allows reading all content in /usr. If we start to mount in from /etc, we could have issues.

right, so allowing users to have generic mounts from host in containers isn't really feasible. We would basically allow reading from everywhere in selinux which might not be nice.
Should we start with just the RHEL stuff for entitlements and revisit this later for generic user provided mounts?

**Comment by rhatdan** [comment]
Perhaps we should just have a builtin mount points for CRI-O, where we could specify which directories would be mounted into the containers by default.  Then we just configure our RHEL/Fedora/Centos packages to mount /usr/share/rhel/secrets:/run/secrets by default

**Comment by runcom** [comment]
But they need to live under /usr right? Or selinux is broken

**Comment by rhatdan** [comment]
No they would have to set the labels correct if they want to allow them to be readonly in the containers.  We could explain in the man page how to do this. or give them suggestions.  Almost no one would do this.  So I don't see it as a huge problem and then it does not become a RHEL special sauce.

**Comment by runcom** [comment]
Fair enough, I'll work on this as soon as I can

**Comment by rhatdan** [comment]
@umohnani8 could you take thisone over?

**Comment by runcom** [comment]
@umohnani8 feel free to ping me for an overall design discussion as I though about a way to implement this :+1:

**Comment by umohnani8** [comment]
@rhatdan sure will take over.

**Comment by rhatdan** [comment]
Yes lets @runcom @umohnani8 and me work on the overall design.

**Comment by runcom** [comment]
Scheduled a meeting for tomorrow guys

**Comment by rhatdan** [comment]
This has been merged, closing.
