### ISSUE TITLE
kpod finished time is incorrect

### ISSUE THREAD

**Issue by baude** [kubernetes-incubator/cri-o#971]
Using kpod inspect, the finished time always reports:
        "finished": "0001-01-01T00:00:00Z"

**Comment by rhatdan** [comment]
@nalind Is this a storage issue?  Or is this field provided as part of container shutdown?

@mrunalp @runcom WDYT?

**Comment by mrunalp** [comment]
In cri-o it is set here https://github.com/kubernetes-incubator/cri-o/blob/master/oci/oci.go#L588
You can get it from the creation time of the exit file for kpod to get an accurate time.

**Comment by rhatdan** [comment]
@baude Did you fix this?

**Comment by baude** [comment]
nope

**Comment by baude** [comment]
@rhatdan I'll do this in libpod for kpod as we move over the container support.  Can you assign it to me ?

**Comment by rhatdan** [comment]
Done

**Comment by umohnani8** [comment]
This has been fixed - don't know when. Just tested inspect with a container and got the actual exit time.

**Comment by umohnani8** [comment]
@baude @rhatdan issue can be closed.
