### ISSUE TITLE
signature_policy file ignored in kpod load

### ISSUE THREAD

**Issue by moretea** [kubernetes-incubator/cri-o#997]
I'm trying to load a image with `kpod load --config=$CONFIG_FILE < $IMAGE_FILE`. My `signature_policy` file is in a non standard location.

According to [crio.conf.5.md](https://github.com/kubernetes-incubator/cri-o/blob/master/docs/crio.conf.5.md#crioruntime-table), I should set `crio.runtime.signature_policy` in my `$CONFIG_FILE`. The example in https://github.com/kubernetes-incubator/cri-o/blob/master/libkpod/testdata/config.toml sets `crio.image.signature_policy`.

Unfortunately, neither appear to have an effect; in both cases it tries to read `/etc/containers/policy.json`

**Comment by rhatdan** [comment]
@umohnani8 PTAL

**Comment by runcom** [comment]
Are we okay having kpod reading cri-o conf though?

**Comment by moretea** [comment]
I would prefer to be able to set the signature policy directly via a CLI argument, but it appeared that going through a `$CONFIG_FILE` is the only way that this setting might be exposed to `kpod`.

**Comment by rhatdan** [comment]
Don't tell anyone kpod pull --security-policy exists, it is a hidden option. used for testing.

**Comment by TomSweeneyRedHat** [comment]
FWIW, the 'kpod load' code is currently not handling the signature-policy file except to use the one in the default /etc/containers/policy.json. 

'kpod push' doesn't appear to be using the one from the conf file either, it's taking the one from the CLI argument if provided.

Like Dan said, pull has the cli argument, but it's undocumented.

I'll plan to add signature-policy as an argument unless I hear otherwise.

**Comment by mheon** [comment]
@runcom I think it's OK for now? We use a subset of the options in `crio.conf` (ignoring the ones for the gRPC API mostly) and don't need anything that's not in there, so for convenience's sake we have kpod just using the CRIO config file. If we ever need options that CRIO doesn't need, we'd have to revisit this.

**Comment by rhatdan** [comment]
I'm hesitant to tie kpod directly to crio for this other then both using the same default.  I think we can expose these options, if there is demand.

**Comment by mheon** [comment]
I strongly suspect we have some bugs throughout the image code related to handling of signature-policy and other containers/image configuration. Most of that code needs refactoring anyways - the interface isn't really pleasant to work with now. This is something we should look to fix as part of that.

**Comment by TomSweeneyRedHat** [comment]
@mheon true that, the authentication stuff also needs some polishing across the commands too.

**Comment by moretea** [comment]
So I don't have a `/etc/containers/policy.json`, because of me trying to package `cri-o` for [NixOS](https://nixos.org). I'm trying to specify an alternative file location.

Does have kpod's `--config` flag any at this moment then?

**Comment by TomSweeneyRedHat** [comment]
@moretea I've created PR  #1008 which hopefully will fix this issue for you.

**Comment by rhatdan** [comment]
Merged so closing.
